"""Differential ML-KEM vectors from OpenSSL 3.6.

    python3 tests/crypto/tools/mlkem_openssl.py

For each parameter set, three key pairs are generated by
`openssl genpkey -algorithm ML-KEM-N -pkeyopt hexseed:<d || z>` from
seeds drawn deterministically from SHAKE256 of a label (seed
`mlkem-openssl-1`). OpenSSL's own rendering of each key gives the
encapsulation key and the expanded decapsulation key. Each key pair
then answers:

- four encapsulations by `openssl pkeyutl -encap -pkeyopt hexikme:<m>`,
  OpenSSL's deterministic encapsulation with a given m (also drawn
  from SHAKE256): the ciphertext and OpenSSL's shared secret (kind
  `encap`);
- two of those ciphertexts with one byte flipped (a byte of c1, then
  the last byte of c2), decapsulated by `openssl pkeyutl -decap`: the
  implicit-rejection secret J(z || c) as OpenSSL computes it (kind
  `reject`).

Writes, the same bytes on every run:

- mlkem-openssl-keys.txt: set seed ek dk
- mlkem-openssl-kem.txt: set kind seed m c k (m is `-` for `reject`)
"""
import hashlib
import os
import re
import subprocess
import sys
import tempfile

from mlkem_util import hx, params, write

OPENSSL = "/opt/homebrew/bin/openssl"
SEED = "mlkem-openssl-1"


def run(args, data=None):
    r = subprocess.run([OPENSSL] + args, input=data, capture_output=True)
    if r.returncode != 0:
        sys.exit(f"openssl {' '.join(args)}: exit {r.returncode}\n{r.stderr.decode(errors='replace')}")
    return r.stdout


def section(text, name):
    """The bytes of the colon-hex block after `name:` in OpenSSL's text."""
    m = re.search(rf"^{name}:\n((?:    .*\n)+)", text, re.M)
    if not m:
        sys.exit(f"no {name} in OpenSSL's key text")
    return bytes.fromhex(re.sub(r"[\s:]", "", m.group(1)))


def main():
    version = run(["version"]).decode().strip()
    keys, kem = [], []
    with tempfile.TemporaryDirectory() as tmp:
        for (n, k) in (("512", 2), ("768", 3), ("1024", 4)):
            ek_len, dk_len, ct_len = params(k)
            du = 11 if k == 4 else 10
            for i in range(3):
                seed = hashlib.shake_256(f"{SEED}/{n}/{i}".encode()).digest(64)
                priv = os.path.join(tmp, "k.pem")
                pub = os.path.join(tmp, "p.pem")
                run(["genpkey", "-algorithm", f"ML-KEM-{n}", "-pkeyopt", f"hexseed:{seed.hex()}", "-out", priv])
                run(["pkey", "-in", priv, "-pubout", "-out", pub])
                text = run(["pkey", "-in", priv, "-text", "-noout"]).decode()
                if section(text, "seed") != seed:
                    sys.exit("OpenSSL did not keep the seed")
                ek, dk = section(text, "ek"), section(text, "dk")
                if len(ek) != ek_len or len(dk) != dk_len:
                    sys.exit(f"ML-KEM-{n}: unexpected key lengths")
                keys.append(f"{n} {hx(seed)} {hx(ek)} {hx(dk)}")
                cts = []
                for j in range(4):
                    ctf, ssf = os.path.join(tmp, "c"), os.path.join(tmp, "s")
                    m = hashlib.shake_256(f"{SEED}/{n}/{i}/m{j}".encode()).digest(32)
                    run(["pkeyutl", "-encap", "-pubin", "-inkey", pub, "-pkeyopt", f"hexikme:{m.hex()}",
                         "-out", ctf, "-secret", ssf])
                    c, s = open(ctf, "rb").read(), open(ssf, "rb").read()
                    if len(c) != ct_len or len(s) != 32:
                        sys.exit("unexpected encapsulation lengths")
                    cts.append(c)
                    kem.append(f"{n} encap {hx(seed)} {hx(m)} {hx(c)} {hx(s)}")
                for (j, pos) in ((0, 7), (1, ct_len - 1)):
                    c = bytearray(cts[j])
                    c[pos] ^= 1
                    ctf, ssf = os.path.join(tmp, "c"), os.path.join(tmp, "s")
                    open(ctf, "wb").write(bytes(c))
                    run(["pkeyutl", "-decap", "-inkey", priv, "-in", ctf, "-secret", ssf])
                    s = open(ssf, "rb").read()
                    if s != hashlib.shake_256(seed[32:] + bytes(c)).digest(32):
                        sys.exit("OpenSSL's rejection secret is not J(z || c)")
                    kem.append(f"{n} reject {hx(seed)} - {hx(bytes(c))} {hx(s)}")
    gen = "sha256: - (generated, not downloaded)"
    extract = f"extract: tests/crypto/tools/mlkem_openssl.py (seed {SEED})"
    write("mlkem-openssl-keys.txt", [f"source: {version}, openssl genpkey -pkeyopt hexseed and pkey -text", gen,
                                     extract, "fields: set seed ek dk"], keys)
    write("mlkem-openssl-kem.txt", [f"source: {version}, openssl pkeyutl -encap -pkeyopt hexikme and -decap", gen, extract,
                                    "fields: set kind seed m c k"], kem)


if __name__ == "__main__":
    main()
