//! Emit the Axiom binding module for a crate's `#[axiom_export]` surface.
//!
//! This reads the Rust SOURCE rather than the compiled artifact, the way
//! `cbindgen` does. The alternative — a runtime registry built with
//! life-before-main constructors — does not survive `no_std`, and
//! `no_std` is the mode that keeps Axiom freestanding, so it would have
//! ruled out the more valuable of the two build modes.
//!
//! Because this is a second, independent pass over the same annotations
//! the proc macro reads, the two could drift. They cannot now: both use
//! `axiom-ffi-classify` for the type table, the attribute grammar and
//! the symbol names, and `scripts/check-ffi.sh` still regenerates the
//! checked-in modules and fails if they differ.
//!
//! # The module shape
//!
//! ```text
//! ; GENERATED by axiom-bindgen from the `axiom_demo` crate. Do not edit.
//! (import Ffi)
//! (import Err)                       ; only when a Result wrapper exists
//!
//! (pub extern "axiom_demo"
//!   (add :: (-> Int Int Int) (symbol "axffi_add"))
//!   (shoutRaw :: (-> String Int Int) (symbol "axffi_shout"))
//!   (counterNewRaw :: (-> Int Foreign) (symbol "axffi_counter_new"))
//!   (counterDropFn :: Int (symbol "axffi_counter_drop_fn")))
//!
//! (pub data Counter (Counter Handle))  ; one per #[axiom_opaque] type
//! (pub :: counterClose (-> Counter Int))
//! (pub :: counterNew (-> Int Counter))
//! (pub :: shout (-> String String))
//! ```
//!
//! Every shim that returns bytes, words, strings or can fail takes a
//! trailing out-cell, its raw binding carries a `Raw` suffix, and the
//! ergonomic name is an Axiom wrapper that allocates the cell through
//! `Ffi.ax`, calls, decodes and frees. An opaque value is wrapped in a
//! `Handle` that carries the type's drop function, so the Rust value
//! dies with its last Axiom reference. A `Vec<i64>` / `Vec<String>`
//! return becomes an Axiom `Vec` (an `Int` handle) through
//! `ffiWordsToVec` / `ffiStrsToVec`, freed on the Rust side with
//! `ffiFreeWords` / `ffiFreeStrList`; a `&[i64]` parameter is a `Vec`
//! handle passed through as `Int`; a callback (`AxFn1..3`) is bound
//! under its arrow type, `(-> Int Int)` and so on, and passed through.
//! Every generated local is `__`-prefixed so a Rust parameter named
//! `cell` or `p` is never shadowed.
//!
//! The output is byte-for-byte what `axiom fmt` produces for it: the
//! printer in [`sexp`] follows the formatter's structural rules (an
//! application stays on one line iff its head and at most four
//! arguments are all "simple"; `let`, `if` and `match` always break;
//! every top-level declaration is separated by a blank line).

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use axiom_ffi_classify as cls;
use cls::{Param, Payload, Ret, Scalar};

pub mod sexp;
use sexp::{app, atom, Ex};

/// A generation failure: a message for the user, already worded.
#[derive(Debug)]
pub struct Error(pub String);

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

type Result<T> = std::result::Result<T, Error>;

/// Generate the module for the `.rs` files under `src_root`, binding the
/// archive `lib<lib>.a`.
pub fn generate(src_root: &Path, lib: &str) -> Result<String> {
    let mut files = Vec::new();
    collect_rs(src_root, &mut files);
    files.sort();
    if files.is_empty() {
        return Err(Error(format!("no `.rs` files under {}", src_root.display())));
    }

    let mut surface = Surface::default();
    for f in &files {
        let text = fs::read_to_string(f)
            .map_err(|e| Error(format!("{}: {e}", f.display())))?;
        let ast = syn::parse_file(&text)
            .map_err(|e| Error(format!("{}: {e}", f.display())))?;
        let file = f.strip_prefix(src_root).unwrap_or(f).display().to_string();
        surface.walk(&ast.items, &file, "")?;
    }
    surface.validate()?;
    Ok(surface.render(lib))
}

fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect_rs(&p, out)
        } else if p.extension().map(|x| x == "rs").unwrap_or(false) {
            out.push(p)
        }
    }
}

fn attr_named<'a>(attrs: &'a [syn::Attribute], name: &str) -> Option<&'a syn::Attribute> {
    attrs
        .iter()
        .find(|a| a.path().segments.last().map(|s| s.ident == name).unwrap_or(false))
}

fn attr_metas(a: &syn::Attribute) -> std::result::Result<Vec<syn::Meta>, String> {
    match &a.meta {
        syn::Meta::Path(_) => Ok(Vec::new()),
        syn::Meta::List(_) => a
            .parse_args_with(
                syn::punctuated::Punctuated::<syn::Meta, syn::Token![,]>::parse_terminated,
            )
            .map(|p| p.into_iter().collect())
            .map_err(|e| e.to_string()),
        syn::Meta::NameValue(_) => Err("expected a key list in parentheses".into()),
    }
}

/// One `#[axiom_opaque]` type.
#[derive(Clone, Debug)]
struct Opaque {
    name: String,
    stem: String,
    at: String,
}

/// One exported function (or one hand-written `axffi_*` shim).
#[derive(Clone, Debug)]
struct Decl {
    rust_name: String,
    axiom_name: String,
    symbol: String,
    /// `(wrapper parameter name, classification)`.
    params: Vec<(String, Param)>,
    ret: Ret,
    /// A hand-written `axffi_*` shim: bound as a plain item, never wrapped.
    raw: bool,
    /// Where it was declared, for messages.
    at: String,
}

#[derive(Default)]
struct Surface {
    decls: Vec<Decl>,
    opaques: Vec<Opaque>,
}

impl Surface {
    /// Walk a module's items, recursing into inline `mod` bodies. `path`
    /// is the module path for messages (`inner::deeper`).
    fn walk(&mut self, items: &[syn::Item], file: &str, path: &str) -> Result<()> {
        for item in items {
            match item {
                syn::Item::Fn(f) => self.visit_fn(f, file, path)?,
                syn::Item::Struct(s) => self.visit_opaque(&s.attrs, &s.ident, file, path)?,
                syn::Item::Enum(e) => self.visit_opaque(&e.attrs, &e.ident, file, path)?,
                syn::Item::Mod(m) => {
                    if let Some((_, inner)) = &m.content {
                        let sub = if path.is_empty() {
                            m.ident.to_string()
                        } else {
                            format!("{path}::{}", m.ident)
                        };
                        self.walk(inner, file, &sub)?;
                    }
                    // `mod x;` lives in its own file, which the directory
                    // walk already found.
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn visit_opaque(
        &mut self,
        attrs: &[syn::Attribute],
        ident: &syn::Ident,
        file: &str,
        path: &str,
    ) -> Result<()> {
        let Some(a) = attr_named(attrs, "axiom_opaque") else { return Ok(()) };
        let at = where_(file, path, &ident.to_string());
        let metas = attr_metas(a).map_err(|m| Error(format!("{at}: `#[axiom_opaque]`: {m}")))?;
        let parsed = cls::parse_opaque_attr(metas.iter())
            .map_err(|e| Error(format!("{at}: {}", e.message)))?;
        let name = ident.to_string();
        let stem = cls::opaque_stem(&name, &parsed);
        self.opaques.push(Opaque { name, stem, at });
        Ok(())
    }

    fn visit_fn(&mut self, f: &syn::ItemFn, file: &str, path: &str) -> Result<()> {
        let rust_name = f.sig.ident.to_string();
        let at = where_(file, path, &rust_name);
        let is_pub = matches!(f.vis, syn::Visibility::Public(_));
        if let Some(a) = attr_named(&f.attrs, "axiom_export") {
            // The macro refuses a non-`pub` export; a source tree that
            // compiles never has one, so this only mirrors that rule.
            if !is_pub {
                return Ok(());
            }
            let metas = attr_metas(a)
                .map_err(|m| Error(format!("{at}: `#[axiom_export]`: {m}")))?;
            let attr = cls::parse_export_attr(metas.iter())
                .map_err(|e| Error(format!("{at}: {}", e.message)))?;
            let mut params = Vec::new();
            for (i, arg) in f.sig.inputs.iter().enumerate() {
                let syn::FnArg::Typed(pt) = arg else {
                    return Err(Error(format!("{at}: `self` cannot cross the boundary")));
                };
                let pname = match &*pt.pat {
                    syn::Pat::Ident(id) => id.ident.to_string(),
                    _ => format!("__arg{}", i + 1),
                };
                if pname.starts_with("__") && !pname.starts_with("__arg") {
                    return Err(Error(format!(
                        "{at}: parameter `{pname}`: names starting with `__` are reserved \
                         for the generated wrapper's own locals"
                    )));
                }
                let p = cls::classify_param(&pt.ty).map_err(|m| Error(format!("{at}: {m}")))?;
                params.push((cls::camel_case(&pname), p));
            }
            let ret_ty = match &f.sig.output {
                syn::ReturnType::Default => None,
                syn::ReturnType::Type(_, t) => Some(&**t),
            };
            let ret = cls::classify_return(ret_ty).map_err(|m| Error(format!("{at}: {m}")))?;
            self.decls.push(Decl {
                axiom_name: cls::camel_case(&rust_name),
                symbol: cls::export_symbol(&rust_name, &attr),
                rust_name,
                params,
                ret,
                raw: false,
                at,
            });
        } else if let Some(d) = raw_shim(f, &at) {
            // A HAND-WRITTEN `pub extern "C" fn axffi_*`. Bound as a plain
            // extern item over words: `AxWord` parameters are `Foreign`,
            // integers are `Int`, the return is `Int`.
            self.decls.push(d);
        }
        Ok(())
    }

    fn validate(&self) -> Result<()> {
        // Every opaque type at the boundary must be marked.
        let marked: BTreeSet<&str> = self.opaques.iter().map(|o| o.name.as_str()).collect();
        for d in self.decls.iter().filter(|d| !d.raw) {
            let mut used: Vec<&str> = Vec::new();
            for (_, p) in &d.params {
                if let Param::Opaque { ty, .. } = p {
                    used.push(&ty.name);
                }
            }
            match &d.ret {
                Ret::Opaque(o) => used.push(&o.name),
                Ret::Result(Payload::Opaque(o)) | Ret::Option(Payload::Opaque(o)) => {
                    used.push(&o.name)
                }
                _ => {}
            }
            for t in used {
                if !marked.contains(t) {
                    return Err(Error(format!(
                        "{}: `{t}` crosses the boundary as an opaque handle but no \
                         `#[axiom_opaque]` declaration of `{t}` was found under the source \
                         root; mark the type (it generates the destructor the handle needs)",
                        d.at
                    )));
                }
            }
        }
        // Opaque type names are unique.
        let mut seen: BTreeMap<&str, &Opaque> = BTreeMap::new();
        for o in &self.opaques {
            if let Some(prev) = seen.insert(&o.name, o) {
                return Err(Error(format!(
                    "two `#[axiom_opaque]` types are both named `{}` ({} and {}); the Axiom \
                     `data` they bind to is one flat namespace",
                    o.name, prev.at, o.at
                )));
            }
        }
        // Every value name the module defines is unique.
        let mut names: BTreeMap<String, String> = BTreeMap::new();
        let mut claim = |name: String, origin: String| -> Result<()> {
            if let Some(prev) = names.insert(name.clone(), origin.clone()) {
                return Err(Error(format!(
                    "Axiom name `{name}` is generated twice: for {prev} and for {origin}; \
                     rename one (camelCase folds `foo_bar` and `fooBar` together, and \
                     wrapped items also claim `<name>Raw`)"
                )));
            }
            Ok(())
        };
        for o in &self.opaques {
            let t = &o.name;
            claim(format!("{}DropFn", lower_first(t)), format!("the drop function of `{t}`"))?;
            claim(format!("{}Close", lower_first(t)), format!("the close wrapper of `{t}`"))?;
        }
        for d in &self.decls {
            let origin = format!("`{}` ({})", d.rust_name, d.at);
            claim(d.axiom_name.clone(), origin.clone())?;
            if d.needs_wrapper() {
                claim(format!("{}Raw", d.axiom_name), origin)?;
            }
        }
        Ok(())
    }

    fn render(&self, lib: &str) -> String {
        let mut decls: Vec<&Decl> = self.decls.iter().collect();
        decls.sort_by(|a, b| a.axiom_name.cmp(&b.axiom_name));
        let mut opaques: Vec<&Opaque> = self.opaques.iter().collect();
        opaques.sort_by(|a, b| a.name.cmp(&b.name));

        let needs_err = decls.iter().any(|d| matches!(d.ret, Ret::Result(_)));

        let mut out = String::new();
        out.push_str(&format!(
            "; GENERATED by axiom-bindgen from the `{lib}` crate. Do not edit.\n"
        ));
        let mut tops: Vec<String> = Vec::new();
        tops.push("(import Ffi)".into());
        if needs_err {
            tops.push("(import Err)".into());
        }

        // The extern block: one item per raw shim, plus the drop-function
        // probe of every opaque type.
        let mut items: Vec<(String, String)> = Vec::new();
        for d in &decls {
            items.push((d.raw_name(), format!("{} (symbol \"{}\")", d.raw_type(), d.symbol)));
        }
        for o in &opaques {
            items.push((
                format!("{}DropFn", lower_first(&o.name)),
                format!("Int (symbol \"{}\")", cls::drop_fn_symbol(&o.stem)),
            ));
        }
        items.sort();
        let mut block = format!("(pub extern \"{lib}\"");
        for (name, rest) in &items {
            block.push_str(&format!("\n  ({name} :: {rest})"));
        }
        block.push(')');
        tops.push(block);

        // One `data` per opaque type, with its close wrapper.
        for o in &opaques {
            let t = &o.name;
            tops.push(format!(
                "; `{t}` is a Rust value held through a `Handle`: when the last\n\
                 ; reference dies the handle runs `{}`.\n\
                 (pub data {t}\n  ({t} Handle))",
                cls::drop_symbol(&o.stem)
            ));
            let close = format!("{}Close", lower_first(t));
            tops.push(format!("(pub :: {close} (-> {t} Int))"));
            let body = Ex::Match(
                Box::new(atom("c")),
                vec![(app(vec![atom(t), atom("__h")]), app(vec![atom("ffiHandleClose"), atom("__h")]))],
            );
            tops.push(sexp::decl_fn(&close, &["c".to_string()], &body));
        }

        // The wrappers.
        for d in &decls {
            if !d.needs_wrapper() {
                continue;
            }
            tops.push(format!("(pub :: {} {})", d.axiom_name, d.wrapper_type()));
            let params: Vec<String> = d.params.iter().map(|(n, _)| n.clone()).collect();
            tops.push(sexp::decl_fn(&d.axiom_name, &params, &d.wrapper_body()));
        }

        out.push_str(&tops.join("\n\n"));
        out.push('\n');
        out
    }
}

fn where_(file: &str, path: &str, name: &str) -> String {
    if path.is_empty() {
        format!("{file}: `{name}`")
    } else {
        format!("{file}: `{path}::{name}`")
    }
}

fn lower_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

/// A hand-written `#[no_mangle] pub extern "C" fn axffi_*`, bound raw.
fn raw_shim(f: &syn::ItemFn, at: &str) -> Option<Decl> {
    let name = f.sig.ident.to_string();
    if !name.starts_with("axffi_") {
        return None;
    }
    if !matches!(f.vis, syn::Visibility::Public(_)) {
        return None;
    }
    f.sig.abi.as_ref()?;
    let mut params = Vec::new();
    for (i, a) in f.sig.inputs.iter().enumerate() {
        let syn::FnArg::Typed(pt) = a else { return None };
        let n = match &*pt.pat {
            syn::Pat::Ident(id) => id.ident.to_string(),
            _ => format!("__arg{}", i + 1),
        };
        // `AxWord` is the crate's word for "an opaque word": `Foreign`.
        // A plain integer is a number: `Int`. The word is modelled as an
        // opaque borrow, which renders as `Foreign`; a raw shim never
        // gets a wrapper, so the pseudo-type is never looked up.
        let is_word = matches!(&*pt.ty, syn::Type::Path(p)
            if p.path.segments.last().map(|s| s.ident == "AxWord").unwrap_or(false));
        let p = if is_word {
            Param::Opaque {
                ty: cls::OpaqueTy { ty: (*pt.ty).clone(), name: "AxWord".into() },
                mutable: false,
            }
        } else {
            Param::Scalar(Scalar::I64)
        };
        params.push((cls::camel_case(&n), p));
    }
    Some(Decl {
        axiom_name: cls::camel_case(name.trim_start_matches("axffi_")),
        symbol: name.clone(),
        rust_name: name,
        params,
        ret: Ret::Scalar(Scalar::I64),
        raw: true,
        at: at.to_string(),
    })
}

fn payload_axiom_type(p: &Payload) -> String {
    match p {
        Payload::Scalar(s) => s.axiom_type().to_string(),
        Payload::Bytes => "String".into(),
        // A `Vec` is an `Int` handle in the stdlib.
        Payload::Words | Payload::Strs => "Int".into(),
        Payload::Opaque(o) => o.name.clone(),
    }
}

/// The Axiom type of a parameter as the RAW extern item declares it.
fn param_raw_type(p: &Param) -> String {
    match p {
        Param::Scalar(s) => s.axiom_type().to_string(),
        Param::Str | Param::Bytes => "String".into(),
        Param::Opaque { .. } => "Foreign".into(),
        Param::Words => "Int".into(),
        Param::Callback(n) => callback_type(*n),
    }
}

/// `(-> Int Int)` for one argument, and so on: the arrow type a
/// callback parameter carries on both the raw item and the wrapper.
fn callback_type(arity: u8) -> String {
    let mut t = String::from("(->");
    for _ in 0..=arity {
        t.push_str(" Int");
    }
    t.push(')');
    t
}

/// The Ffi.ax pair that builds an Axiom value from a cell-carried
/// collection and frees the Rust side: `(build, free)`.
fn collection_helpers(p: &Payload) -> (&'static str, &'static str) {
    match p {
        Payload::Bytes => ("ffiBytesToStr", "ffiFreeBytes"),
        Payload::Words => ("ffiWordsToVec", "ffiFreeWords"),
        Payload::Strs => ("ffiStrsToVec", "ffiFreeStrList"),
        _ => unreachable!("only collections ride the cell as (ptr, n)"),
    }
}

/// The payload a direct collection return carries.
fn direct_payload(r: &Ret) -> Payload {
    match r {
        Ret::Bytes => Payload::Bytes,
        Ret::Words => Payload::Words,
        Ret::Strs => Payload::Strs,
        _ => unreachable!("not a direct collection return"),
    }
}

impl Decl {
    /// Whether the symbol is bound under `<name>Raw` with an Axiom
    /// wrapper over it.
    fn needs_wrapper(&self) -> bool {
        if self.raw {
            return false;
        }
        self.ret.needs_cell()
            || matches!(self.ret, Ret::Opaque(_))
            || self.params.iter().any(|(_, p)| matches!(p, Param::Opaque { .. }))
    }

    fn raw_name(&self) -> String {
        if self.needs_wrapper() {
            format!("{}Raw", self.axiom_name)
        } else {
            self.axiom_name.clone()
        }
    }

    /// The raw extern's type: the shim's real arity over wire types.
    fn raw_type(&self) -> String {
        let mut ps: Vec<String> = self.params.iter().map(|(_, p)| param_raw_type(p)).collect();
        let ret = if self.ret.needs_cell() {
            ps.push("Int".into());
            "Int".to_string()
        } else {
            match &self.ret {
                Ret::Scalar(s) => s.axiom_type().to_string(),
                Ret::Opaque(_) => "Foreign".into(),
                _ => unreachable!(),
            }
        };
        arrow(&ps, &ret)
    }

    /// The wrapper's Axiom-facing type.
    fn wrapper_type(&self) -> String {
        let ps: Vec<String> = self
            .params
            .iter()
            .map(|(_, p)| match p {
                Param::Opaque { ty, .. } => ty.name.clone(),
                other => param_raw_type(other),
            })
            .collect();
        let ret = match &self.ret {
            Ret::Scalar(s) => s.axiom_type().to_string(),
            Ret::Opaque(o) => o.name.clone(),
            Ret::Bytes | Ret::Words | Ret::Strs => payload_axiom_type(&direct_payload(&self.ret)),
            Ret::Result(p) => format!("(Result {} String)", payload_axiom_type(p)),
            Ret::Option(p) => format!("(Option {})", payload_axiom_type(p)),
        };
        arrow(&ps, &ret)
    }

    /// The wrapper body. Opaque parameters are unwrapped by nested
    /// `match`es, then one `let` binds the raw pointers, the call and
    /// the decoded result, in order.
    fn wrapper_body(&self) -> Ex {
        // The raw call's arguments and the pointer bindings they need.
        let mut binds: Vec<(String, Ex)> = Vec::new();
        let mut args: Vec<Ex> = Vec::new();
        let mut handles: Vec<(String, String, String)> = Vec::new(); // (param, type, __hN)
        for (i, (name, p)) in self.params.iter().enumerate() {
            match p {
                Param::Opaque { ty, .. } => {
                    let h = format!("__h{i}");
                    let a = format!("__a{i}");
                    binds.push((
                        a.clone(),
                        Ex::Cast("Foreign".into(), Box::new(app(vec![atom("ffiHandlePtr"), atom(&h)]))),
                    ));
                    args.push(atom(&a));
                    handles.push((name.clone(), ty.name.clone(), h));
                }
                _ => args.push(atom(name)),
            }
        }
        let raw = self.raw_name();
        let mut call = vec![atom(&raw)];
        call.extend(args);

        let body = match &self.ret {
            Ret::Scalar(_) => {
                binds.push(("__r".into(), app(call)));
                Ex::Let(binds, Box::new(atom("__r")))
            }
            Ret::Opaque(o) => {
                binds.push(("__p".into(), Ex::Cast("Int".into(), Box::new(app(call)))));
                binds.push((
                    "__h".into(),
                    app(vec![atom("ffiHandleNew"), atom("__p"), atom(&drop_fn_name(&o.name))]),
                ));
                Ex::Let(binds, Box::new(app(vec![atom(&o.name), atom("__h")])))
            }
            Ret::Bytes | Ret::Words | Ret::Strs => {
                let (build, free) = collection_helpers(&direct_payload(&self.ret));
                call.push(atom("__c"));
                binds.push(("__c".into(), atom("ffiCellNew")));
                binds.push(("__st".into(), app(call)));
                binds.push(("__p".into(), app(vec![atom("ffiCellWord"), atom("__c"), atom("0")])));
                binds.push(("__n".into(), app(vec![atom("ffiCellWord"), atom("__c"), atom("1")])));
                binds.push(("__v".into(), app(vec![atom(build), atom("__p"), atom("__n")])));
                Ex::Let(
                    binds,
                    Box::new(Ex::Block(vec![
                        app(vec![atom(free), atom("__p"), atom("__n")]),
                        app(vec![atom("ffiCellFree"), atom("__c")]),
                        atom("__v"),
                    ])),
                )
            }
            Ret::Result(p) | Ret::Option(p) => {
                let is_result = matches!(self.ret, Ret::Result(_));
                call.push(atom("__c"));
                binds.push(("__c".into(), atom("ffiCellNew")));
                binds.push(("__st".into(), app(call)));
                binds.push(("__p".into(), app(vec![atom("ffiCellWord"), atom("__c"), atom("0")])));
                binds.push(("__n".into(), app(vec![atom("ffiCellWord"), atom("__c"), atom("1")])));
                let ctor = if is_result { "Ok" } else { "Some" };
                // A Float payload is the word reinterpreted. The cast is
                // bound up front (harmless on the error path, where the
                // word is a pointer nothing reads as a Float) so the
                // `Ok`/`Some` application stays on one line.
                if matches!(p, Payload::Scalar(s) if s.is_float()) {
                    binds.push(("__f".into(), Ex::Cast("Float".into(), Box::new(atom("__p")))));
                }
                let ok = match p {
                    Payload::Bytes | Payload::Words | Payload::Strs => {
                        let (build, free) = collection_helpers(p);
                        Ex::Let(
                            vec![("__v".into(), app(vec![atom(build), atom("__p"), atom("__n")]))],
                            Box::new(Ex::Block(vec![
                                app(vec![atom(free), atom("__p"), atom("__n")]),
                                app(vec![atom("ffiCellFree"), atom("__c")]),
                                app(vec![atom(ctor), atom("__v")]),
                            ])),
                        )
                    }
                    other => {
                        let value = match other {
                            Payload::Scalar(s) if s.is_float() => atom("__f"),
                            Payload::Scalar(Scalar::Bool) => {
                                app(vec![atom("!="), atom("__p"), atom("0")])
                            }
                            Payload::Scalar(_) => atom("__p"),
                            Payload::Opaque(o) => app(vec![
                                atom(&o.name),
                                app(vec![atom("ffiHandleNew"), atom("__p"), atom(&drop_fn_name(&o.name))]),
                            ]),
                            Payload::Bytes | Payload::Words | Payload::Strs => unreachable!(),
                        };
                        Ex::Block(vec![
                            app(vec![atom("ffiCellFree"), atom("__c")]),
                            app(vec![atom(ctor), value]),
                        ])
                    }
                };
                let not_ok = if is_result {
                    Ex::Let(
                        vec![("__m".into(), app(vec![atom("ffiBytesToStr"), atom("__p"), atom("__n")]))],
                        Box::new(Ex::Block(vec![
                            app(vec![atom("ffiFreeBytes"), atom("__p"), atom("__n")]),
                            app(vec![atom("ffiCellFree"), atom("__c")]),
                            app(vec![atom("Err"), atom("__m")]),
                        ])),
                    )
                } else {
                    Ex::Block(vec![app(vec![atom("ffiCellFree"), atom("__c")]), atom("None")])
                };
                Ex::Let(
                    binds,
                    Box::new(Ex::If(
                        Box::new(app(vec![atom("=="), atom("__st"), atom("0")])),
                        Box::new(ok),
                        Box::new(not_ok),
                    )),
                )
            }
        };

        // Unwrap the handles, innermost last: `(match c ((Counter __h0) body))`.
        let mut wrapped = body;
        for (param, ty, h) in handles.into_iter().rev() {
            wrapped = Ex::Match(
                Box::new(atom(&param)),
                vec![(app(vec![atom(&ty), atom(&h)]), wrapped)],
            );
        }
        wrapped
    }
}

fn drop_fn_name(type_name: &str) -> String {
    format!("{}DropFn", lower_first(type_name))
}

fn arrow(ps: &[String], ret: &str) -> String {
    if ps.is_empty() {
        ret.to_string()
    } else {
        format!("(-> {} {})", ps.join(" "), ret)
    }
}
