//! Emit the Axiom binding module for a crate's `#[axiom_export]` surface.
//!
//! This reads the Rust SOURCE rather than the compiled artifact, the way
//! `cbindgen` does. The alternative — a runtime registry built with
//! life-before-main constructors — does not survive `no_std`, and
//! `no_std` is the mode that keeps Axiom freestanding, so it would have
//! ruled out the more valuable of the two build modes.
//!
//! Because this is a second, independent pass over the same annotations
//! the proc macro reads, the two could drift. They cannot now: both use
//! `axiom-ffi-classify` for the type table, the attribute grammar and
//! the symbol names, and `scripts/check-ffi.sh` still regenerates the
//! checked-in modules and fails if they differ.
//!
//! # The module shape
//!
//! ```text
//! ; GENERATED by axiom-bindgen from the `axiom_demo` crate. Do not edit.
//! (import Ffi)
//! (import Err)                       ; only when a Result wrapper exists
//!
//! (pub extern "axiom_demo"
//!   (add :: (-> Int Int Int) (symbol "axffi_add"))
//!   (shoutRaw :: (-> String Int Int) (symbol "axffi_shout"))
//!   (counterNewRaw :: (-> Int Foreign) (symbol "axffi_counter_new"))
//!   (counterDropFn :: Int (symbol "axffi_counter_drop_fn")))
//!
//! (pub data Counter (Counter Handle))  ; one per #[axiom_opaque] type
//! (pub :: counterClose (-> Counter Int))
//! (pub :: counterNew (-> Int Counter))
//! (pub :: shout (-> String String))
//! ```
//!
//! Every shim that returns bytes, words, strings, a record or can fail
//! takes a trailing out-cell, its raw binding carries a `Raw` suffix,
//! and the ergonomic name is an Axiom wrapper that allocates the cell
//! through `Ffi.ax`, calls, decodes and frees. An opaque value is
//! wrapped in a `Handle` that carries the type's drop function, so the
//! Rust value dies with its last Axiom reference. A `Vec<T>` /
//! `Vec<String>` return becomes an Axiom `Vec` (an `Int` handle)
//! through `ffiWordsToVec` / `ffiStrsToVec`, freed on the Rust side
//! with `ffiFreeWords` / `ffiFreeStrList`; a `&[T]` or `&[&str]`
//! parameter is a `Vec` handle passed through as `Int`; a callback
//! (`AxFn1..3`) is bound under its arrow type, `(-> Int Int)` and so
//! on, and passed through. An `#[axiom_record]` struct is a `data`
//! type with one positional field per Rust field: a parameter is
//! destructured into one raw argument per field, a result is rebuilt
//! from a cell of one word per field (`ffiCellNewN`). A `Vec<Record>`
//! result and a `&[Record]` parameter go through two module-private
//! loops per record type - `__pointFromWords` rebuilds a `Vec` of
//! records from `n * ARITY` Rust words (`ffiWordAt`), `__pointToWords`
//! flattens a `Vec` of records into the words the shim chunks - the
//! one thing a generated module declares for itself, because the
//! record's shape is the crate's. A `Vec<Vec<T>>` result is
//! `ffiWordListsToVec` / `ffiFreeWordLists`; a nested
//! `Result<Option<T>, E>` / `Option<Result<T, E>>` nests the
//! constructors over the same three statuses. Every generated local
//! is `__`-prefixed so a Rust parameter named `cell` or `p` is never
//! shadowed.
//!
//! The output is byte-for-byte what `axiom fmt` produces for it: the
//! printer in [`sexp`] follows the formatter's structural rules (an
//! application stays on one line iff its head and at most four
//! arguments are all "simple"; `let`, `if` and `match` always break;
//! every top-level declaration is separated by a blank line).

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use axiom_ffi_classify as cls;
use cls::{Named, Param, Payload, RecordField, RecordTy, Registry, Ret, Scalar};

pub mod sexp;
use sexp::{app, atom, Ex};

/// A generation failure: a message for the user, already worded.
#[derive(Debug)]
pub struct Error(pub String);

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

type Result<T> = std::result::Result<T, Error>;

/// Generate the module for the `.rs` files under `src_root`, binding the
/// archive `lib<lib>.a`.
pub fn generate(src_root: &Path, lib: &str) -> Result<String> {
    let mut files = Vec::new();
    collect_rs(src_root, &mut files);
    files.sort();
    if files.is_empty() {
        return Err(Error(format!("no `.rs` files under {}", src_root.display())));
    }

    let mut parsed = Vec::new();
    for f in &files {
        let text = fs::read_to_string(f)
            .map_err(|e| Error(format!("{}: {e}", f.display())))?;
        let ast = syn::parse_file(&text)
            .map_err(|e| Error(format!("{}: {e}", f.display())))?;
        let file = f.strip_prefix(src_root).unwrap_or(f).display().to_string();
        parsed.push((file, ast));
    }
    // Two passes: the types first, so a function that names a record
    // or a handle is classified against the whole source root whatever
    // file or order it appears in.
    let mut surface = Surface::default();
    for (file, ast) in &parsed {
        surface.walk_types(&ast.items, file, "")?;
    }
    for (file, ast) in &parsed {
        surface.walk_fns(&ast.items, file, "")?;
    }
    surface.validate()?;
    Ok(surface.render(lib))
}

fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect_rs(&p, out)
        } else if p.extension().map(|x| x == "rs").unwrap_or(false) {
            out.push(p)
        }
    }
}

fn attr_named<'a>(attrs: &'a [syn::Attribute], name: &str) -> Option<&'a syn::Attribute> {
    attrs
        .iter()
        .find(|a| a.path().segments.last().map(|s| s.ident == name).unwrap_or(false))
}

fn attr_metas(a: &syn::Attribute) -> std::result::Result<Vec<syn::Meta>, String> {
    match &a.meta {
        syn::Meta::Path(_) => Ok(Vec::new()),
        syn::Meta::List(_) => a
            .parse_args_with(
                syn::punctuated::Punctuated::<syn::Meta, syn::Token![,]>::parse_terminated,
            )
            .map(|p| p.into_iter().collect())
            .map_err(|e| e.to_string()),
        syn::Meta::NameValue(_) => Err("expected a key list in parentheses".into()),
    }
}

/// One `#[axiom_opaque]` type.
#[derive(Clone, Debug)]
struct Opaque {
    name: String,
    stem: String,
    at: String,
}

/// One exported function (or one hand-written `axffi_*` shim).
#[derive(Clone, Debug)]
struct Decl {
    rust_name: String,
    axiom_name: String,
    symbol: String,
    /// `(wrapper parameter name, classification)`.
    params: Vec<(String, Param)>,
    ret: Ret,
    /// A hand-written `axffi_*` shim: bound as a plain item, never wrapped.
    raw: bool,
    /// Where it was declared, for messages.
    at: String,
}

/// One `#[axiom_record]` struct.
#[derive(Clone, Debug)]
struct Record {
    name: String,
    fields: Vec<RecordField>,
    at: String,
}

#[derive(Default)]
struct Surface {
    decls: Vec<Decl>,
    opaques: Vec<Opaque>,
    records: Vec<Record>,
}

impl Registry for Surface {
    fn lookup(&self, name: &str) -> Option<Named> {
        if let Some(r) = self.records.iter().find(|r| r.name == name) {
            return Some(Named::Record(r.fields.clone()));
        }
        self.opaques.iter().any(|o| o.name == name).then_some(Named::Opaque)
    }
}

/// The module path of a nested `mod` for messages (`inner::deeper`).
fn sub_path(path: &str, m: &syn::ItemMod) -> String {
    if path.is_empty() {
        m.ident.to_string()
    } else {
        format!("{path}::{}", m.ident)
    }
}

impl Surface {
    /// Walk a module's type items, recursing into inline `mod` bodies.
    /// `path` is the module path for messages.
    fn walk_types(&mut self, items: &[syn::Item], file: &str, path: &str) -> Result<()> {
        for item in items {
            match item {
                syn::Item::Struct(s) => {
                    self.visit_opaque(&s.attrs, &s.ident, file, path)?;
                    self.visit_record(s, file, path)?;
                }
                syn::Item::Enum(e) => self.visit_opaque(&e.attrs, &e.ident, file, path)?,
                syn::Item::Mod(m) => {
                    if let Some((_, inner)) = &m.content {
                        self.walk_types(inner, file, &sub_path(path, m))?;
                    }
                    // `mod x;` lives in its own file, which the directory
                    // walk already found.
                }
                _ => {}
            }
        }
        Ok(())
    }

    /// Walk a module's functions, after every type has been seen.
    fn walk_fns(&mut self, items: &[syn::Item], file: &str, path: &str) -> Result<()> {
        for item in items {
            match item {
                syn::Item::Fn(f) => self.visit_fn(f, file, path)?,
                syn::Item::Mod(m) => {
                    if let Some((_, inner)) = &m.content {
                        self.walk_fns(inner, file, &sub_path(path, m))?;
                    }
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn visit_opaque(
        &mut self,
        attrs: &[syn::Attribute],
        ident: &syn::Ident,
        file: &str,
        path: &str,
    ) -> Result<()> {
        let Some(a) = attr_named(attrs, "axiom_opaque") else { return Ok(()) };
        let at = where_(file, path, &ident.to_string());
        let metas = attr_metas(a).map_err(|m| Error(format!("{at}: `#[axiom_opaque]`: {m}")))?;
        let parsed = cls::parse_opaque_attr(metas.iter())
            .map_err(|e| Error(format!("{at}: {}", e.message)))?;
        let name = ident.to_string();
        let stem = cls::opaque_stem(&name, &parsed);
        self.opaques.push(Opaque { name, stem, at });
        Ok(())
    }

    fn visit_record(&mut self, s: &syn::ItemStruct, file: &str, path: &str) -> Result<()> {
        if attr_named(&s.attrs, "axiom_record").is_none() {
            return Ok(());
        }
        let name = s.ident.to_string();
        let at = where_(file, path, &name);
        let syn::Fields::Named(named) = &s.fields else {
            return Err(Error(format!("{at}: an `#[axiom_record]` needs named fields")));
        };
        let pairs: Vec<(String, &syn::Type)> = named
            .named
            .iter()
            .map(|f| (f.ident.as_ref().map(|i| i.to_string()).unwrap_or_default(), &f.ty))
            .collect();
        let fields = cls::classify_record_fields(pairs.iter().map(|(n, t)| (n.as_str(), *t)))
            .map_err(|m| Error(format!("{at}: {m}")))?;
        self.records.push(Record { name, fields, at });
        Ok(())
    }

    fn visit_fn(&mut self, f: &syn::ItemFn, file: &str, path: &str) -> Result<()> {
        let rust_name = f.sig.ident.to_string();
        let at = where_(file, path, &rust_name);
        let is_pub = matches!(f.vis, syn::Visibility::Public(_));
        if let Some(a) = attr_named(&f.attrs, "axiom_export") {
            // The macro refuses a non-`pub` export; a source tree that
            // compiles never has one, so this only mirrors that rule.
            if !is_pub {
                return Ok(());
            }
            let metas = attr_metas(a)
                .map_err(|m| Error(format!("{at}: `#[axiom_export]`: {m}")))?;
            let attr = cls::parse_export_attr(metas.iter())
                .map_err(|e| Error(format!("{at}: {}", e.message)))?;
            let mut params = Vec::new();
            for (i, arg) in f.sig.inputs.iter().enumerate() {
                let syn::FnArg::Typed(pt) = arg else {
                    return Err(Error(format!("{at}: `self` cannot cross the boundary")));
                };
                let pname = match &*pt.pat {
                    syn::Pat::Ident(id) => id.ident.to_string(),
                    _ => format!("__arg{}", i + 1),
                };
                if pname.starts_with("__") && !pname.starts_with("__arg") {
                    return Err(Error(format!(
                        "{at}: parameter `{pname}`: names starting with `__` are reserved \
                         for the generated wrapper's own locals"
                    )));
                }
                let p = cls::classify_param_with(&pt.ty, self)
                    .map_err(|m| Error(format!("{at}: {m}")))?;
                params.push((cls::camel_case(&pname), p));
            }
            let ret_ty = match &f.sig.output {
                syn::ReturnType::Default => None,
                syn::ReturnType::Type(_, t) => Some(&**t),
            };
            let ret = cls::classify_return_with(ret_ty, self)
                .map_err(|m| Error(format!("{at}: {m}")))?;
            // A record named by value, in a slice or in a `Vec` that no
            // `#[axiom_record]` under the source root declares.
            let classified: Vec<Param> = params.iter().map(|(_, p)| p.clone()).collect();
            if let Some(name) = cls::unresolved_records(&classified, &ret).first() {
                return Err(Error(format!(
                    "{at}: `{name}` crosses as a record but no `#[axiom_record]` declaration \
                     of `{name}` was found under the source root; mark the struct (it \
                     crosses as its fields), or take `&{name}` with `#[axiom_opaque]`"
                )));
            }
            self.decls.push(Decl {
                axiom_name: cls::camel_case(&rust_name),
                symbol: cls::export_symbol(&rust_name, &attr),
                rust_name,
                params,
                ret,
                raw: false,
                at,
            });
        } else if let Some(d) = raw_shim(f, &at) {
            // A HAND-WRITTEN `pub extern "C" fn axffi_*`. Bound as a plain
            // extern item over words: `AxWord` parameters are `Foreign`,
            // integers are `Int`, the return is `Int`.
            self.decls.push(d);
        }
        Ok(())
    }

    fn validate(&self) -> Result<()> {
        // Every opaque type at the boundary must be marked.
        let marked: BTreeSet<&str> = self.opaques.iter().map(|o| o.name.as_str()).collect();
        for d in self.decls.iter().filter(|d| !d.raw) {
            let mut used: Vec<&str> = Vec::new();
            for (_, p) in &d.params {
                if let Param::Opaque { ty, .. } = p {
                    used.push(&ty.name);
                }
            }
            match &d.ret {
                Ret::Opaque(o) => used.push(&o.name),
                other => {
                    if let Some(Payload::Opaque(o)) = other.status_payload() {
                        used.push(&o.name)
                    }
                }
            }
            for t in used {
                if !marked.contains(t) {
                    return Err(Error(format!(
                        "{}: `{t}` crosses the boundary as an opaque handle but no \
                         `#[axiom_opaque]` declaration of `{t}` was found under the source \
                         root; mark the type (it generates the destructor the handle needs)",
                        d.at
                    )));
                }
            }
        }
        // Opaque and record type names are unique, together: each is
        // one Axiom `data` in one flat namespace.
        let mut seen: BTreeMap<&str, (&str, &str)> = BTreeMap::new();
        let typed = self
            .opaques
            .iter()
            .map(|o| (o.name.as_str(), "#[axiom_opaque]", o.at.as_str()))
            .chain(self.records.iter().map(|r| (r.name.as_str(), "#[axiom_record]", r.at.as_str())));
        for (name, kind, at) in typed {
            if let Some((prev_kind, prev_at)) = seen.insert(name, (kind, at)) {
                return Err(Error(format!(
                    "two types are both named `{name}` (`{prev_kind}` at {prev_at} and \
                     `{kind}` at {at}); the Axiom `data` they bind to is one flat namespace"
                )));
            }
        }
        // Every value name the module defines is unique.
        let mut names: BTreeMap<String, String> = BTreeMap::new();
        let mut claim = |name: String, origin: String| -> Result<()> {
            if let Some(prev) = names.insert(name.clone(), origin.clone()) {
                return Err(Error(format!(
                    "Axiom name `{name}` is generated twice: for {prev} and for {origin}; \
                     rename one (camelCase folds `foo_bar` and `fooBar` together, and \
                     wrapped items also claim `<name>Raw`)"
                )));
            }
            Ok(())
        };
        for o in &self.opaques {
            let t = &o.name;
            claim(format!("{}DropFn", lower_first(t)), format!("the drop function of `{t}`"))?;
            claim(format!("{}Close", lower_first(t)), format!("the close wrapper of `{t}`"))?;
        }
        for d in &self.decls {
            let origin = format!("`{}` ({})", d.rust_name, d.at);
            claim(d.axiom_name.clone(), origin.clone())?;
            if d.needs_wrapper() {
                claim(format!("{}Raw", d.axiom_name), origin)?;
            }
        }
        Ok(())
    }

    fn render(&self, lib: &str) -> String {
        let mut decls: Vec<&Decl> = self.decls.iter().collect();
        decls.sort_by(|a, b| a.axiom_name.cmp(&b.axiom_name));
        let mut opaques: Vec<&Opaque> = self.opaques.iter().collect();
        opaques.sort_by(|a, b| a.name.cmp(&b.name));

        let needs_err = decls
            .iter()
            .any(|d| matches!(d.ret, Ret::Result(_) | Ret::ResultOption(_) | Ret::OptionResult(_)));
        // The record types that cross in a `Vec`, each way: the
        // module declares a rebuild loop and a flatten loop for them,
        // which is what needs `Vec`.
        let mut from_words: Vec<&RecordTy> = Vec::new();
        let mut to_words: Vec<&RecordTy> = Vec::new();
        for d in decls.iter().filter(|d| !d.raw) {
            for (_, p) in &d.params {
                if let Param::Records(r) = p {
                    if !to_words.iter().any(|x| x.name == r.name) {
                        to_words.push(r);
                    }
                }
            }
            let answered = match &d.ret {
                Ret::Records(r) => Some(r),
                other => match other.status_payload() {
                    Some(Payload::Records(r)) => Some(r),
                    _ => None,
                },
            };
            if let Some(r) = answered {
                if !from_words.iter().any(|x| x.name == r.name) {
                    from_words.push(r);
                }
            }
        }
        from_words.sort_by(|a, b| a.name.cmp(&b.name));
        to_words.sort_by(|a, b| a.name.cmp(&b.name));

        let mut out = String::new();
        out.push_str(&format!(
            "; GENERATED by axiom-bindgen from the `{lib}` crate. Do not edit.\n"
        ));
        let mut tops: Vec<String> = Vec::new();
        tops.push("(import Ffi)".into());
        if needs_err {
            tops.push("(import Err)".into());
        }
        if !from_words.is_empty() || !to_words.is_empty() {
            tops.push("(import Vec)".into());
        }

        // The extern block: one item per raw shim, plus the drop-function
        // probe of every opaque type.
        let mut items: Vec<(String, String)> = Vec::new();
        for d in &decls {
            items.push((d.raw_name(), format!("{} (symbol \"{}\")", d.raw_type(), d.symbol)));
        }
        for o in &opaques {
            items.push((
                format!("{}DropFn", lower_first(&o.name)),
                format!("Int (symbol \"{}\")", cls::drop_fn_symbol(&o.stem)),
            ));
        }
        items.sort();
        let mut block = format!("(pub extern \"{lib}\"");
        for (name, rest) in &items {
            block.push_str(&format!("\n  ({name} :: {rest})"));
        }
        block.push(')');
        // A `Vec` is `Int`-typed and holds one word per element; which
        // scalar those words are is only known here, so say it where
        // the items are declared (the formatter moves a comment out of
        // the block, so it goes before it).
        let notes: Vec<String> = decls.iter().flat_map(|d| d.vec_notes()).collect();
        if !notes.is_empty() {
            let mut note = String::from(
                "; A `Vec` is an `Int` handle holding one word per element, and the\n\
                 ; element type is whatever the program reads it as - Float bits with\n\
                 ; `(cast Float (vecGet v i))`, a Bool as 0/1, a Char as its code point,\n\
                 ; every integer as the word (a u64 >= 2^63 reads negative):",
            );
            for n in notes {
                note.push_str("\n;   ");
                note.push_str(&n);
            }
            note.push('\n');
            note.push_str(&block);
            block = note;
        }
        tops.push(block);

        // One `data` per record type: one constructor, one positional
        // field per Rust field, in order.
        let mut records: Vec<&Record> = self.records.iter().collect();
        records.sort_by(|a, b| a.name.cmp(&b.name));
        for r in &records {
            let t = &r.name;
            let fields: Vec<String> = r
                .fields
                .iter()
                .map(|f| format!("{} {}", f.name, f.scalar.axiom_type()))
                .collect();
            let types: Vec<&str> = r.fields.iter().map(|f| f.scalar.axiom_type()).collect();
            tops.push(format!(
                "; `{t}` crosses the boundary as its fields, one word each: {}.\n\
                 (pub data {t}\n  ({t} {}))",
                fields.join(", "),
                types.join(" ")
            ));
        }

        // The record loops: a `Vec<Record>` result is `n * ARITY` Rust
        // words rebuilt into a `Vec` of records, a `&[Record]`
        // parameter a `Vec` of records flattened into the words the
        // shim chunks. Module-private: the record's shape is this
        // crate's, and two generated modules never see each other's.
        for r in &from_words {
            let (sig, body) = record_from_words_loop(r);
            tops.push(format!(
                "; A `Vec` of `{}` answered by Rust: {} words per element, rebuilt here.\n{sig}",
                r.name,
                r.arity()
            ));
            tops.push(body);
        }
        for r in &to_words {
            let (sig, body) = record_to_words_loop(r);
            tops.push(format!(
                "; A `Vec` of `{}` handed to Rust: flattened to {} words per element here.\n{sig}",
                r.name,
                r.arity()
            ));
            tops.push(body);
        }

        // One `data` per opaque type, with its close wrapper.
        for o in &opaques {
            let t = &o.name;
            tops.push(format!(
                "; `{t}` is a Rust value held through a `Handle`: when the last\n\
                 ; reference dies the handle runs `{}`.\n\
                 (pub data {t}\n  ({t} Handle))",
                cls::drop_symbol(&o.stem)
            ));
            let close = format!("{}Close", lower_first(t));
            tops.push(format!("(pub :: {close} (-> {t} Int))"));
            let body = Ex::Match(
                Box::new(atom("c")),
                vec![(app(vec![atom(t), atom("__h")]), app(vec![atom("ffiHandleClose"), atom("__h")]))],
            );
            tops.push(sexp::decl_fn(&close, &["c".to_string()], &body));
        }

        // The wrappers.
        for d in &decls {
            if !d.needs_wrapper() {
                continue;
            }
            tops.push(format!("(pub :: {} {})", d.axiom_name, d.wrapper_type()));
            let params: Vec<String> = d.params.iter().map(|(n, _)| n.clone()).collect();
            tops.push(sexp::decl_fn(&d.axiom_name, &params, &d.wrapper_body()));
        }

        out.push_str(&tops.join("\n\n"));
        out.push('\n');
        out
    }
}

fn where_(file: &str, path: &str, name: &str) -> String {
    if path.is_empty() {
        format!("{file}: `{name}`")
    } else {
        format!("{file}: `{path}::{name}`")
    }
}

fn lower_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

/// A hand-written `#[no_mangle] pub extern "C" fn axffi_*`, bound raw.
fn raw_shim(f: &syn::ItemFn, at: &str) -> Option<Decl> {
    let name = f.sig.ident.to_string();
    if !name.starts_with("axffi_") {
        return None;
    }
    if !matches!(f.vis, syn::Visibility::Public(_)) {
        return None;
    }
    f.sig.abi.as_ref()?;
    let mut params = Vec::new();
    for (i, a) in f.sig.inputs.iter().enumerate() {
        let syn::FnArg::Typed(pt) = a else { return None };
        let n = match &*pt.pat {
            syn::Pat::Ident(id) => id.ident.to_string(),
            _ => format!("__arg{}", i + 1),
        };
        // `AxWord` is the crate's word for "an opaque word": `Foreign`.
        // A plain integer is a number: `Int`. The word is modelled as an
        // opaque borrow, which renders as `Foreign`; a raw shim never
        // gets a wrapper, so the pseudo-type is never looked up.
        let is_word = matches!(&*pt.ty, syn::Type::Path(p)
            if p.path.segments.last().map(|s| s.ident == "AxWord").unwrap_or(false));
        let p = if is_word {
            Param::Opaque {
                ty: cls::OpaqueTy { ty: (*pt.ty).clone(), name: "AxWord".into() },
                mutable: false,
            }
        } else {
            Param::Scalar(Scalar::I64)
        };
        params.push((cls::camel_case(&n), p));
    }
    Some(Decl {
        axiom_name: cls::camel_case(name.trim_start_matches("axffi_")),
        symbol: name.clone(),
        rust_name: name,
        params,
        ret: Ret::Scalar(Scalar::I64),
        raw: true,
        at: at.to_string(),
    })
}

fn payload_axiom_type(p: &Payload) -> String {
    match p {
        Payload::Scalar(s) => s.axiom_type().to_string(),
        Payload::Bytes => "String".into(),
        // A `Vec` is an `Int` handle in the stdlib, whatever it holds.
        Payload::Words(_) | Payload::WordLists(_) | Payload::Strs | Payload::Records(_) => {
            "Int".into()
        }
        Payload::Opaque(o) => o.name.clone(),
        Payload::Record(r) => r.name.clone(),
    }
}

/// The Axiom types of a parameter as the RAW extern item declares
/// them: one for every shape but a record, which is one per field.
fn param_raw_types(p: &Param) -> Vec<String> {
    match p {
        Param::Record(r) => r.fields.iter().map(|f| f.scalar.axiom_type().to_string()).collect(),
        other => vec![param_raw_type(other)],
    }
}

/// The Axiom type of a one-word parameter as the RAW extern item
/// declares it.
fn param_raw_type(p: &Param) -> String {
    match p {
        Param::Scalar(s) => s.axiom_type().to_string(),
        Param::Str | Param::Bytes => "String".into(),
        Param::Opaque { .. } => "Foreign".into(),
        Param::Words(_)
        | Param::MutWords(_)
        | Param::WordLists(_)
        | Param::Strs
        | Param::Records(_) => "Int".into(),
        Param::Callback(n) => callback_type(*n),
        Param::Record(r) => r.name.clone(),
    }
}

/// How a field word reads back as its Axiom type: a Float, Bool or
/// Char is the word reinterpreted, an Int is the word.
fn field_from_word(scalar: Scalar, word: Ex) -> Ex {
    match scalar.axiom_type() {
        "Int" => word,
        other => Ex::Cast(other.to_string(), Box::new(word)),
    }
}

/// The bindings that rebuild a record from the cell - `__w0`, `__w1`,
/// .. one per field, then `__r` - and the record expression.
fn record_from_cell(r: &RecordTy, binds: &mut Vec<(String, Ex)>) {
    let mut ctor = vec![atom(&r.name)];
    for (j, f) in r.fields.iter().enumerate() {
        let w = format!("__w{j}");
        let word = app(vec![atom("ffiCellWord"), atom("__c"), atom(&j.to_string())]);
        binds.push((w.clone(), field_from_word(f.scalar, word)));
        ctor.push(atom(&w));
    }
    binds.push(("__r".into(), app(ctor)));
}

/// `__pointFromWords`: the module-private loop that rebuilds a `Vec`
/// of `Point`s from the `n * ARITY` words a shim answered.
fn from_words_name(record: &str) -> String {
    format!("__{}FromWords", lower_first(record))
}

/// `__pointToWords`: the module-private loop that flattens a `Vec` of
/// `Point`s into `ARITY` words per element for a shim.
fn to_words_name(record: &str) -> String {
    format!("__{}ToWords", lower_first(record))
}

/// The signature and body of the rebuild loop:
///
/// ```text
/// (:: __pointFromWords (-> Int Int Int Int Int))
/// (fn (__pointFromWords __v __p __n __i)
///   (if (>= __i __n) __v
///     (let ((__w0 (ffiWordAt __p (* __i 2))) (__w1 (cast Float ..)))
///       { (vecPush __v (Point __w0 __w1)) (__pointFromWords __v __p __n (+ __i 1)) })))
/// ```
fn record_from_words_loop(r: &RecordTy) -> (String, String) {
    let name = from_words_name(&r.name);
    let arity = r.arity();
    let mut binds: Vec<(String, Ex)> = Vec::new();
    let mut ctor = vec![atom(&r.name)];
    for (j, f) in r.fields.iter().enumerate() {
        let base = if arity == 1 {
            atom("__i")
        } else {
            app(vec![atom("*"), atom("__i"), atom(&arity.to_string())])
        };
        let index = if j == 0 { base } else { app(vec![atom("+"), base, atom(&j.to_string())]) };
        let w = format!("__w{j}");
        binds.push((w.clone(), field_from_word(f.scalar, app(vec![atom("ffiWordAt"), atom("__p"), index]))));
        ctor.push(atom(&w));
    }
    let step = Ex::Block(vec![
        app(vec![atom("vecPush"), atom("__v"), app(ctor)]),
        app(vec![atom(&name), atom("__v"), atom("__p"), atom("__n"), app(vec![atom("+"), atom("__i"), atom("1")])]),
    ]);
    let body = Ex::If(
        Box::new(app(vec![atom(">="), atom("__i"), atom("__n")])),
        Box::new(atom("__v")),
        Box::new(Ex::Let(binds, Box::new(step))),
    );
    let params = ["__v", "__p", "__n", "__i"].map(String::from);
    (
        format!("(:: {name} (-> Int Int Int Int Int))"),
        sexp::decl_private_fn(&name, &params, &body),
    )
}

/// The signature and body of the flatten loop:
///
/// ```text
/// (:: __pointToWords (-> Int Int Int Int))
/// (fn (__pointToWords __ps __w __i)
///   (if (>= __i (vecLen __ps)) __w
///     (match (vecGet __ps __i)
///       ((Point __f0 __f1)
///         { (vecPush __w __f0) (vecPush __w __f1) (__pointToWords __ps __w (+ __i 1)) }))))
/// ```
///
/// Each field is pushed as the word it already is (`vecPush` is
/// polymorphic in its element, and a Float, Bool or Char IS its word),
/// which is what the shim's `from_words` reads back.
fn record_to_words_loop(r: &RecordTy) -> (String, String) {
    let name = to_words_name(&r.name);
    let mut pat = vec![atom(&r.name)];
    let mut stmts: Vec<Ex> = Vec::new();
    for j in 0..r.arity() {
        let f = format!("__f{j}");
        stmts.push(app(vec![atom("vecPush"), atom("__w"), atom(&f)]));
        pat.push(atom(&f));
    }
    stmts.push(app(vec![atom(&name), atom("__ps"), atom("__w"), app(vec![atom("+"), atom("__i"), atom("1")])]));
    let body = Ex::If(
        Box::new(app(vec![atom(">="), atom("__i"), app(vec![atom("vecLen"), atom("__ps")])])),
        Box::new(atom("__w")),
        Box::new(Ex::Match(
            Box::new(app(vec![atom("vecGet"), atom("__ps"), atom("__i")])),
            vec![(app(pat), Ex::Block(stmts))],
        )),
    );
    let params = ["__ps", "__w", "__i"].map(String::from);
    (
        format!("(:: {name} (-> Int Int Int Int))"),
        sexp::decl_private_fn(&name, &params, &body),
    )
}

/// `(-> Int Int)` for one argument, and so on: the arrow type a
/// callback parameter carries on both the raw item and the wrapper.
fn callback_type(arity: u8) -> String {
    let mut t = String::from("(->");
    for _ in 0..=arity {
        t.push_str(" Int");
    }
    t.push(')');
    t
}

/// Whether a payload rides the cell as a `(ptr, n)` pair the wrapper
/// copies out of and then frees.
fn is_collection(p: &Payload) -> bool {
    matches!(
        p,
        Payload::Bytes | Payload::Words(_) | Payload::WordLists(_) | Payload::Strs | Payload::Records(_)
    )
}

/// The expression that builds the Axiom value of a cell-carried
/// collection from `__p` and `__n`: an Ffi.ax helper, or for a `Vec`
/// of records the module's own rebuild loop over a fresh `Vec`.
fn collection_build(p: &Payload) -> Ex {
    let helper = match p {
        Payload::Bytes => "ffiBytesToStr",
        Payload::Words(_) => "ffiWordsToVec",
        Payload::WordLists(_) => "ffiWordListsToVec",
        Payload::Strs => "ffiStrsToVec",
        Payload::Records(r) => {
            return app(vec![
                atom(&from_words_name(&r.name)),
                app(vec![atom("vecWithCapacity"), atom("__n")]),
                atom("__p"),
                atom("__n"),
                atom("0"),
            ])
        }
        _ => unreachable!("only collections ride the cell as (ptr, n)"),
    };
    app(vec![atom(helper), atom("__p"), atom("__n")])
}

/// The expression that frees the Rust side of a cell-carried
/// collection: a `Vec` of records is `n * ARITY` words.
fn collection_free(p: &Payload) -> Ex {
    let helper = match p {
        Payload::Bytes => "ffiFreeBytes",
        Payload::Words(_) => "ffiFreeWords",
        Payload::WordLists(_) => "ffiFreeWordLists",
        Payload::Strs => "ffiFreeStrList",
        Payload::Records(r) => {
            return app(vec![
                atom("ffiFreeWords"),
                atom("__p"),
                app(vec![atom("*"), atom("__n"), atom(&r.arity().to_string())]),
            ])
        }
        _ => unreachable!("only collections ride the cell as (ptr, n)"),
    };
    app(vec![atom(helper), atom("__p"), atom("__n")])
}

/// The payload a direct cell-carried return carries.
fn direct_payload(r: &Ret) -> Payload {
    match r {
        Ret::Bytes => Payload::Bytes,
        Ret::Words(s) => Payload::Words(*s),
        Ret::WordLists(s) => Payload::WordLists(*s),
        Ret::Strs => Payload::Strs,
        Ret::Record(r) => Payload::Record(r.clone()),
        Ret::Records(r) => Payload::Records(r.clone()),
        _ => unreachable!("not a direct cell-carried return"),
    }
}

/// The cell a wrapper allocates: `ffiCellNew` for the two-word
/// protocols, `(ffiCellNewN n)` for a record of `n` words.
fn cell_new(ret: &Ret) -> Ex {
    let record = matches!(ret, Ret::Record(_))
        || matches!(ret.status_payload(), Some(Payload::Record(_)));
    if record {
        app(vec![atom("ffiCellNewN"), atom(&ret.cell_words().to_string())])
    } else {
        atom("ffiCellNew")
    }
}

/// How a `Vec` of `scalar` elements reads, for the element-type note.
fn element_note(scalar: Scalar) -> String {
    match scalar {
        Scalar::I64 => "Int".into(),
        Scalar::U64 => "u64 (the word's bits, unsigned)".into(),
        Scalar::F64 | Scalar::F32 => format!("Float bits ({})", scalar.rust_name()),
        Scalar::Bool => "Bool (0/1)".into(),
        Scalar::Char => "Char (code points)".into(),
        other => format!("{} (each word range-checked)", other.rust_name()),
    }
}

/// The constructor applications of a status return: `ok` wraps the
/// payload, `none` and `err` (over `__m`) are the other two states;
/// a plain `Result` has no `none`, a plain `Option` no `err`.
struct StatusCtors {
    ok: fn(Ex) -> Ex,
    none: Option<Ex>,
    err: Option<Ex>,
}

fn status_ctors(ret: &Ret) -> StatusCtors {
    fn ok(v: Ex) -> Ex {
        app(vec![atom("Ok"), v])
    }
    fn some(v: Ex) -> Ex {
        app(vec![atom("Some"), v])
    }
    fn ok_some(v: Ex) -> Ex {
        ok(some(v))
    }
    fn some_ok(v: Ex) -> Ex {
        some(ok(v))
    }
    let err = app(vec![atom("Err"), atom("__m")]);
    match ret {
        Ret::Result(_) => StatusCtors { ok, none: None, err: Some(err) },
        Ret::Option(_) => StatusCtors { ok: some, none: Some(atom("None")), err: None },
        Ret::ResultOption(_) => StatusCtors { ok: ok_some, none: Some(ok(atom("None"))), err: Some(err) },
        Ret::OptionResult(_) => StatusCtors { ok: some_ok, none: Some(atom("None")), err: Some(some(err)) },
        _ => unreachable!("not a status return"),
    }
}

impl Decl {
    /// Whether the symbol is bound under `<name>Raw` with an Axiom
    /// wrapper over it.
    fn needs_wrapper(&self) -> bool {
        if self.raw {
            return false;
        }
        self.ret.needs_cell()
            || matches!(self.ret, Ret::Opaque(_))
            || self
                .params
                .iter()
                .any(|(_, p)| matches!(p, Param::Opaque { .. } | Param::Record(_) | Param::Records(_)))
    }

    fn raw_name(&self) -> String {
        if self.needs_wrapper() {
            format!("{}Raw", self.axiom_name)
        } else {
            self.axiom_name.clone()
        }
    }

    /// The raw extern's type: the shim's real arity over wire types.
    fn raw_type(&self) -> String {
        let mut ps: Vec<String> = self.params.iter().flat_map(|(_, p)| param_raw_types(p)).collect();
        let ret = if self.ret.needs_cell() {
            ps.push("Int".into());
            "Int".to_string()
        } else {
            match &self.ret {
                Ret::Scalar(s) => s.axiom_type().to_string(),
                Ret::Opaque(_) => "Foreign".into(),
                _ => unreachable!(),
            }
        };
        arrow(&ps, &ret)
    }

    /// The wrapper's Axiom-facing type.
    fn wrapper_type(&self) -> String {
        let ps: Vec<String> = self
            .params
            .iter()
            .map(|(_, p)| match p {
                Param::Opaque { ty, .. } => ty.name.clone(),
                other => param_raw_type(other),
            })
            .collect();
        let ret = match &self.ret {
            Ret::Scalar(s) => s.axiom_type().to_string(),
            Ret::Opaque(o) => o.name.clone(),
            Ret::Bytes | Ret::Words(_) | Ret::WordLists(_) | Ret::Strs | Ret::Record(_)
            | Ret::Records(_) => payload_axiom_type(&direct_payload(&self.ret)),
            Ret::Result(p) => format!("(Result {} String)", payload_axiom_type(p)),
            Ret::Option(p) => format!("(Option {})", payload_axiom_type(p)),
            Ret::ResultOption(p) => format!("(Result (Option {}) String)", payload_axiom_type(p)),
            Ret::OptionResult(p) => format!("(Option (Result {} String))", payload_axiom_type(p)),
        };
        arrow(&ps, &ret)
    }

    /// One line per `Vec` parameter or result whose element is not a
    /// plain `Int`, saying how its words read.
    fn vec_notes(&self) -> Vec<String> {
        let mut out = Vec::new();
        let name = &self.axiom_name;
        for (pname, p) in &self.params {
            match p {
                Param::Words(s) if *s != Scalar::I64 => {
                    out.push(format!("`{name}` reads `{pname}` as a Vec of {};", element_note(*s)))
                }
                Param::MutWords(s) => out.push(format!(
                    "`{name}` writes `{pname}` in place, a Vec of {};",
                    element_note(*s)
                )),
                Param::WordLists(s) => out.push(format!(
                    "`{name}` reads `{pname}` as a Vec of Vecs of {};",
                    element_note(*s)
                )),
                Param::Strs => out.push(format!("`{name}` reads `{pname}` as a Vec of String;")),
                Param::Records(r) => out.push(format!(
                    "`{name}` reads `{pname}` as a Vec of {} (flattened to {} words per \
                     element for the call);",
                    r.name,
                    r.arity()
                )),
                _ => {}
            }
        }
        let answered = match &self.ret {
            Ret::Words(s) => Some(Payload::Words(*s)),
            Ret::WordLists(s) => Some(Payload::WordLists(*s)),
            Ret::Records(r) => Some(Payload::Records(r.clone())),
            other => other.status_payload().cloned(),
        };
        match answered {
            Some(Payload::Words(s)) if s != Scalar::I64 => {
                out.push(format!("`{name}` answers a Vec of {};", element_note(s)))
            }
            Some(Payload::WordLists(s)) => {
                out.push(format!("`{name}` answers a Vec of Vecs of {};", element_note(s)))
            }
            Some(Payload::Records(r)) => out.push(format!("`{name}` answers a Vec of {};", r.name)),
            _ => {}
        }
        out
    }

    /// The wrapper body. Opaque and record parameters are unwrapped by
    /// nested `match`es, then one `let` binds the raw pointers, the
    /// call and the decoded result, in order.
    fn wrapper_body(&self) -> Ex {
        // The raw call's arguments and the pointer bindings they need.
        let mut binds: Vec<(String, Ex)> = Vec::new();
        let mut args: Vec<Ex> = Vec::new();
        // (param, pattern): `(Counter __h0)` for a handle, `(Point __f0 __f1)`
        // for a record; record field locals are numbered across the
        // whole signature.
        let mut matches: Vec<(String, Ex)> = Vec::new();
        let mut field_no = 0usize;
        for (i, (name, p)) in self.params.iter().enumerate() {
            match p {
                Param::Opaque { ty, .. } => {
                    let h = format!("__h{i}");
                    let a = format!("__a{i}");
                    binds.push((
                        a.clone(),
                        Ex::Cast("Foreign".into(), Box::new(app(vec![atom("ffiHandlePtr"), atom(&h)]))),
                    ));
                    args.push(atom(&a));
                    matches.push((name.clone(), app(vec![atom(&ty.name), atom(&h)])));
                }
                Param::Record(r) => {
                    let mut pat = vec![atom(&r.name)];
                    for _ in &r.fields {
                        let f = format!("__f{field_no}");
                        field_no += 1;
                        args.push(atom(&f));
                        pat.push(atom(&f));
                    }
                    matches.push((name.clone(), app(pat)));
                }
                Param::Records(r) => {
                    // Flattened into a fresh words Vec of ARITY words
                    // per element, which the shim chunks back.
                    let a = format!("__a{i}");
                    let cap = app(vec![
                        atom("*"),
                        app(vec![atom("vecLen"), atom(name)]),
                        atom(&r.arity().to_string()),
                    ]);
                    binds.push((
                        a.clone(),
                        app(vec![
                            atom(&to_words_name(&r.name)),
                            atom(name),
                            app(vec![atom("vecWithCapacity"), cap]),
                            atom("0"),
                        ]),
                    ));
                    args.push(atom(&a));
                }
                _ => args.push(atom(name)),
            }
        }
        let raw = self.raw_name();
        let mut call = vec![atom(&raw)];
        call.extend(args);
        let cell_free = app(vec![atom("ffiCellFree"), atom("__c")]);

        let body = match &self.ret {
            Ret::Scalar(_) => {
                binds.push(("__r".into(), app(call)));
                Ex::Let(binds, Box::new(atom("__r")))
            }
            Ret::Opaque(o) => {
                binds.push(("__p".into(), Ex::Cast("Int".into(), Box::new(app(call)))));
                binds.push((
                    "__h".into(),
                    app(vec![atom("ffiHandleNew"), atom("__p"), atom(&drop_fn_name(&o.name))]),
                ));
                Ex::Let(binds, Box::new(app(vec![atom(&o.name), atom("__h")])))
            }
            Ret::Record(r) => {
                call.push(atom("__c"));
                binds.push(("__c".into(), cell_new(&self.ret)));
                binds.push(("__st".into(), app(call)));
                record_from_cell(r, &mut binds);
                Ex::Let(binds, Box::new(Ex::Block(vec![cell_free, atom("__r")])))
            }
            Ret::Bytes | Ret::Words(_) | Ret::WordLists(_) | Ret::Strs | Ret::Records(_) => {
                let payload = direct_payload(&self.ret);
                call.push(atom("__c"));
                binds.push(("__c".into(), atom("ffiCellNew")));
                binds.push(("__st".into(), app(call)));
                binds.push(("__p".into(), app(vec![atom("ffiCellWord"), atom("__c"), atom("0")])));
                binds.push(("__n".into(), app(vec![atom("ffiCellWord"), atom("__c"), atom("1")])));
                binds.push(("__v".into(), collection_build(&payload)));
                Ex::Let(
                    binds,
                    Box::new(Ex::Block(vec![collection_free(&payload), cell_free, atom("__v")])),
                )
            }
            Ret::Result(p) | Ret::Option(p) | Ret::ResultOption(p) | Ret::OptionResult(p) => {
                let ctors = status_ctors(&self.ret);
                call.push(atom("__c"));
                binds.push(("__c".into(), cell_new(&self.ret)));
                binds.push(("__st".into(), app(call)));
                binds.push(("__p".into(), app(vec![atom("ffiCellWord"), atom("__c"), atom("0")])));
                binds.push(("__n".into(), app(vec![atom("ffiCellWord"), atom("__c"), atom("1")])));
                // A Float or Char payload is the word reinterpreted.
                // The cast is bound up front (harmless on the other
                // paths, where the word is a pointer or zero nothing
                // reads as that type) so the constructor application
                // stays on one line. A record is rebuilt up front the
                // same way: on the other paths the cell holds a
                // message or zeros, read by nothing.
                if matches!(p, Payload::Scalar(s) if s.is_float()) {
                    binds.push(("__f".into(), Ex::Cast("Float".into(), Box::new(atom("__p")))));
                }
                if matches!(p, Payload::Scalar(Scalar::Char)) {
                    binds.push(("__ch".into(), Ex::Cast("Char".into(), Box::new(atom("__p")))));
                }
                if let Payload::Record(r) = p {
                    record_from_cell(r, &mut binds);
                }
                let ok = if is_collection(p) {
                    Ex::Let(
                        vec![("__v".into(), collection_build(p))],
                        Box::new(Ex::Block(vec![
                            collection_free(p),
                            cell_free.clone(),
                            (ctors.ok)(atom("__v")),
                        ])),
                    )
                } else {
                    let value = match p {
                        Payload::Scalar(s) if s.is_float() => atom("__f"),
                        Payload::Scalar(Scalar::Char) => atom("__ch"),
                        Payload::Scalar(Scalar::Bool) => app(vec![atom("!="), atom("__p"), atom("0")]),
                        Payload::Scalar(_) => atom("__p"),
                        Payload::Opaque(o) => app(vec![
                            atom(&o.name),
                            app(vec![atom("ffiHandleNew"), atom("__p"), atom(&drop_fn_name(&o.name))]),
                        ]),
                        Payload::Record(_) => atom("__r"),
                        _ => unreachable!("collections are built above"),
                    };
                    Ex::Block(vec![cell_free.clone(), (ctors.ok)(value)])
                };
                // Status 1: the message's bytes, copied then freed.
                let err = ctors.err.map(|e| {
                    Ex::Let(
                        vec![("__m".into(), app(vec![atom("ffiBytesToStr"), atom("__p"), atom("__n")]))],
                        Box::new(Ex::Block(vec![
                            app(vec![atom("ffiFreeBytes"), atom("__p"), atom("__n")]),
                            cell_free.clone(),
                            e,
                        ])),
                    )
                });
                // Status 2: nothing in the cell.
                let none = ctors.none.map(|n| Ex::Block(vec![cell_free.clone(), n]));
                let not_ok = match (none, err) {
                    (Some(n), Some(e)) => Ex::If(
                        Box::new(app(vec![atom("=="), atom("__st"), atom("2")])),
                        Box::new(n),
                        Box::new(e),
                    ),
                    (Some(n), None) => n,
                    (None, Some(e)) => e,
                    (None, None) => unreachable!("a status return has a second state"),
                };
                Ex::Let(
                    binds,
                    Box::new(Ex::If(
                        Box::new(app(vec![atom("=="), atom("__st"), atom("0")])),
                        Box::new(ok),
                        Box::new(not_ok),
                    )),
                )
            }
        };

        // Unwrap the handles and records, innermost last:
        // `(match c ((Counter __h0) body))`, `(match p ((Point __f0 __f1) body))`.
        let mut wrapped = body;
        for (param, pat) in matches.into_iter().rev() {
            wrapped = Ex::Match(Box::new(atom(&param)), vec![(pat, wrapped)]);
        }
        wrapped
    }
}

fn drop_fn_name(type_name: &str) -> String {
    format!("{}DropFn", lower_first(type_name))
}

fn arrow(ps: &[String], ret: &str) -> String {
    if ps.is_empty() {
        ret.to_string()
    } else {
        format!("(-> {} {})", ps.join(" "), ret)
    }
}
