//! Emit the Axiom `extern` module for a crate's `#[axiom_export]` surface.
//!
//! This reads the Rust SOURCE rather than the compiled artifact, the way
//! `cbindgen` does. The alternative — a runtime registry built with
//! life-before-main constructors — does not survive `no_std`, and
//! `no_std` is the mode that keeps Axiom freestanding, so it would have
//! ruled out the more valuable of the two build modes.
//!
//! Because this is a second, independent pass over the same annotations
//! the proc macro reads, the two can drift. `scripts/check-ffi.sh`
//! closes that: it regenerates the bindings and fails if the checked-in
//! `.ax` differs, which is the same shape as `check-fmt.sh --check`.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut src_root: Option<PathBuf> = None;
    let mut lib = String::from("rustlib");
    let mut module = String::from("Rust");
    let mut out: Option<PathBuf> = None;
    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--src" => { src_root = args.get(i + 1).map(PathBuf::from); i += 2 }
            "--lib" => { lib = args[i + 1].clone(); i += 2 }
            "--module" => { module = args[i + 1].clone(); i += 2 }
            "-o" | "--output" => { out = args.get(i + 1).map(PathBuf::from); i += 2 }
            other => { eprintln!("axiom-bindgen: unknown flag {other}"); std::process::exit(2) }
        }
    }
    let Some(src_root) = src_root else {
        eprintln!("usage: axiom-bindgen --src <dir> [--lib NAME] [--module NAME] -o <file.ax>");
        std::process::exit(2);
    };

    let mut files = Vec::new();
    collect_rs(&src_root, &mut files);
    files.sort();

    let mut decls: BTreeMap<String, Decl> = BTreeMap::new();
    for f in &files {
        let text = match fs::read_to_string(f) {
            Ok(t) => t,
            Err(e) => { eprintln!("axiom-bindgen: {}: {e}", f.display()); std::process::exit(1) }
        };
        let ast = match syn::parse_file(&text) {
            Ok(a) => a,
            Err(e) => { eprintln!("axiom-bindgen: {}: {e}", f.display()); std::process::exit(1) }
        };
        for item in ast.items {
            if let syn::Item::Fn(f) = item {
                if !has_export_attr(&f.attrs) { continue }
                match Decl::from_fn(&f) {
                    Ok(d) => { decls.insert(d.axiom_name.clone(), d); }
                    Err(m) => {
                        eprintln!("axiom-bindgen: `{}`: {m}", f.sig.ident);
                        std::process::exit(1);
                    }
                }
            }
        }
    }

    let mut s = String::new();
    s.push_str(&format!(
        "; GENERATED by axiom-bindgen from the `{lib}` crate. Do not edit.\n\
         ;\n\
         ; One `extern` BLOCK is one unit of enumeration: MM-FFI-5's fourth\n\
         ; requirement is a gate that enumerates permitted external symbols,\n\
         ; and this block is what `scripts/check-ffi.sh` enumerates.\n\
         ;\n\
         ; Every `(symbol ...)` clause is written explicitly, never defaulted.\n\
         ; A static link is one flat namespace, and two crates that each bind\n\
         ; a `parse` and omit the clause would dedup to one `declare`, resolve\n\
         ; both Axiom names to it, and pick a link-time winner with no\n\
         ; diagnostic at any stage.\n"
    ));
    s.push_str(&format!("(pub extern \"{lib}\"\n"));
    for d in decls.values() {
        s.push_str(&d.render_item());
    }
    // The formatter closes the block on the last item's line.
    if s.ends_with(")\n") {
        s.truncate(s.len() - 1);
        s.push_str(")\n");
    }

    match out {
        Some(p) => {
            if let Some(parent) = p.parent() { let _ = fs::create_dir_all(parent); }
            fs::write(&p, s).unwrap_or_else(|e| {
                eprintln!("axiom-bindgen: {}: {e}", p.display());
                std::process::exit(1)
            });
            eprintln!("axiom-bindgen: wrote {} declaration(s) for module {module} to {}",
                      decls.len(), p.display());
        }
        None => print!("{s}"),
    }
}

fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() { collect_rs(&p, out) }
        else if p.extension().map(|x| x == "rs").unwrap_or(false) { out.push(p) }
    }
}

fn has_export_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|a| {
        a.path().segments.last().map(|s| s.ident == "axiom_export").unwrap_or(false)
    })
}

struct Decl {
    axiom_name: String,
    symbol: String,
    params: Vec<(String, String)>,
    ret: String,
    fallible: bool,
}

impl Decl {
    fn from_fn(f: &syn::ItemFn) -> Result<Decl, String> {
        let rust_name = f.sig.ident.to_string();
        let mut params = Vec::new();
        for a in &f.sig.inputs {
            let syn::FnArg::Typed(pt) = a else {
                return Err("`self` cannot cross the boundary".into())
            };
            let name = match &*pt.pat {
                syn::Pat::Ident(i) => i.ident.to_string(),
                _ => "arg".to_string(),
            };
            params.push((camel(&name), axiom_ty(&pt.ty)?));
        }
        let (ret_ty, fallible) = match &f.sig.output {
            syn::ReturnType::Default => ("Unit".to_string(), false),
            syn::ReturnType::Type(_, t) => {
                if let Some(ok) = result_ok(t) { (axiom_ty(ok)?, true) }
                else { (axiom_ty(t)?, false) }
            }
        };
        Ok(Decl {
            axiom_name: camel(&rust_name),
            symbol: format!("axffi_{rust_name}"),
            params,
            ret: ret_ty,
            fallible,
        })
    }

    /// One `symbol-item` line inside the block.
    ///
    /// The BLOCK form is not cosmetic. A separate `(:: name Type)` beside
    /// the binding would draw a false AX3015 on every single extern:
    /// `defIdxBuild` (self_host/typecheck.ax:1114-1132) indexes only
    /// TAG_D_FN nodes with `nodeVis == 1`, so `checkMissingDefs`
    /// (:1242-1262) sees a signature with nothing behind it. Carrying the
    /// type inline makes that failure structurally impossible.
    fn render_item(&self) -> String {
        let arrow = if self.params.is_empty() {
            self.ret_type()
        } else {
            let ps: Vec<String> = self.params.iter().map(|(_, t)| t.clone()).collect();
            format!("(-> {} {})", ps.join(" "), self.ret_type())
        };
        // Single spaces, not aligned columns: this is exactly the
        // formatter's normal form (`fpDeclExtern`, self_host/format.ax),
        // so `axiom fmt` leaves a generated file alone and
        // `check-ffi.sh`'s regenerate-and-diff does not fight
        // `check-fmt.sh`'s sweep.
        format!(
            "  ({} :: {} (symbol \"{}\"))\n",
            self.axiom_name, arrow, self.symbol
        )
    }

    /// A fallible item returns the compiler-owned `Outcome`; a bytes
    /// return is a `Slice`. Both are one word, per contract C2.
    fn ret_type(&self) -> String {
        if self.fallible {
            "Outcome".to_string()
        } else if self.ret == "String" {
            "Slice".to_string()
        } else {
            self.ret.clone()
        }
    }
}

fn result_ok(t: &syn::Type) -> Option<&syn::Type> {
    let syn::Type::Path(p) = t else { return None };
    let seg = p.path.segments.last()?;
    if seg.ident != "Result" { return None }
    let syn::PathArguments::AngleBracketed(a) = &seg.arguments else { return None };
    match a.args.first()? {
        syn::GenericArgument::Type(t) => Some(t),
        _ => None,
    }
}

/// The Rust -> Axiom type name mapping. Anything not named here is an
/// opaque handle, which is what makes arbitrary crate types bindable.
fn axiom_ty(t: &syn::Type) -> Result<String, String> {
    match t {
        syn::Type::Reference(r) => match &*r.elem {
            syn::Type::Path(p) if p.path.is_ident("str") => Ok("String".into()),
            syn::Type::Slice(s) => match &*s.elem {
                syn::Type::Path(p) if p.path.is_ident("u8") => Ok("String".into()),
                _ => Err("only `&[u8]` slices cross".into()),
            },
            // A reference to any other named type is an opaque handle,
            // matching `classify` in axiom-ffi-macros. The two passes
            // must agree or check-ffi.sh's regenerate-and-diff fails.
            syn::Type::Path(_) => Ok("Foreign".into()),
            _ => Err("only `&str`, `&[u8]` and references to named types cross".into()),
        },
        syn::Type::Tuple(t) if t.elems.is_empty() => Ok("Unit".into()),
        syn::Type::Path(p) => {
            let seg = p.path.segments.last().ok_or("empty path")?;
            Ok(match seg.ident.to_string().as_str() {
                "i64" | "i32" | "isize" | "u32" | "usize" => "Int".into(),
                "f64" => "Float".into(),
                "bool" => "Bool".into(),
                "String" => "String".into(),
                "Vec" => "String".into(),
                _ => "Foreign".into(),
            })
        }
        _ => Err("unsupported type at the boundary".into()),
    }
}

/// `sha256_hex` -> `sha256Hex`. Axiom's stdlib is camelCase throughout
/// (`strFromLit`, `sysWrite`, `vecPush`), so a binding that kept Rust's
/// snake_case would read as foreign in a way the call itself does not.
fn camel(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut up = false;
    for c in s.chars() {
        if c == '_' { up = true } else if up { out.extend(c.to_uppercase()); up = false }
        else { out.push(c) }
    }
    out
}
