//! GENERATED by `axiom build --emit-rust-binding` from hostlib.ax. Do not edit.
//!
//! Link the archive `--emit-staticlib` wrote beside this file; every
//! function below is a `pub fn` of that module, a C symbol under its own
//! name. `String` arguments are built with the archive's own `Str$strAlloc`
//! and a `String` result is an owned share the wrapper adopts.
#![allow(non_snake_case, dead_code, unused_imports, clippy::all)]

use axiom_ffi::host::AxString;
use axiom_ffi::AxWord;

mod raw {
    extern "C" {
        pub fn addTwo(a0: i64, a1: i64) -> i64;
        pub fn shout(a0: i64) -> i64;
        pub fn halve(a0: i64) -> i64;
        pub fn isEven(a0: i64) -> i64;
        pub fn nextChar(a0: i64) -> i64;
        pub fn answer() -> i64;
        pub fn same(a0: i64) -> i64;
        pub fn strLenOf(a0: i64) -> i64;
    }
}

/// `(pub :: addTwo (-> Int Int Int))`
pub fn add_two(a: i64, b: i64) -> i64 {
    // SAFETY: the archive defines the symbol with exactly this shape (one word each way).
    let __r = unsafe { raw::addTwo(a, b) };
    __r
}

/// `(pub :: shout (-> String String))`
pub fn shout(s: &str) -> AxString {
    let __a0 = AxString::from_str(s);
    // SAFETY: the archive defines the symbol with exactly this shape (one word each way).
    let __r = unsafe { raw::shout(__a0.as_word()) };
    // SAFETY: a String a function answers is an owned share (MM-LIFE-2c event 2).
    unsafe { AxString::from_owned(__r) }
}

/// `(pub :: halve (-> Float Float))`
pub fn halve(x: f64) -> f64 {
    // SAFETY: the archive defines the symbol with exactly this shape (one word each way).
    let __r = unsafe { raw::halve(x.to_bits() as i64) };
    f64::from_bits(__r as u64)
}

/// `(pub :: isEven (-> Int Bool))`
pub fn is_even(n: i64) -> bool {
    // SAFETY: the archive defines the symbol with exactly this shape (one word each way).
    let __r = unsafe { raw::isEven(n) };
    __r != 0
}

/// `(pub :: nextChar (-> Char Char))`
pub fn next_char(c: char) -> char {
    // SAFETY: the archive defines the symbol with exactly this shape (one word each way).
    let __r = unsafe { raw::nextChar(c as i64) };
    char::from_u32(__r as u32).unwrap_or('\u{FFFD}')
}

/// `(pub :: answer Int)`
pub fn answer() -> i64 {
    // SAFETY: the archive defines the symbol with exactly this shape (one word each way).
    let __r = unsafe { raw::answer() };
    __r
}

/// `(pub :: same (-> String String))`
pub fn same(s: &str) -> AxString {
    let __a0 = AxString::from_str(s);
    // SAFETY: the archive defines the symbol with exactly this shape (one word each way).
    let __r = unsafe { raw::same(__a0.as_word()) };
    // SAFETY: a String a function answers is an owned share (MM-LIFE-2c event 2).
    unsafe { AxString::from_owned(__r) }
}

/// `(pub :: strLenOf (-> String Int))`
pub fn str_len_of(s: &str) -> i64 {
    let __a0 = AxString::from_str(s);
    // SAFETY: the archive defines the symbol with exactly this shape (one word each way).
    let __r = unsafe { raw::strLenOf(__a0.as_word()) };
    __r
}

// Not bound - call these through the archive by hand, or change the type:
// `firstEven`: `(-> Int Int (Option Int))` names `(Option Int)`, which the binding does not carry
// `pairSum`: `(-> Pair Int)` names `Pair`, which the binding does not carry
