//! A Rust program calling Axiom: the other direction, worked.
//!
//! `tests/ffi/host/hostlib.ax` is an Axiom module with no `main`. Built
//! with `axiom build --emit-staticlib --emit-rust-binding hostlib.rs` it
//! is an archive whose `pub fn`s are C symbols under their own names,
//! and `src/hostlib.rs` - GENERATED by that build, checked in, and
//! diffed against a fresh generation by `scripts/check-ffi.sh` - is the
//! Rust view of them: one `extern "C"` declaration each in `raw`, and
//! one wrapper each in Rust's own types (`i64`, `f64`, `bool`, `char`,
//! `&str` in, `AxString` out) - safe, except where a raw `AxWord`
//! crosses. `build.rs` links the archive.
//!
//! # The symbols this host relies on
//!
//! | symbol | defined by | used for |
//! |---|---|---|
//! | `addTwo`, `halve`, `isEven`, `nextChar`, `answer`, `shout`, `same`, `strLenOf`, `firstEven`, `safeDiv`, `pairSum`, ... | `hostlib.ax` (`pub fn`, entry file: unmangled) | the calls below |
//! | `axh_*` | synthesised into the archive by `--emit-rust-binding` | building and reading `Pair`, `Shape`, `Named`, `List`, `Option`, `Result`, and a `Vec` |
//! | `Str$strAlloc` | `stdlib/Str.ax`, mangled `Module$name` | `AxString::from_str` allocating a `&str` argument |
//! | `axiom_release` | the emitted runtime | `AxString`'s drop giving a share back |
//!
//! `axiom_retain` and `axiom_alloc` are in the archive too (every
//! emitted module exports them); this host needs neither, because it
//! keeps nothing past the calls and builds every block through Axiom's
//! own constructors. There is no init call: the allocator initialises
//! on first use.
//!
//! Every call takes the `AxRuntime` this thread claimed first: the
//! runtime is unsynchronised, and the token is how the type system knows
//! only one thread reaches it. A second thread asking for one is
//! refused, which this program checks as well.

mod hostlib;

use axiom_ffi::host::{AxRuntime, AxString};

fn main() {
    let rt = AxRuntime::claim().expect("nothing else has claimed the Axiom runtime yet");

    // Plain words: the cheapest crossing, no marshalling either way.
    let sum = hostlib::add_two(rt, 40, 2);

    // A String argument is built by Axiom's own `strAlloc` (a real
    // block, a real header) and passed borrowed; the answer is a fresh
    // String the host now owns and releases when `reply` drops.
    let reply = hostlib::shout(rt, "hello");
    let text = reply.as_str().unwrap_or("<not utf-8>").to_owned();

    // The other leaves: Float as bits, Bool as 0/1, Char as the code
    // point, a nullary function.
    let half = hostlib::halve(rt, 5.0);
    let even = hostlib::is_even(rt, 42);
    let next = hostlib::next_char(rt, 'a');
    let answer = hostlib::answer(rt);

    // `same` answers its argument. By MM-LIFE-2c event 2 a counted
    // reference a function answers is a share of its own, so adopting
    // the result and dropping the argument are two releases of two
    // shares - which this loop proves by doing it ten thousand times
    // through the allocator's free list and reading the value each time.
    let mut same_ok = true;
    for i in 0..10_000 {
        let s = format!("round {i}");
        let back = hostlib::same(rt, &s);
        if back.as_str() != Ok(s.as_str()) || hostlib::str_len_of(rt, &s) != s.len() as i64 {
            same_ok = false;
            break;
        }
    }

    // Values with structure, through the accessor shims the build put
    // in the archive: `Option`/`Result` map to Rust's own, a `data` is
    // a struct or enum, a `struct` keeps its field names, a user `List`
    // is a boxed recursive enum, and every conversion releases what it
    // built. Round-tripped ten thousand times to prove the shares
    // balance (a leak or a double release shows up in the allocator).
    let opt = hostlib::first_even(rt, 3, 8);
    let res_ok = hostlib::safe_div(rt, 84, 2);
    let res_err = hostlib::safe_div(rt, 1, 0);
    let err_text = match &res_err {
        Err(e) => e.as_str().unwrap_or("<not utf-8>").to_owned(),
        Ok(_) => String::new(),
    };
    let mut structured_ok =
        opt == Some(8) && matches!(res_ok, Ok(42)) && err_text == "division by zero";
    for i in 0..10_000 {
        let p = hostlib::Pair { f0: i, f1: 2 * i };
        let swapped = hostlib::pair_swap(rt, &p);
        let grown = hostlib::shape_grow(rt, &hostlib::Shape::Rect(2, 3), 2);
        let circle = hostlib::shape_area(rt, &hostlib::Shape::Circle(1.0));
        let named = hostlib::named_bump(
            rt,
            &hostlib::Named {
                name: AxString::from_str(rt, "ada"),
                score: i,
            },
        );
        let list = hostlib::list_range(rt, 4);
        let sum = hostlib::list_sum(rt, &list);
        let through = hostlib::opt_pair_sum(rt, &Some(hostlib::Pair { f0: 1, f1: i }));
        let none = hostlib::opt_pair_sum(rt, &None);
        let v = hostlib::AxVecBuf::from_words(rt, &[1, 2, 3, i]);
        let doubled = hostlib::vec_double(rt, &v);
        // A value out and back: `to_axiom` answers an owned share and
        // `from_axiom` consumes it, so ten thousand of these balance.
        // SAFETY: the word is `to_axiom`'s answer, adopted once.
        let again = unsafe { hostlib::Pair::from_axiom(rt, p.to_axiom(rt)) };
        // A RAW word: a `(Vec String)` the host cannot type, so handing it
        // back is `unsafe` and releasing it is the host's job.
        let strs = hostlib::some_strs(rt);
        // SAFETY: `strs` is a live `(Vec String)` from `someStrs`, borrowed.
        let counted = unsafe { hostlib::count_strs(rt, strs) };
        let tagged = hostlib::Tagged { f0: strs, f1: 4 };
        // SAFETY: as above - the field is that same live vector.
        let tagged_len = unsafe { hostlib::tagged_len(rt, &tagged) };
        // SAFETY: the one share `someStrs` answered, given back once.
        unsafe { axiom_ffi::axiom_release(strs) };
        if hostlib::pair_sum(rt, &p) != 3 * i
            || again.f0 != i
            || again.f1 != 2 * i
            || counted != 3
            || tagged_len != 7
            || swapped.f0 != 2 * i
            || swapped.f1 != i
            || !matches!(grown, hostlib::Shape::Rect(4, 6))
            || circle != 3.0
            || named.score != i + 1
            || named.name.as_str() != Ok("ada!")
            || sum != 10
            || through != 1 + i
            || none != -1
            || hostlib::vec_sum(rt, &v) != 6 + i
            || doubled.words() != vec![2, 4, 6, 2 * i]
        {
            structured_ok = false;
            break;
        }
    }

    // The runtime belongs to this thread: another one asking is refused,
    // which is what makes every signature above the whole thread story.
    let other_refused = std::thread::spawn(|| AxRuntime::claim().is_none())
        .join()
        .unwrap_or(false);

    let agree = sum == 42
        && text == "HELLO"
        && half == 2.5
        && even
        && next == 'b'
        && answer == 42
        && same_ok
        && structured_ok
        && other_refused;
    println!(
        "host: addTwo={sum} shout={text} halve={half} isEven={even} nextChar={next} answer={answer} same={} structured={} otherThread={} {}",
        if same_ok { "ok" } else { "BROKEN" },
        if structured_ok { "ok" } else { "BROKEN" },
        if other_refused { "refused" } else { "ALLOWED" },
        if agree { "agree" } else { "DISAGREE" }
    );
    if !agree {
        std::process::exit(1);
    }
}
