//! A Rust program calling Axiom: the other direction, worked.
//!
//! `tests/ffi/host/hostlib.ax` is an Axiom module with no `main`. Built
//! with `axiom build --emit-staticlib --emit-rust-binding hostlib.rs` it
//! is an archive whose `pub fn`s are C symbols under their own names,
//! and `src/hostlib.rs` - GENERATED by that build, checked in, and
//! diffed against a fresh generation by `scripts/check-ffi.sh` - is the
//! Rust view of them: one `extern "C"` declaration each in `raw`, and
//! one safe wrapper each in Rust's own types (`i64`, `f64`, `bool`,
//! `char`, `&str` in, `AxString` out). `build.rs` links the archive.
//!
//! # The symbols this host relies on
//!
//! | symbol | defined by | used for |
//! |---|---|---|
//! | `addTwo`, `halve`, `isEven`, `nextChar`, `answer`, `shout`, `same`, `strLenOf`, `firstEven`, `safeDiv`, `pairSum`, ... | `hostlib.ax` (`pub fn`, entry file: unmangled) | the calls below |
//! | `axh_*` | synthesised into the archive by `--emit-rust-binding` | building and reading `Pair`, `Shape`, `Named`, `List`, `Option`, `Result`, and a `Vec` |
//! | `Str$strAlloc` | `stdlib/Str.ax`, mangled `Module$name` | `AxString::from_str` allocating a `&str` argument |
//! | `axiom_release` | the emitted runtime | `AxString`'s drop giving a share back |
//!
//! `axiom_retain` and `axiom_alloc` are in the archive too (every
//! emitted module exports them); this host needs neither, because it
//! keeps nothing past the calls and builds every block through Axiom's
//! own constructors. There is no init call: the allocator initialises
//! on first use.

mod hostlib;

fn main() {
    // Plain words: the cheapest crossing, no marshalling either way.
    let sum = hostlib::add_two(40, 2);

    // A String argument is built by Axiom's own `strAlloc` (a real
    // block, a real header) and passed borrowed; the answer is a fresh
    // String the host now owns and releases when `reply` drops.
    let reply = hostlib::shout("hello");
    let text = reply.as_str().unwrap_or("<not utf-8>").to_owned();

    // The other leaves: Float as bits, Bool as 0/1, Char as the code
    // point, a nullary function.
    let half = hostlib::halve(5.0);
    let even = hostlib::is_even(42);
    let next = hostlib::next_char('a');
    let answer = hostlib::answer();

    // `same` answers its argument. By MM-LIFE-2c event 2 a counted
    // reference a function answers is a share of its own, so adopting
    // the result and dropping the argument are two releases of two
    // shares - which this loop proves by doing it ten thousand times
    // through the allocator's free list and reading the value each time.
    let mut same_ok = true;
    for i in 0..10_000 {
        let s = format!("round {i}");
        let back = hostlib::same(&s);
        if back.as_str() != Ok(s.as_str()) || hostlib::str_len_of(&s) != s.len() as i64 {
            same_ok = false;
            break;
        }
    }

    // Values with structure, through the accessor shims the build put
    // in the archive: `Option`/`Result` map to Rust's own, a `data` is
    // a struct or enum, a `struct` keeps its field names, a user `List`
    // is a boxed recursive enum, and every conversion releases what it
    // built. Round-tripped ten thousand times to prove the shares
    // balance (a leak or a double release shows up in the allocator).
    let opt = hostlib::first_even(3, 8);
    let res_ok = hostlib::safe_div(84, 2);
    let res_err = hostlib::safe_div(1, 0);
    let err_text = match &res_err {
        Err(e) => e.as_str().unwrap_or("<not utf-8>").to_owned(),
        Ok(_) => String::new(),
    };
    let mut structured_ok =
        opt == Some(8) && matches!(res_ok, Ok(42)) && err_text == "division by zero";
    for i in 0..10_000 {
        let p = hostlib::Pair { f0: i, f1: 2 * i };
        let swapped = hostlib::pair_swap(&p);
        let grown = hostlib::shape_grow(&hostlib::Shape::Rect(2, 3), 2);
        let circle = hostlib::shape_area(&hostlib::Shape::Circle(1.0));
        let named = hostlib::named_bump(&hostlib::Named {
            name: axiom_ffi::host::AxString::from_str("ada"),
            score: i,
        });
        let list = hostlib::list_range(4);
        let sum = hostlib::list_sum(&list);
        let through = hostlib::opt_pair_sum(&Some(hostlib::Pair { f0: 1, f1: i }));
        let none = hostlib::opt_pair_sum(&None);
        let v = hostlib::AxVecBuf::from_words(&[1, 2, 3, i]);
        let doubled = unsafe { hostlib::AxVecBuf::from_owned(hostlib::vec_double(v.as_word())) };
        if hostlib::pair_sum(&p) != 3 * i
            || swapped.f0 != 2 * i
            || swapped.f1 != i
            || !matches!(grown, hostlib::Shape::Rect(4, 6))
            || circle != 3.0
            || named.score != i + 1
            || named.name.as_str() != Ok("ada!")
            || sum != 10
            || through != 1 + i
            || none != -1
            || hostlib::vec_sum(v.as_word()) != 6 + i
            || doubled.words() != vec![2, 4, 6, 2 * i]
        {
            structured_ok = false;
            break;
        }
    }

    let agree = sum == 42
        && text == "HELLO"
        && half == 2.5
        && even
        && next == 'b'
        && answer == 42
        && same_ok
        && structured_ok;
    println!(
        "host: addTwo={sum} shout={text} halve={half} isEven={even} nextChar={next} answer={answer} same={} structured={} {}",
        if same_ok { "ok" } else { "BROKEN" },
        if structured_ok { "ok" } else { "BROKEN" },
        if agree { "agree" } else { "DISAGREE" }
    );
    if !agree {
        std::process::exit(1);
    }
}
