//! A Rust program calling Axiom: the other direction, worked.
//!
//! `tests/ffi/host/hostlib.ax` is an Axiom module with no `main`. Built
//! with `axiom build --emit-staticlib --emit-rust-binding hostlib.rs` it
//! is an archive whose `pub fn`s are C symbols under their own names,
//! and `src/hostlib.rs` - GENERATED by that build, checked in, and
//! diffed against a fresh generation by `scripts/check-ffi.sh` - is the
//! Rust view of them: one `extern "C"` declaration each in `raw`, and
//! one safe wrapper each in Rust's own types (`i64`, `f64`, `bool`,
//! `char`, `&str` in, `AxString` out). `build.rs` links the archive.
//!
//! # The symbols this host relies on
//!
//! | symbol | defined by | used for |
//! |---|---|---|
//! | `addTwo`, `halve`, `isEven`, `nextChar`, `answer`, `shout`, `same`, `strLenOf` | `hostlib.ax` (`pub fn`, entry file: unmangled) | the calls below |
//! | `Str$strAlloc` | `stdlib/Str.ax`, mangled `Module$name` | `AxString::from_str` allocating a `&str` argument |
//! | `axiom_release` | the emitted runtime | `AxString`'s drop giving a share back |
//!
//! `axiom_retain` and `axiom_alloc` are in the archive too (every
//! emitted module exports them); this host needs neither, because it
//! keeps nothing past the calls and builds every block through Axiom's
//! own constructors. There is no init call: the allocator initialises
//! on first use.

mod hostlib;

fn main() {
    // Plain words: the cheapest crossing, no marshalling either way.
    let sum = hostlib::add_two(40, 2);

    // A String argument is built by Axiom's own `strAlloc` (a real
    // block, a real header) and passed borrowed; the answer is a fresh
    // String the host now owns and releases when `reply` drops.
    let reply = hostlib::shout("hello");
    let text = reply.as_str().unwrap_or("<not utf-8>").to_owned();

    // The other leaves: Float as bits, Bool as 0/1, Char as the code
    // point, a nullary function.
    let half = hostlib::halve(5.0);
    let even = hostlib::is_even(42);
    let next = hostlib::next_char('a');
    let answer = hostlib::answer();

    // `same` answers its argument. By MM-LIFE-2c event 2 a counted
    // reference a function answers is a share of its own, so adopting
    // the result and dropping the argument are two releases of two
    // shares - which this loop proves by doing it ten thousand times
    // through the allocator's free list and reading the value each time.
    let mut same_ok = true;
    for i in 0..10_000 {
        let s = format!("round {i}");
        let back = hostlib::same(&s);
        if back.as_str() != Ok(s.as_str()) || hostlib::str_len_of(&s) != s.len() as i64 {
            same_ok = false;
            break;
        }
    }

    let agree = sum == 42
        && text == "HELLO"
        && half == 2.5
        && even
        && next == 'b'
        && answer == 42
        && same_ok;
    println!(
        "host: addTwo={sum} shout={text} halve={half} isEven={even} nextChar={next} answer={answer} same={} {}",
        if same_ok { "ok" } else { "BROKEN" },
        if agree { "agree" } else { "DISAGREE" }
    );
    if !agree {
        std::process::exit(1);
    }
}
