#!/usr/bin/env bash
# Build the Axiom compiler from a clean checkout, with no Rust.
#
# This is the script that makes deleting the Rust compiler possible. The
# self-hosting fixpoint has been reached for some time - stage2 and
# stage3 are byte-identical, and stage2 builds stage3 through its own
# driver with no Rust involved - but every one of those ladders starts
# by asking the Rust compiler for a stage1. Remove the Rust crates and a
# fresh clone has nothing at all to build with. A checked-in seed is
# what replaces it.
#
#   bootstrap/axiom-<target>.ll   the compiler, as LLVM IR, one per
#                                 target, generated by a PREVIOUS
#                                 compiler and committed
#   llc + cc                      turn that into `seed`
#   seed                          compiles self_host/ into stage1
#   stage1 -> stage2 -> stage3    the ordinary ladder, from source
#
# THE SEED IS NOT ASSERTED TO MATCH THE SOURCE, and that is deliberate.
# A seed regenerated on every commit would put 8.4 MB of generated text
# in every diff that touches the compiler, and the property it would buy
# - "the seed is this exact source" - is not the property a fresh clone
# needs. What a clone needs is "the seed can build this source", which
# is what this script checks, and which is also what catches the seed
# going stale: if the compiler's source starts using something the
# committed seed cannot compile, this fails, and `scripts/reseed.sh`
# is the fix. That is the same bargain Go and Rust make with their
# bootstrap toolchains.
#
# What a tampered seed would have to survive: compiling the whole
# compiler from source, then having ITS output compile the compiler
# again to a byte-identical fixpoint, then having that build and run a
# working program. Ken Thompson's attack still applies, as it does to
# every bootstrapped compiler; everything short of it does not.
#
# Requires: llc, cc. Not cargo, not rustc.

set -uo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

fail() { echo "FAIL: $*" >&2; exit 1; }

command -v llc >/dev/null || fail "llc is not on PATH"
command -v cc  >/dev/null || fail "cc is not on PATH"

# The host target names the seed to use. A freestanding binary cannot
# ask the kernel what it is running on, so the target is chosen when the
# compiler is COMPILED - which is exactly why there is one seed per
# target rather than one seed.
case "$(uname -s)" in
  Darwin) os=darwin ;;
  Linux)  os=linux ;;
  *) fail "unsupported OS $(uname -s): the seeds cover darwin and linux" ;;
esac
case "$(uname -m)" in
  arm64|aarch64) arch=aarch64 ;;
  x86_64|amd64)  arch=x86_64 ;;
  *) fail "unsupported architecture $(uname -m)" ;;
esac
target="$os-$arch"
seed_ll="bootstrap/axiom-$target.ll"
[[ -f "$seed_ll" ]] || fail "no seed for this host at $seed_ll"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# The compiler resolves `(import Foo)` against `self_host/` and
# `stdlib/` relative to its working directory.
ln -s "$repo_root/stdlib"    "$work/stdlib"
ln -s "$repo_root/self_host" "$work/self_host"

# ---------------------------------------------------------------
# Integrity: the seed is what the tree says it is.
#
# This is not a trust check - a committed hash and a committed file
# move together under any edit - it is a corruption check, and it
# names the file that changed, which a link error three steps later
# does not.
# ---------------------------------------------------------------
[[ -f bootstrap/SHA256SUMS ]] \
  || fail "bootstrap/SHA256SUMS is missing: an unverifiable seed is not a seed"
# The sums name the files bare, so the check runs from beside them.
if command -v sha256sum >/dev/null; then
  sumcheck() { sha256sum -c SHA256SUMS; }
else
  sumcheck() { shasum -a 256 -c SHA256SUMS; }
fi
(cd bootstrap && sumcheck) >"$work/sums.log" 2>&1 \
  || { sed 's/^/    /' "$work/sums.log" >&2; fail "a bootstrap seed does not match its recorded hash"; }
echo "ok   the seeds match bootstrap/SHA256SUMS"

# ---------------------------------------------------------------
# The seed itself.
#
# `llc` is invoked exactly as scripts/check-bootstrap.sh invokes it,
# and the reasoning there applies here unchanged: an explicit
# relocation model, and NOT -O0. At -O0 there is no tail-call
# elimination and a compiler compiling its own source overflows its
# stack; at the default level the bump allocator's chunking is
# rearranged but the compiler is correct. Changing this line means
# re-reading that comment first.
# ---------------------------------------------------------------
llc -filetype=obj -relocation-model=pic "$seed_ll" -o "$work/seed.o" 2>"$work/llc.err" \
  || { head -3 "$work/llc.err" >&2; fail "llc rejected $seed_ll"; }
cc "$work/seed.o" -o "$work/seed" -e _main 2>"$work/cc.err" \
  || { head -3 "$work/cc.err" >&2; fail "could not link the seed"; }
echo "ok   seed built for $target from $seed_ll (no Rust)"

# A stage reads `in.ax` and writes LLVM to stdout, so compiling the
# compiler means feeding it its own entry point.
build_next() {
  local from="$1" out_ll="$2" out_bin="$3"
  cp "$repo_root/self_host/main.ax" "$work/in.ax"
  (cd "$work" && "./$from" >"$out_ll" 2>"$out_ll.err") \
    || { head -5 "$work/$out_ll.err" >&2; fail "$from could not compile self_host/main.ax"; }
  # Blame the stage that produced the garbage, not the tool that
  # chokes on it. Ablated with a seed that was a valid Axiom program
  # but not a compiler, the failure without these two lines read
  # "llc rejected the IR" - true, and it points at the wrong file.
  grep -q "^target triple" "$work/$out_ll" \
    || fail "$from emitted no LLVM module - it is not a compiler"
  (( $(wc -l <"$work/$out_ll") > 10000 )) \
    || fail "$from emitted only $(wc -l <"$work/$out_ll") lines for the compiler - the emit was truncated"
  llc -filetype=obj -relocation-model=pic "$work/$out_ll" -o "$work/$out_bin.o" 2>"$work/llc.err" \
    || { head -3 "$work/llc.err" >&2; fail "llc rejected the IR $from produced"; }
  cc "$work/$out_bin.o" -o "$work/$out_bin" -e _main 2>"$work/cc.err" \
    || { head -3 "$work/cc.err" >&2; fail "could not link $out_bin"; }
}

# ---------------------------------------------------------------
# The seed compiles the tree. This is the staleness check, and it is
# the whole reason the seed is allowed to lag the source: if
# self_host/ starts using a construct the committed seed cannot
# compile, it fails HERE, naming the construct, rather than in some
# consumer months later.
# ---------------------------------------------------------------
build_next seed stage1.ll stage1
echo "ok   the seed compiled the current self_host/ into stage1"

build_next stage1 stage2.ll stage2
build_next stage2 stage3.ll stage3

if ! cmp -s "$work/stage2.ll" "$work/stage3.ll"; then
  cmp "$work/stage2.ll" "$work/stage3.ll" >&2 | head -3
  fail "stage2 and stage3 differ: the ladder from the seed does not reach a fixpoint"
fi
if ! cmp -s "$work/stage2.o" "$work/stage3.o"; then
  fail "stage2 and stage3 IR matched but their objects differ"
fi
echo "ok   stage2 and stage3 are byte-identical - the fixpoint holds from the seed"

# ---------------------------------------------------------------
# And it compiles a real program. Two compilers can agree byte for
# byte on their own source and still both be wrong, which is why
# every ladder in this repository ends with something that RUNS.
# ---------------------------------------------------------------
mkdir -p "$work/prog"
cat >"$work/prog/hello.ax" <<'CASE'
(import IO)
(:: main Int)
;@axiom:effect(io)
(fn (main) { (println "bootstrapped") 42 })
CASE
ln -s "$repo_root/stdlib" "$work/prog/stdlib"
(cd "$work/prog" && "$work/stage3" build --input hello.ax --output hello >build.log 2>&1) \
  || { sed 's/^/    /' "$work/prog/build.log" | head -5 >&2; fail "stage3 could not build a program"; }
out="$("$work/prog/hello")"; got=$?
[[ "$got" == 42 && "$out" == "bootstrapped" ]] \
  || fail "a program built from the seeded compiler said '$out'/$got, want 'bootstrapped'/42"
echo "ok   a program built by the seeded compiler runs correctly"

echo
echo "bootstrapped from source with no Rust compiler: $seed_ll -> stage1 -> stage2 == stage3"
