#!/usr/bin/env bash
# Build the Axiom compiler from a clean checkout, with no Rust.
#
# This is the script that makes deleting the Rust compiler possible. The
# self-hosting fixpoint has been reached for some time - stage2 and
# stage3 are byte-identical, and stage2 builds stage3 through its own
# driver with no Rust involved - but every one of those ladders starts
# by asking the Rust compiler for a stage1. Remove the Rust crates and a
# fresh clone has nothing at all to build with. A checked-in seed is
# what replaces it.
#
#   bootstrap/axiom-<target>.ll   the compiler, as LLVM IR, one per
#                                 target, generated by a PREVIOUS
#                                 compiler and committed
#   llc + cc                      turn that into `seed`
#   seed                          compiles self_host/ into stage1
#   stage1 -> stage2 -> stage3    the ordinary ladder, from source
#
# THE SEED IS NOT ASSERTED TO MATCH THE SOURCE, and that is deliberate.
# A seed regenerated on every commit would put 13.9 MB of generated
# text in every diff that touches the compiler, and the property it would buy
# - "the seed is this exact source" - is not the property a fresh clone
# needs. What a clone needs is "the seed can build this source", which
# is what this script checks, and which is also what catches the seed
# going stale: if the compiler's source starts using something the
# committed seed cannot compile, this fails, and `scripts/reseed.sh`
# is the fix. That is the same bargain Go and Rust make with their
# bootstrap toolchains.
#
# What a tampered seed would have to survive: compiling the whole
# compiler from source, then having ITS output compile the compiler
# again to a byte-identical fixpoint, then having that build and run a
# working program. Ken Thompson's attack still applies to THIS ladder,
# as it does to every bootstrapped compiler; `scripts/check-seed-lineage.sh`
# is what answers it, by replaying the seed's ancestry from the Rust
# compiler at `bb730db`, which no Axiom seed ever touched.
#
# Requires: llc, cc. Not cargo, not rustc.

#
# With `--install DIR` it also copies the verified compiler to
# DIR/axiom. That is how every other gate gets a compiler: they share
# one preamble (`scripts/lib/gate.sh`) whose `$axiom` defaults to
# `${AXIOM:-.axiom-bin/axiom}` and which runs this script with
# `--install` when nothing is there, so `AXIOM=<dir>/axiom` is the
# single knob that moves all of them off it. The binary installed is
# stage3 - the one that came out of the fixpoint, not the seed and not
# the first thing built from it.

set -uo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

fail() { echo "FAIL: $*" >&2; exit 1; }

install_dir=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --install) install_dir="${2:-}"; [[ -n "$install_dir" ]] || fail "--install needs a directory"; shift 2 ;;
    *) fail "unknown argument $1 (usage: $0 [--install DIR])" ;;
  esac
done

command -v llc >/dev/null || fail "llc is not on PATH"
command -v cc  >/dev/null || fail "cc is not on PATH"

# ---------------------------------------------------------------
# The LLVM middle end, which this script used to skip entirely.
#
# `llc` does instruction selection and its own backend passes. It does
# not do the middle end, and nothing here was running `opt` - so every
# stage of this ladder, and the compiler this script INSTALLS for every
# other gate to use, was built without it. Measured on one emitted
# compiler, 67,029 lines of IR, built two ways and each then asked to
# compile `self_host/main.ax`:
#
#   llc alone          16.52s
#   opt -O1 then llc    1.72s
#
# 9.6x, on the binary every gate afterwards builds with.
#
# `opt` stays OPTIONAL, exactly as `driver.ax` treats it: a PATH without
# it warns and builds, because it is genuinely not always installed and
# the result is correct either way - only slower. That is also why this
# cannot simply be added to the `command -v` checks above.
#
# It does not touch the `llc` invocations, whose level was chosen
# deliberately for a reason recorded at the seed build below and which
# still applies unchanged.
have_opt=0
command -v opt >/dev/null && have_opt=1
[[ $have_opt -eq 1 ]] || echo "warn: opt is not on PATH - stages will be correct but roughly 9x slower to run" >&2

# Answer the path `llc` should read: the optimised IR when `opt` is
# available and succeeded, the original otherwise. A failing `opt` is
# NOT fatal here for the same reason a missing one is not.
optimised() {
  local in="$1" out="$2"
  if [[ $have_opt -eq 1 ]] && opt -O1 "$in" -S -o "$out" 2>/dev/null; then
    printf '%s' "$out"
  else
    printf '%s' "$in"
  fi
}

# The host target names the seed to use. A freestanding binary cannot
# ask the kernel what it is running on, so the target is chosen when the
# compiler is COMPILED - which is exactly why there is one seed per
# target rather than one seed.
case "$(uname -s)" in
  Darwin)  os=darwin ;;
  Linux)   os=linux ;;
  FreeBSD) os=freebsd ;;
  MINGW*|MSYS*|CYGWIN*|Windows_NT)
    fail "no seed for Windows: bootstrap/ holds no axiom-windows-x86_64.ll, because hosting the compiler on Windows is a later phase of the Windows track (a Linux or macOS compiler cross-emits and links for windows-x86_64 today). README's Targets section says what is true" ;;
  *) fail "unsupported OS $(uname -s): the seeds cover darwin, linux and freebsd" ;;
esac
case "$(uname -m)" in
  arm64|aarch64) arch=aarch64 ;;
  x86_64|amd64)  arch=x86_64 ;;
  *) fail "unsupported architecture $(uname -m)" ;;
esac
target="$os-$arch"
seed_ll="bootstrap/axiom-$target.ll"

# The entry flag the two link lines below pass: `-e _main` on Darwin
# and nothing anywhere else. This script does not source
# `scripts/lib/gate.sh` (it is what that preamble runs when there is
# no compiler yet), so the rule is restated here; `gate_link_entry`
# there carries the measurement behind it.
case "$os" in
  darwin) link_entry="-e _main" ;;
  *)      link_entry="" ;;
esac
[[ -f "$seed_ll" ]] || fail "no seed for this host at $seed_ll"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# The compiler resolves `(import Foo)` against `self_host/` and
# `stdlib/` relative to its working directory.
ln -s "$repo_root/stdlib"    "$work/stdlib"
ln -s "$repo_root/self_host" "$work/self_host"

# ---------------------------------------------------------------
# Integrity: the seed is what the tree says it is.
#
# This is not a trust check - a committed hash and a committed file
# move together under any edit - it is a corruption check, and it
# names the file that changed, which a link error three steps later
# does not.
#
# It used to be a corruption check with a hole in it, and this is the
# one path where that mattered: a clone with no compiler, no CI and no
# second opinion. `shasum -c` verifies the rows it is handed and is
# silent about a file it was handed no row for, so DELETING a row and
# replacing the file it named exits 0 - measured 2026-09-03, three
# files, two OKs and rc=0. `seed_sums_verify` compares the rows and the
# files as sets, both directions, before it hashes anything.
#
# `scripts/lib/seed-sums.sh` and NOT `scripts/lib/gate.sh`: this script
# sources nothing that assumes a compiler (see the note above the
# `link_entry` case), and seed-sums.sh assumes none - it is shell, a
# `mktemp -d`, `sed`, `comm` and `shasum`.
# ---------------------------------------------------------------
source "$repo_root/scripts/lib/seed-sums.sh"
seed_sums_verify bootstrap \
  || fail "bootstrap/SHA256SUMS does not account for the seeds in bootstrap/"
echo "ok   the seeds match bootstrap/SHA256SUMS, and it names every seed present"

# NO SEPARATE "and this host's seed is named" CHECK, deliberately. The
# first draft of this block had one, and it could not fail: `$seed_ll`
# is required to exist forty lines above, and `seed_sums_verify` refuses
# any `.ll` present that the sums do not name - so a row for THIS host's
# seed is already implied by the two checks that ran. A third line
# asserting it would read as extra care and be a check with no failing
# input, which is the defect this whole file is a correction of.

# ---------------------------------------------------------------
# The seed itself.
#
# `llc` is invoked exactly as scripts/check-bootstrap.sh invokes it,
# and the reasoning there applies here unchanged: an explicit
# relocation model, and NOT -O0. At -O0 there is no tail-call
# elimination and a compiler compiling its own source overflows its
# stack; at the default level the bump allocator's chunking is
# rearranged but the compiler is correct. Changing this line means
# re-reading that comment first.
# ---------------------------------------------------------------
llc -filetype=obj -relocation-model=pic "$(optimised "$seed_ll" "$work/seed.opt.ll")" \
    -o "$work/seed.o" 2>"$work/llc.err" \
  || { head -3 "$work/llc.err" >&2; fail "llc rejected $seed_ll"; }
cc "$work/seed.o" -o "$work/seed" $link_entry 2>"$work/cc.err" \
  || { head -3 "$work/cc.err" >&2; fail "could not link the seed"; }
echo "ok   seed built for $target from $seed_ll (no Rust)"

# A stage compiles the file it is given and writes LLVM to stdout, so
# compiling the compiler means feeding it its own entry point.
#
# The filename is passed explicitly. It used to be omitted, relying on a
# bare invocation defaulting to `in.ax` - a default that made `axiom`
# with no arguments answer `cannot read input: in.ax`, naming a file the
# user never typed. The default is gone; every caller says what it means.
#
# EVERY STAGE IS BUILT TO THE SAME BASENAME IN ITS OWN DIRECTORY, and
# that is load-bearing in both directions:
#
#   input   `llc` records the BASENAME of the .ll it was handed as an
#           ELF STT_FILE symbol in .strtab, so assembling `stage2.ll` and
#           `stage3.ll` gives two objects that differ in the only thing
#           the compiler did not choose. Measured: byte-identical IR,
#           objects differing at char 253, the sole differing string
#           being the filename. Mach-O drops the record entirely, so
#           this was invisible on darwin and red on every Linux job.
#   output  macOS `ld` derives the Mach-O LC_UUID from the output path
#           and the ad-hoc signature covers it, so two byte-identical
#           compilers linked side by side as `stage2` and `stage3`
#           differ in 48 bytes. scripts/check-bootstrap.sh has built
#           its stages this way for that reason since it was written.
#
# A comparison whose inputs or outputs differ in path is a comparison of
# paths. Both hazards die under one convention: `dN/axc`.
build_next() {
  local from="$1" dir="$2"
  mkdir -p "$work/$dir"
  cp "$repo_root/self_host/main.ax" "$work/in.ax"
  # The compile itself runs with cwd=$work, where the stdlib/self_host
  # symlinks are, so `(import IO)` resolves for every stage.
  (cd "$work" && "./$from" in.ax >"$dir/axc.ll" 2>"$dir/axc.ll.err") \
    || { head -5 "$work/$dir/axc.ll.err" >&2; fail "$from could not compile self_host/main.ax"; }
  # Blame the stage that produced the garbage, not the tool that
  # chokes on it. Ablated with a seed that was a valid Axiom program
  # but not a compiler, the failure without these two lines read
  # "llc rejected the IR" - true, and it points at the wrong file.
  grep -q "^target triple" "$work/$dir/axc.ll" \
    || fail "$from emitted no LLVM module - it is not a compiler"
  (( $(wc -l <"$work/$dir/axc.ll") > 10000 )) \
    || fail "$from emitted only $(wc -l <"$work/$dir/axc.ll") lines for the compiler - the emit was truncated"
  llc -filetype=obj -relocation-model=pic \
      "$(optimised "$work/$dir/axc.ll" "$work/$dir/axc.opt.ll")" \
      -o "$work/$dir/axc.o" 2>"$work/llc.err" \
    || { head -3 "$work/llc.err" >&2; fail "llc rejected the IR $from produced"; }
  cc "$work/$dir/axc.o" -o "$work/$dir/axc" $link_entry 2>"$work/cc.err" \
    || { head -3 "$work/cc.err" >&2; fail "could not link $dir/axc"; }
}

# ---------------------------------------------------------------
# The seed compiles the tree. This is the staleness check, and it is
# the whole reason the seed is allowed to lag the source: if
# self_host/ starts using a construct the committed seed cannot
# compile, it fails HERE, naming the construct, rather than in some
# consumer months later.
# ---------------------------------------------------------------
build_next seed d1
echo "ok   the seed compiled the current self_host/ into stage1"

build_next d1/axc d2
build_next d2/axc d3

# Anti-vacuousness before the comparison, not after it: `cmp` is
# happiest when both files are empty, and two missing compilers are
# byte-identical. build_next's floors cover the IR; these cover what
# came out of the linker.
for stage in d2 d3; do
  [[ -x "$work/$stage/axc" ]] || fail "$stage/axc is not an executable file"
  (( $(wc -c <"$work/$stage/axc") > 100000 )) \
    || fail "$stage/axc is $(wc -c <"$work/$stage/axc") bytes - too small to be the compiler"
done

if ! cmp -s "$work/d2/axc.ll" "$work/d3/axc.ll"; then
  # `cmp a b >&2 | head -3`, which this used to be, redirects cmp's
  # stdout to stderr and then pipes an empty stream into `head`, so the
  # report the reader needs never arrives. check-bootstrap.sh fixed the
  # same line and named this file as still carrying it.
  cmp "$work/d2/axc.ll" "$work/d3/axc.ll" 2>&1 | head -3 | sed 's/^/    /' >&2
  fail "stage2 and stage3 differ: the ladder from the seed does not reach a fixpoint"
fi
if ! cmp -s "$work/d2/axc.o" "$work/d3/axc.o"; then
  # Identical IR through identical llc invocations that disagree is
  # almost never the compiler: it is something the OBJECT records that
  # the compiler did not choose. Print the differing bytes so the next
  # reader can see whether they spell a path.
  cmp -l "$work/d2/axc.o" "$work/d3/axc.o" 2>&1 | head -5 | sed 's/^/    /' >&2
  fail "stage2 and stage3 IR matched but their objects differ"
fi
if ! cmp -s "$work/d2/axc" "$work/d3/axc"; then
  fail "stage2 and stage3 objects matched but their binaries differ"
fi
echo "ok   stage2 and stage3 are byte-identical - the fixpoint holds from the seed"

# ---------------------------------------------------------------
# And it compiles a real program. Two compilers can agree byte for
# byte on their own source and still both be wrong, which is why
# every ladder in this repository ends with something that RUNS.
# ---------------------------------------------------------------
mkdir -p "$work/prog"
cat >"$work/prog/hello.ax" <<'CASE'
(import IO)
(:: main Int)
;@axiom:effect(io)
(fn (main) { (println "bootstrapped") 42 })
CASE
ln -s "$repo_root/stdlib" "$work/prog/stdlib"
(cd "$work/prog" && "$work/d3/axc" build --input hello.ax --output hello >build.log 2>&1) \
  || { sed 's/^/    /' "$work/prog/build.log" | head -5 >&2; fail "stage3 could not build a program"; }
out="$("$work/prog/hello")"; got=$?
[[ "$got" == 42 && "$out" == "bootstrapped" ]] \
  || fail "a program built from the seeded compiler said '$out'/$got, want 'bootstrapped'/42"
echo "ok   a program built by the seeded compiler runs correctly"

if [[ -n "$install_dir" ]]; then
  mkdir -p "$install_dir" || fail "could not create $install_dir"
  # Written beside the target and renamed over it, never copied onto
  # it. `cp` onto an existing executable truncates and rewrites the
  # same inode, and on macOS a binary that was ever executed keeps its
  # code signature cached by inode: the rewritten file passes
  # `codesign -v` and is SIGKILLed (exit 137, no output) on every
  # exec until it is replaced by a new inode. Measured 2026-08-28,
  # while three gates shared one `.axiom-bin/axiom` - every `check`
  # in the tree died silently for 45 minutes. A rename is atomic and
  # gives the kernel a new inode.
  cp "$work/d3/axc" "$install_dir/axiom.new.$$" || fail "could not install to $install_dir"
  chmod +x "$install_dir/axiom.new.$$"
  mv -f "$install_dir/axiom.new.$$" "$install_dir/axiom" || fail "could not install to $install_dir"
  # Installed only AFTER the fixpoint and the running program, so
  # `$install_dir/axiom` existing means every check above passed. A
  # gate that finds a compiler there has one that was verified, not
  # one that merely linked.
  echo "ok   installed the verified compiler at $install_dir/axiom"
fi

echo
echo "bootstrapped from source with no Rust compiler: $seed_ll -> stage1 -> stage2 == stage3"
