#!/usr/bin/env bash
# Check that the committed seed is the emission of source in this
# repository's history, by regenerating it.
#
# `bootstrap/SHA256SUMS` catches a damaged seed, and `check-bootstrap.sh`
# shows the seed can build this source. This gate asks the remaining
# question: is the seed the output of source anyone can read?
#
# It proves the seed is a reproducible build product of reviewable
# source on all six targets. A tamper then has to be findable in `.ax`
# files, not only in the LLVM IR beside them (`wc -l bootstrap/*.ll`
# shows how much IR that is). It cannot answer Ken Thompson's attack:
# the compiler that regenerates the seed is itself seed-descended.
# `check-seed-lineage.sh` covers that by replaying every seed from the
# one before it, back to the Rust compiler at `bb730db`, which no Axiom
# seed touched.
#
# The provenance commit is found from git, not read from a file.
# `reseed.sh` cannot record it, because the seed is generated from a
# dirty tree and lands in the next commit. STAMP's `Source stamp:` is
# the falsifiable half: the commit's sources must hash to it before
# anything is regenerated.
#
# The seed is the six `.ll` files, not the `bootstrap/` directory. A
# commit that only edits `bootstrap/STAMP` or `bootstrap/README.md`
# changes metadata about the seed and must not read as a reseed.
#
# It costs one compiler build plus six whole-compiler emissions, about
# seven minutes, so it is its own CI job. It needs the full history
# (`fetch-depth: 0`) because a shallow clone cannot see the commit that
# introduced a file it did not fetch.
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/gate.sh"
gate_init

failed=0
fail() { echo "FAIL: $*"; failed=$((failed + 1)); }

command -v git >/dev/null || { echo "FAIL: git is not on PATH"; exit 1; }

# The target list comes from `seed_targets` in scripts/lib/seed-sums.sh,
# the list `reseed.sh` writes. A handwritten copy could drift and pass
# while regenerating a different set, so check-seed-supply-chain.sh
# refuses one here.
source "$(dirname "${BASH_SOURCE[0]}")/lib/seed-sums.sh"
targets="$(seed_targets | tr '\n' ' ')"

# --------------------------------------------------------------------
echo "== STAMP states a source stamp, and it is well formed =="
# --------------------------------------------------------------------
stamp_file="bootstrap/STAMP"
[[ -f "$stamp_file" ]] || { echo "FAIL: $stamp_file is missing"; exit 1; }
want_stamp="$(sed -n 's/^Source stamp: *//p' "$stamp_file" | tr -d '[:space:]')"
want_files="$(sed -n 's/^Source files: *//p' "$stamp_file" | tr -d '[:space:]')"
if [[ ! "$want_stamp" =~ ^[0-9a-f]{64}$ ]]; then
  echo "FAIL: $stamp_file has no 64-hex 'Source stamp:' line"
  echo "      It read: '${want_stamp:-<nothing>}'"
  exit 1
fi
if [[ ! "$want_files" =~ ^[0-9]+$ ]] || (( want_files == 0 )); then
  echo "FAIL: $stamp_file has no positive 'Source files:' count"
  exit 1
fi
echo "ok   STAMP claims ${want_stamp:0:12}… over $want_files source files"

# STAMP must not record a `Generated from commit:` line. `reseed.sh`
# cannot know the commit the seed lands in, so such a line names the
# wrong commit.
if grep -q '^Generated from commit:' "$stamp_file"; then
  fail "$stamp_file has gone back to recording a commit; see its own note"
else
  echo "ok   it records no 'Generated from commit:' line"
fi

# --------------------------------------------------------------------
echo
echo "== the second witness =="
# --------------------------------------------------------------------
# This section reports and never fails: a `Generated on host:` line is
# the writing machine's unverifiable claim about itself.
#
# When the seed was generated on another host, such as a darwin seed
# regenerated by CI on `ubuntu-latest`, a green run is two systems and
# toolchains reaching the same IR: Wheeler's second witness, in the weak
# same-source sense. On the same host the report withholds that claim.
#
# A STAMP without the line is reported as absent, never as agreement,
# as `check-seed-lineage.sh`'s (e4) probe also holds. Do not hand-write
# the line, since STAMP must match what `reseed.sh` emits. To exercise
# each branch, put a synthetic line into a copy of STAMP.
gen_host="$(sed -n 's/^Generated on host: *//p' "$stamp_file" | sed 's/[[:space:]]*$//')"
case "$(uname -s)" in
  Darwin)  here_os=darwin ;;
  Linux)   here_os=linux ;;
  FreeBSD) here_os=freebsd ;;
  *)       here_os="$(uname -s)" ;;
esac
case "$(uname -m)" in
  arm64|aarch64) here_arch=aarch64 ;;
  x86_64|amd64)  here_arch=x86_64 ;;
  *)             here_arch="$(uname -m)" ;;
esac
here_host="$here_os-$here_arch"
if [[ -z "$gen_host" ]]; then
  echo "--   STAMP records no generating host: this seed predates the line, so"
  echo "     whether the regeneration below is a second witness is UNKNOWN."
  echo "     It arrives at the next reseed. Absent, not agreed."
elif [[ "${gen_host%% *}" == "$here_host" ]]; then
  echo "--   regenerating on $here_host, which is also where the seed was"
  echo "     generated ($gen_host). Byte-identity below is one toolchain"
  echo "     repeating itself - the provenance claim, and not a second witness."
else
  echo "ok   second witness: generated on $gen_host, regenerated here on"
  echo "     $here_host. Byte-identity below is two hosts agreeing."
fi

# --------------------------------------------------------------------
echo
echo "== the commit that carries this seed =="
# --------------------------------------------------------------------
commit="$(git -C "$repo_root" log -1 --format=%H -- 'bootstrap/*.ll' 2>/dev/null || true)"
if [[ -z "$commit" ]]; then
  echo "FAIL: no commit in history touches bootstrap/*.ll."
  echo "      A shallow clone cannot answer this - the job needs fetch-depth: 0."
  exit 1
fi
echo "ok   the six seeds were last written by ${commit:0:7}"

extract() {
  local sha="$1" dest="$2"
  rm -rf "$dest"; mkdir -p "$dest"
  ( cd "$repo_root" && git archive "$sha" self_host stdlib ) | tar -x -C "$dest"
}

tree="$work/tree"
extract "$commit" "$tree"
got_stamp="$(gate_seed_source_stamp "$tree")"
got_files="$(cd "$tree" && find self_host stdlib -name '*.ax' -type f | wc -l | tr -d ' ')"
if [[ "$got_stamp" == "$want_stamp" ]] && [[ "$got_files" == "$want_files" ]]; then
  echo "ok   its sources hash to what STAMP says ($got_files files)"
else
  fail "STAMP does not describe ${commit:0:7}'s sources"
  echo "     STAMP: $want_stamp over $want_files files"
  echo "     ${commit:0:7}: $got_stamp over $got_files files"
  echo "     Either the seed was committed without its STAMP, or STAMP was"
  echo "     edited by hand. Re-run scripts/reseed.sh and commit both."
fi

# --------------------------------------------------------------------
echo
echo "== regenerating all six seeds from those sources =="
# --------------------------------------------------------------------
# `reseed.sh`'s procedure, reproduced rather than invoked because that
# script writes into `bootstrap/` and this one must not touch the tree.
# It builds a compiler from the named sources and emits
# `self_host/main.ax` once per target.
#
# `AXIOM_STDLIB` is set for both steps, and the emit is the one that
# matters. `gate_init` exports this checkout's `stdlib/`, so an emit that
# inherited it would compile the seed commit's self_host against today's
# standard library. That is not the source STAMP names, and it may not
# even compile.
regenerate() {
  local src="$1" out="$2" log="$3"
  rm -rf "$out"; mkdir -p "$out"
  if ! AXIOM_STDLIB="$src/stdlib" "$axiom" build \
         --input "$src/self_host/main.ax" --output "$out/gen" >"$log" 2>&1; then
    return 1
  fi
  # The emit runs from a directory holding `in.ax` beside links to the
  # two module trees, the shape `reseed.sh` emits in. The input's name
  # reaches the output, so it must be `in.ax` here too. The command line
  # is the one the seed's commit emitted with (`seed_emit_argv`).
  ln -s "$src/stdlib"    "$out/stdlib"
  ln -s "$src/self_host" "$out/self_host"
  cp "$src/self_host/main.ax" "$out/in.ax"
  local t
  for t in $targets; do
    seed_emit_argv "$repo_root" "$commit" "$t"
    if ! ( cd "$out" && AXIOM_STDLIB="$src/stdlib" AXIOM_PATH=self_host ./gen "${seed_argv[@]}" \
             >"$out/axiom-$t.ll" 2>"$out/$t.err" ); then
      echo "     the $t emit failed:" >&2
      head -5 "$out/$t.err" | sed 's/^/       /' >&2
      return 1
    fi
    # `reseed.sh`'s two sanity checks. A truncated emit means the run
    # broke, and comparing it would report "differs" when nothing was
    # produced.
    grep -q '^target triple' "$out/axiom-$t.ll" || {
      echo "     the $t emit has no target triple - it is not an LLVM module" >&2
      return 1
    }
    (( $(wc -l <"$out/axiom-$t.ll") > 10000 )) || {
      echo "     the $t emit is only $(wc -l <"$out/axiom-$t.ll") lines - truncated" >&2
      return 1
    }
  done
  return 0
}

gen="$work/gen"
if ! regenerate "$tree" "$gen" "$work/build.log"; then
  fail "could not regenerate the seed from ${commit:0:7}"
  tail -20 "$work/build.log" | sed 's/^/     /'
else
  same=0
  for t in $targets; do
    if cmp -s "$gen/axiom-$t.ll" "$repo_root/bootstrap/axiom-$t.ll"; then
      echo "ok   axiom-$t.ll is byte-identical to the regeneration"
      same=$((same + 1))
    else
      fail "axiom-$t.ll differs from the regeneration"
      echo "     committed:    $(wc -c <"$repo_root/bootstrap/axiom-$t.ll" | tr -d ' ') bytes"
      echo "     regenerated:  $(wc -c <"$gen/axiom-$t.ll" | tr -d ' ') bytes"
      echo "     differing lines: $(diff "$gen/axiom-$t.ll" "$repo_root/bootstrap/axiom-$t.ll" | grep -c '^[<>]' || true)"
      { diff "$gen/axiom-$t.ll" "$repo_root/bootstrap/axiom-$t.ll" || true; } | head -8 | sed 's/^/       /'
    fi
  done
  (( same == 6 )) && echo "     all six targets, $(wc -l <"$repo_root/bootstrap/axiom-darwin-aarch64.ll" | tr -d ' ') lines each"
fi

# --------------------------------------------------------------------
echo
echo "== negative probe: a one-byte source change must move the seed =="
# --------------------------------------------------------------------
# The regeneration above means nothing if it would agree with anything.
# This changes one function body in a copy of the tree and requires the
# emission to stop matching. A comment change never reaches the IR, so
# it would prove nothing.
#
# One target is enough to show the comparison can fail, and the rest
# would cost minutes.
probe="$work/probe"
cp -R "$tree" "$probe"
victim="$probe/stdlib/Path.ax"
[[ -f "$victim" ]] || { echo "FAIL: the probe's victim file is missing"; exit 1; }
# `pathIsAbsolute` asks whether byte 0 is `/` (47). Ask about `\` (92)
# instead: one literal, one instruction, and the function is exported,
# so it cannot be optimised away.
if ! grep -q '(== (strByte p 0) 47)' "$victim"; then
  echo "FAIL: the probe's anchor is gone from stdlib/Path.ax - re-derive it"
  exit 1
fi
sed -i.bak 's/(== (strByte p 0) 47)/(== (strByte p 0) 92)/' "$victim"
rm -f "$victim.bak"
probe_out="$work/probe-out"
if ! AXIOM_STDLIB="$probe/stdlib" "$axiom" build \
       --input "$probe/self_host/main.ax" --output "$work/probe-gen" >"$work/probe.log" 2>&1; then
  fail "the probe tree does not build - the probe is measuring itself"
  tail -10 "$work/probe.log" | sed 's/^/     /'
else
  mkdir -p "$probe_out"
  ln -s "$probe/stdlib"    "$probe_out/stdlib"
  ln -s "$probe/self_host" "$probe_out/self_host"
  cp "$probe/self_host/main.ax" "$probe_out/in.ax"
  cp "$work/probe-gen" "$probe_out/gen"
  seed_emit_argv "$repo_root" "$commit" darwin-aarch64
  ( cd "$probe_out" && AXIOM_STDLIB="$probe/stdlib" AXIOM_PATH=self_host ./gen "${seed_argv[@]}" \
      >"$probe_out/out.ll" 2>"$probe_out/err" ) || true
  # The probe must produce a different emission, not an empty one, or it
  # would pass on a zero-line file.
  if ! grep -q '^target triple' "$probe_out/out.ll" \
     || (( $(wc -l <"$probe_out/out.ll") < 10000 )); then
    fail "the probe emitted nothing to compare - it would pass on an empty file"
    head -5 "$probe_out/err" | sed 's/^/     /'
  elif cmp -s "$probe_out/out.ll" "$repo_root/bootstrap/axiom-darwin-aarch64.ll"; then
    fail "one byte of stdlib/Path.ax changed and the seed did not move"
    echo "     The comparison above cannot distinguish this source from any other."
  else
    echo "ok   a one-byte source change moves the emission ($(diff "$probe_out/out.ll" "$repo_root/bootstrap/axiom-darwin-aarch64.ll" | grep -c '^[<>]' || true) lines)"
  fi
  # And the stamp moves with it, which is what makes STAMP falsifiable.
  if [[ "$(gate_seed_source_stamp "$probe")" == "$want_stamp" ]]; then
    fail "the source stamp did not move when a source byte did"
  else
    echo "ok   the source stamp moves with it"
  fi
fi

# --------------------------------------------------------------------
echo
echo "== negative probe: the wrong commit must be reported wrong =="
# --------------------------------------------------------------------
# The commit is derived, so this guards against the derivation landing
# on a different tree that happens to hash right.
#
# `moved` is the last commit at or before the seed commit to touch a
# `.ax` file, and `${moved}^` is the tree before the sources last moved.
# That tree must hash differently. When the seed rides in the commit
# that changed the sources, `moved` is the seed commit itself.
#
# A commit can carry the seed alone. A new target's name must land one
# commit before its seed, since only a compiler that knows a target can
# emit its seed. That commit's parent is then the same source tree and
# must hash the same: STAMP identifies trees, and two commits with one
# tree are one tree.
parent="$(git -C "$repo_root" rev-parse --verify "${commit}^" 2>/dev/null || true)"
moved="$(git -C "$repo_root" log -1 --format=%H "$commit" -- 'self_host/*.ax' 'stdlib/*.ax' 2>/dev/null || true)"
before="$(git -C "$repo_root" rev-parse --verify "${moved}^" 2>/dev/null || true)"
if [[ -z "$parent" || -z "$moved" || -z "$before" ]]; then
  echo "warn: ${commit:0:7} has no ancestor before its sources last moved - the wrong-commit probe cannot run here"
else
  if [[ "$moved" != "$commit" ]]; then
    extract "$parent" "$work/parent"
    if [[ "$(gate_seed_source_stamp "$work/parent")" == "$want_stamp" ]]; then
      echo "ok   ${commit:0:7} carries the seed alone; its parent ${parent:0:7} is the same source tree and hashes the same, as one tree must"
    else
      fail "${parent:0:7} touches no source file after ${moved:0:7} yet hashes differently from ${commit:0:7} - the stamp is reading something other than the sources"
    fi
  fi
  extract "$before" "$work/before"
  if [[ "$(gate_seed_source_stamp "$work/before")" == "$want_stamp" ]]; then
    fail "${before:0:7}'s sources hash the same as ${commit:0:7}'s - the stamp cannot tell them apart"
  else
    echo "ok   ${before:0:7}, the tree before the sources last moved (${moved:0:7}), hashes differently, so STAMP identifies one tree"
  fi
fi

echo
if (( failed > 0 )); then
  echo "check-seed-provenance: $failed check(s) failed"
  exit 1
fi
echo "check-seed-provenance: the seed is ${commit:0:7}'s emission, on all six targets,"
echo "                       and a one-byte source change is enough to say so"
