#!/usr/bin/env bash
#
# The public surface of the standard library must agree with the
# baseline the last release published, and every disagreement that
# BREAKS a consumer must be declared.
#
# WHY THIS EXISTS. `check-version.sh` holds nineteen literals across
# sixteen files to `VERSION`. That proves the number is STATED, not that
# it is EARNED: before this gate, deleting every `pub` name in `stdlib/`
# left all forty-five gates green. `CHANGELOG.md`'s 0.2.0 Compatibility
# section named the gap and called it the next release's work.
#
# WHAT IS COMPARED. `tests/compat/verify-compat.py` turns
# `axiom symbols --diagnostic-format=ai` into one normalised row per
# public name; its header records why the nid is identity and the type
# plus effect row is the contract, both measured rather than assumed.
#
# THE THREE VACUOUS MODES THIS GATE IS BUILT AGAINST, each with the
# thing that closes it:
#
#   1. AN EMPTY STREAM READS AS AGREEMENT. `symbols` folds every failure
#      into exit 1 and prints no table, so a tree that does not compile
#      would report "everything was removed" - or, if the comparison
#      were written the other way, nothing at all. The helper raises
#      FATAL for a non-zero exit and refuses a surface under its row
#      floor, and FATAL is distinct from every comparison result.
#
#   2. A PROBE THAT BREAKS THE BUILD SATISFIES A RED-EXPECTING TEST.
#      Found while building this: the first effect-widening probe went
#      red on `AX2001`, not on a detected widening. So section 4 asserts
#      the CLASSIFICATION each probe must produce, never merely that the
#      gate failed.
#
#   3. A BASELINE REGENERATED BY THE COMMAND THAT CHECKS IT is satisfied
#      by construction. The baseline is a committed file; section 2
#      requires it to be older than this run, and `--bless` is the only
#      thing that writes it.
#
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/gate.sh"
gate_init

failed=0
checks=0
ok()  { echo "ok   $*"; checks=$((checks + 1)); }
bad() { echo "FAIL $*"; failed=$((failed + 1)); }

helper="$repo_root/tests/compat/verify-compat.py"
baseline_dir="$repo_root/compat"
version="$(cat "$repo_root/VERSION")"

# The compiler under test, content-addressed and shared with the rest of
# the battery.
gate_build_axc axc

echo "== the baseline exists and names a released version =="
checks=$((checks + 1))
baseline=""
for f in "$baseline_dir"/*.axsym; do [[ -f "$f" ]] && baseline="$f"; done
if [[ -z "$baseline" ]]; then
  bad "no baseline under compat/ - a gate with nothing to compare against cannot fail"
  echo "     write one with: $0 --bless"
  exit 1
fi
base_version="$(basename "$baseline" .axsym)"
ok "baseline is $(basename "$baseline"), $(grep -c . "$baseline") rows"

# A baseline this run wrote is a baseline that agrees with itself. It
# has to be a committed file, and the one direction that catches a
# regenerate-then-compare is asking git whether it is dirty.
echo "== the baseline is committed, not freshly written =="
checks=$((checks + 1))
if git -C "$repo_root" diff --quiet -- "compat/$(basename "$baseline")" 2>/dev/null; then
  ok "the baseline is unmodified in the working tree"
else
  bad "compat/$(basename "$baseline") is modified - a baseline regenerated by the run that"
  echo "     checks it is satisfied by construction. Commit it, or revert it."
fi

echo "== the current surface agrees with the baseline, or the break is declared =="
checks=$((checks + 1))
diff_out="$work/diff.txt"
set +e
python3 "$helper" compare "$axc" "$work" "$baseline" "$repo_root/stdlib" > "$diff_out" 2>&1
rc=$?
set -e
if grep -q '^FATAL' "$diff_out"; then
  # NOT a compatibility verdict. A tree that does not compile must never
  # read as "every symbol was removed", and must never satisfy a
  # negative probe that only asks for a non-zero exit.
  bad "the surface could not be taken at all"
  sed 's/^/     /' "$diff_out" | head -5
elif [[ $rc -eq 0 ]]; then
  ok "no breaking difference against $base_version$(grep -c '^  ADDED' "$diff_out" > /dev/null && true)"
  sed -n 's/^  ADDED/     added:/p' "$diff_out" | head -10
else
  # Every breaking difference needs a line in compat/BREAKING naming
  # THIS version. That file is the deprecation policy made mechanical:
  # a break is allowed, and it is allowed only when someone wrote down
  # that they meant it.
  undeclared=0
  while read -r kind letter name; do
    if grep -qE "^$version[[:space:]]+$letter[[:space:]]+$name([[:space:]]|$)" \
         "$baseline_dir/BREAKING" 2>/dev/null; then
      echo "     declared: $kind $letter $name"
    else
      echo "     UNDECLARED: $kind $letter $name"
      undeclared=$((undeclared + 1))
    fi
  done < <(awk '$1=="REMOVED"||$1=="CHANGED"||$1=="WIDENED" {print $1, $2, $3}' "$diff_out")
  if [[ $undeclared -eq 0 ]]; then
    ok "every breaking difference is declared in compat/BREAKING for $version"
  else
    bad "$undeclared breaking difference(s) with no line in compat/BREAKING"
    echo "     a removed, retyped or effect-widened public name breaks a consumer."
    echo "     Either undo it, or declare it: '<version>  <kind-letter>  <name>  <why>'"
  fi
fi

# ---------------------------------------------------------------------
# The negative probes. Each plants one defect in a COPY of `stdlib/` and
# requires this gate to name the CLASSIFICATION it should produce - not
# merely to fail, because a probe that breaks the build fails too, and
# for a reason that has nothing to do with compatibility.
#
# Each is run individually. A batch-level "the ablation failed" would
# ship a vacuous assertion the moment one probe stopped reaching its
# arm: 25 of 26 `check-driver` cases once failed correctly and the 26th
# passed on both sides.
# ---------------------------------------------------------------------
echo "== the hole in the stream is exactly the hole we wrote down =="
# `symbols` carries no row for a macro, for an impl method, or for an
# effect declaration itself. Those names are public API this gate
# cannot see, so they are listed in `compat/UNCOVERED` and compared as
# a SET - a count would let one name leave the stream while another
# joined it, and a fourteenth invisible name has to be loud.
checks=$((checks + 1))
have="$work/uncovered.have"
want="$work/uncovered.want"
python3 "$helper" uncovered "$axc" "$work" "$repo_root/stdlib" 2>/dev/null | LC_ALL=C sort > "$have"
grep -v '^#' "$baseline_dir/UNCOVERED" | grep -v '^[[:space:]]*$' | LC_ALL=C sort > "$want"
if diff -q "$have" "$want" > /dev/null; then
  n="$(grep -c . "$have" || true)"
  if [[ "$n" -eq 0 ]]; then
    ok "every public name reaches the symbol stream"
  else
    ok "$n public names are outside the stream, exactly as compat/UNCOVERED records"
  fi
else
  bad "the set of names outside the symbol stream has moved"
  diff "$want" "$have" | sed 's/^/     /' | head -10
  echo "     '<' left the list, '>' joined it. A name joining it is a REGRESSION:"
  echo "     it is public API that no gate can see. Update compat/UNCOVERED only"
  echo "     when a name LEAVES."
fi

echo "== the negative probes =="

probe() {                       # name  expect-classification  file  old  new
  local name="$1" expect="$2" file="$3" old="$4" new="$5"
  local abl="$work/abl"
  rm -rf "$abl"; cp -r "$repo_root/stdlib" "$abl"
  checks=$((checks + 1))
  if ! python3 - "$abl/$file" "$old" "$new" <<'PY'
import sys
path, old, new = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path, encoding="utf-8") as fh:
    s = fh.read()
if old not in s:
    sys.exit(f"probe text absent from {path}: {old!r}")
with open(path, "w", encoding="utf-8") as fh:
    fh.write(s.replace(old, new, 1))
PY
  then
    bad "$name: could not plant the defect - the probe has rotted against the source"
    return
  fi
  local out; out="$(python3 "$helper" compare "$axc" "$work" "$baseline" "$abl" 2>&1 || true)"
  if printf '%s\n' "$out" | grep -q '^FATAL'; then
    bad "$name: the probe stopped the tree compiling, so it proves nothing about this gate"
    printf '%s\n' "$out" | sed 's/^/     /' | head -3
  elif printf '%s\n' "$out" | grep -qE "^  $expect\$"; then
    ok "$name -> $expect"
  else
    bad "$name: expected '$expect', got:"
    printf '%s\n' "$out" | sed 's/^/     /' | head -5
  fi
  rm -rf "$abl"
}

probe "a public name leaves the API" "REMOVED F vecPop" Vec.ax \
  '(pub :: vecPop (-> Int Int))' '(:: vecPop (-> Int Int))'

probe "a signature changes" "CHANGED F unwrapOr" Err.ax \
  '(pub :: unwrapOr (-> (Result a e) a a))' '(pub :: unwrapOr (-> (Result a zz) a a))'

# The widening probe has to make the body PERFORM the effect as well as
# declare it, and both halves are the interesting part.
#
# Effects have been checked claims since 0.3.0: a tag over a body that
# does not reach a syscall is `AX3010`, and a body that reaches one
# without the tag is `AX3042`. So an effect row cannot widen by
# accident - which is exactly why this gate can see it, and why the
# substitution below carries the tag and the syscall together.
#
# And the subject has to be a function NOTHING CALLS. Effects are
# inferred transitively, so widening a leaf widens every caller above
# it and the tree stops compiling on the first one that does not
# declare it - which is `AX3042` doing its job, and a probe that proves
# nothing about this gate. `isErr` is one of the eight exports
# `docs/error-model.md` records as reached by no fixture and no caller.
#
# The syscall number is a literal rather than `Sys.ax`'s named
# constant, so the probe needs no import and stays inside `Err.ax`.
probe "an effect row widens" "WIDENED F isErr" Err.ax \
  '(pub :: isErr (-> (Result a e) Bool))

(pub fn (isErr r)
  (match r
    ((Ok x) false)
    ((Err y) true)
  )
)' ';@axiom:effect(io)
(pub :: isErr (-> (Result a e) Bool))

(pub fn (isErr r)
  { (__syscall3 20 0 0 0)
    (match r
      ((Ok x) false)
      ((Err y) true)
    ) }
)'

# The one probe that must stay GREEN. A gate that reddens on every
# difference is not a compatibility gate, it is a freeze - and it would
# make adding a function to the standard library a breaking change.
checks=$((checks + 1))
abl="$work/abl"; rm -rf "$abl"; cp -r "$repo_root/stdlib" "$abl"
printf '\n(pub :: compatProbeAdded Int)\n\n(pub fn (compatProbeAdded) 7)\n' >> "$abl/Vec.ax"
if out="$(python3 "$helper" compare "$axc" "$work" "$baseline" "$abl" 2>&1)"; then
  if printf '%s\n' "$out" | grep -q '^  ADDED F compatProbeAdded$'; then
    ok "a new public name is ADDED and not breaking"
  else
    bad "adding a public name did not report ADDED"; printf '%s\n' "$out" | sed 's/^/     /' | head -4
  fi
else
  bad "adding a public name was treated as breaking - this gate is a freeze, not a contract"
  printf '%s\n' "$out" | sed 's/^/     /' | head -4
fi
rm -rf "$abl"

# And the mode the other three cannot show: a tree that does not compile
# must answer FATAL, never a compatibility verdict. Without this, every
# probe above could be satisfied by a syntax error.
echo "== a tree that does not compile is not a compatibility verdict =="
checks=$((checks + 1))
rm -rf "$abl"; cp -r "$repo_root/stdlib" "$abl"
printf '\n(pub :: broken (-> \n' >> "$abl/Vec.ax"
out="$(python3 "$helper" compare "$axc" "$work" "$baseline" "$abl" 2>&1 || true)"
if printf '%s\n' "$out" | grep -q '^FATAL'; then
  ok "an uncompilable stdlib answers FATAL, not REMOVED"
else
  bad "an uncompilable stdlib produced a compatibility verdict:"
  printf '%s\n' "$out" | sed 's/^/     /' | head -4
fi
rm -rf "$abl"

echo
if [[ $failed -eq 0 ]]; then
  echo "check-compat: $checks checks passed"
else
  echo "check-compat: $failed of $checks checks FAILED"
  exit 1
fi
