#!/usr/bin/env bash
#
# The public surface of the standard library must agree with the
# baseline the last release published, and every disagreement that
# BREAKS a consumer must be declared.
#
# WHY THIS EXISTS. `check-version.sh` holds nineteen literals across
# sixteen files to `VERSION`. That proves the number is STATED, not that
# it is EARNED: before this gate, deleting every `pub` name in `stdlib/`
# left all forty-five gates green. `CHANGELOG.md`'s 0.2.0 Compatibility
# section named the gap and called it the next release's work.
#
# WHAT IS COMPARED. `tests/compat/verify-compat.py` turns
# `axiom symbols --diagnostic-format=ai` into one normalised row per
# public name; its header records why the nid is identity and the type
# plus effect row is the contract, both measured rather than assumed.
#
# THE THREE VACUOUS MODES THIS GATE IS BUILT AGAINST, each with the
# thing that closes it:
#
#   1. AN EMPTY STREAM READS AS AGREEMENT. `symbols` folds every failure
#      into exit 1 and prints no table, so a tree that does not compile
#      would report "everything was removed" - or, if the comparison
#      were written the other way, nothing at all. The helper raises
#      FATAL for a non-zero exit and refuses a surface under its row
#      floor, and FATAL is distinct from every comparison result.
#
#   2. A PROBE THAT BREAKS THE BUILD SATISFIES A RED-EXPECTING TEST.
#      Found while building this: the first effect-widening probe went
#      red on `AX2001`, not on a detected widening. So section 4 asserts
#      the CLASSIFICATION each probe must produce, never merely that the
#      gate failed.
#
#   3. A BASELINE REGENERATED BY THE COMMAND THAT CHECKS IT is satisfied
#      by construction. The baseline is a committed file; section 2
#      requires it to be older than this run, and `--bless` is the only
#      thing that writes it.
#
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/gate.sh"
gate_init

failed=0
checks=0
ok()  { echo "ok   $*"; checks=$((checks + 1)); }
bad() { echo "FAIL $*"; failed=$((failed + 1)); }

# Is this break declared against a version strictly newer than the
# baseline's? `sort -V` decides, so 0.10.0 beats 0.9.0.
#
# DEFINED HERE, above every use, and that is not a style choice. The
# first version of this gate defined it thirty lines BELOW its only
# caller. Bash resolves a function at call time, so the call answered
# 127, `if` swallowed that as false, `set -e` never fired because a
# condition is exempt, and every declared break was reported
# UNDECLARED. No negative probe caught it, because not one of them
# exercised the DECLARED path - the gate had five probes for refusing
# and none for accepting. There is one now.
declared_newer() {  # <permit-file> <kind-letter> <name>
  # Every one of these is `local`, and `d_n` is not spelled `n`. Bash
  # scopes dynamically: an undeclared `n` here assigns straight through
  # to `undeclared_in`'s local counter of the same name, and the count
  # came back as the string `unwrapOr`. Same shape as two parallel Vecs
  # sharing one names-Vec - the write lands somewhere real and wrong.
  local brk="$1" letter="$2" name="$3" d_v d_k d_n
  while read -r d_v d_k d_n _; do
    [[ "$d_k" == "$letter" && "$d_n" == "$name" ]] || continue
    [[ "$d_v" == "$base_version" ]] && continue
    [[ "$(printf '%s\n%s\n' "$base_version" "$d_v" | sort -V | tail -1)" == "$d_v" ]] && return 0
  done < <(grep -v '^#' "$brk" 2>/dev/null | grep -v '^[[:space:]]*$')
  return 1
}

# Every breaking row in <diff-file> that <permit-file> does not declare,
# counted and named on stdout.
#
# THE REAL CHECK AND THE ACCEPTING PROBE BOTH CALL THIS, and that is the
# point. The first accepting probe called `declared_newer` directly and
# so tested the FUNCTION while the defect was at the CALL SITE - the
# call sat above the definition, answered 127, and `if` read that as
# false. Ablated, the probe stayed green through the exact bug it was
# written for. A probe has to drive the path the gate drives.
undeclared_in() {  # <diff-file> <permit-file> -> count on stdout
  local diff_file="$1" brk="$2" n=0 kind letter name
  while read -r kind letter name; do
    if declared_newer "$brk" "$letter" "$name"; then
      echo "     declared: $kind $letter $name" >&2
    else
      echo "     UNDECLARED: $kind $letter $name" >&2
      n=$((n + 1))
    fi
  done < <(awk '$1=="REMOVED"||$1=="CHANGED"||$1=="WIDENED" {print $1, $2, $3}' "$diff_file")
  echo "$n"
}

helper="$repo_root/tests/compat/verify-compat.py"
baseline_dir="$repo_root/compat"
version="$(cat "$repo_root/VERSION")"

# The compiler under test, content-addressed and shared with the rest of
# the battery.
gate_build_axc axc

echo "== the baseline exists and names a released version =="
checks=$((checks + 1))
baseline=""
for f in "$baseline_dir"/*.axsym; do [[ -f "$f" ]] && baseline="$f"; done
if [[ -z "$baseline" ]]; then
  bad "no baseline under compat/ - a gate with nothing to compare against cannot fail"
  echo "     write one with: $0 --bless"
  exit 1
fi
base_version="$(basename "$baseline" .axsym)"
ok "baseline is $(basename "$baseline"), $(grep -c . "$baseline") rows"

# A baseline this run wrote is a baseline that agrees with itself. It
# has to be a committed file, and the one direction that catches a
# regenerate-then-compare is asking git whether it is dirty.
echo "== the baseline is committed, not freshly written =="
checks=$((checks + 1))
if git -C "$repo_root" diff --quiet -- "compat/$(basename "$baseline")" 2>/dev/null; then
  ok "the baseline is unmodified in the working tree"
else
  bad "compat/$(basename "$baseline") is modified - a baseline regenerated by the run that"
  echo "     checks it is satisfied by construction. Commit it, or revert it."
fi

echo "== the module list and stdlib/ agree =="
# Both directions. A list checked only for existence lets a NEW module
# join `stdlib/` and stay entirely outside this gate - its whole public
# surface invisible, with every check below still green. That is
# `check-stdlib-api.sh`'s rule and the reason it gives: a list checked
# one way rots the other. The three per-target `Sys/Platform` files are
# the one exception, named rather than globbed because which one the
# baseline carries is a decision worth seeing.
checks=$((checks + 1))
listed="$work/mods.listed"
intree="$work/mods.tree"
python3 "$helper" modules "$axc" "$work" | LC_ALL=C sort > "$listed"
(cd "$repo_root" && find stdlib -name '*.ax' -type f) \
  | grep -v 'stdlib/Sys/Platform\.linux-' | LC_ALL=C sort > "$intree"
if diff -q "$listed" "$intree" > /dev/null; then
  ok "the module list and stdlib/ agree, $(grep -c . "$listed") modules"
else
  bad "the module list has drifted from stdlib/"
  diff "$listed" "$intree" | sed 's/^/     /' | head -10
  echo "     '<' is named in verify-compat.py's MODULES and not in the tree;"
  echo "     '>' is in the tree and outside this gate entirely."
fi

# Every helper the permit needs must EXIST by the time the permit runs.
#
# This is here because the alternative did not work. Bash resolves a
# function at call time, so a call above its definition answers 127 and
# `if` reads that as false - which is how the permit came to report
# every declared break as UNDECLARED while the gate passed twenty-two
# checks. A negative probe cannot cover it: the probes run near the end
# of this file, by which point every definition has been read, so the
# probe stays green through the exact bug it was written for. Measured,
# twice.
#
# So the guard is structural rather than behavioural, it sits
# immediately above the first call, and it is the only check here that
# is about this script rather than about the library.
checks=$((checks + 1))
missing=""
for f in declared_newer undeclared_in; do
  declare -F "$f" > /dev/null 2>&1 || missing="$missing $f"
done
if [[ -z "$missing" ]]; then
  ok "the permit's helpers are defined before the permit runs"
else
  bad "called before defined:$missing"
  echo "     bash resolves a function at call time; a call above its"
  echo "     definition answers 127, and \`if\` reads 127 as false - so"
  echo "     every breaking change would be reported as declared, or as"
  echo "     undeclared, depending on which way the test is written."
  exit 1
fi

echo "== the current surface agrees with the baseline, or the break is declared =="
checks=$((checks + 1))
diff_out="$work/diff.txt"
set +e
python3 "$helper" compare "$axc" "$work" "$baseline" "$repo_root/stdlib" > "$diff_out" 2>&1
rc=$?
set -e
if grep -q '^FATAL' "$diff_out"; then
  # NOT a compatibility verdict. A tree that does not compile must never
  # read as "every symbol was removed", and must never satisfy a
  # negative probe that only asks for a non-zero exit.
  bad "the surface could not be taken at all"
  sed 's/^/     /' "$diff_out" | head -5
elif [[ $rc -eq 0 ]]; then
  ok "no breaking difference against $base_version$(grep -c '^  ADDED' "$diff_out" > /dev/null && true)"
  sed -n 's/^  ADDED/     added:/p' "$diff_out" | head -10
else
  # Every breaking difference needs a line in compat/BREAKING naming
  # THIS version. That file is the deprecation policy made mechanical:
  # a break is allowed, and it is allowed only when someone wrote down
  # that they meant it.
  undeclared="$(undeclared_in "$diff_out" "$baseline_dir/BREAKING")"
  if [[ $undeclared -eq 0 ]]; then
    ok "every breaking difference is declared in compat/BREAKING for $version"
  else
    bad "$undeclared breaking difference(s) with no line in compat/BREAKING"
    echo "     a removed, retyped or effect-widened public name breaks a consumer."
    echo "     Either undo it, or declare it: '<version>  <kind-letter>  <name>  <why>'"
  fi
fi

# ---------------------------------------------------------------------
# The negative probes. Each plants one defect in a COPY of `stdlib/` and
# requires this gate to name the CLASSIFICATION it should produce - not
# merely to fail, because a probe that breaks the build fails too, and
# for a reason that has nothing to do with compatibility.
#
# Each is run individually. A batch-level "the ablation failed" would
# ship a vacuous assertion the moment one probe stopped reaching its
# arm: 25 of 26 `check-driver` cases once failed correctly and the 26th
# passed on both sides.
# ---------------------------------------------------------------------
# Is this break declared against a version strictly newer than the
# baseline's? `sort -V` decides, so 0.10.0 beats 0.9.0.

echo "== the hole in the stream is exactly the hole we wrote down =="
# `symbols` carries no row for a macro, for an impl method, or for an
# effect declaration itself. Those names are public API this gate
# cannot see, so they are listed in `compat/UNCOVERED` and compared as
# a SET - a count would let one name leave the stream while another
# joined it, and a fourteenth invisible name has to be loud.
checks=$((checks + 1))
have="$work/uncovered.have"
want="$work/uncovered.want"
python3 "$helper" uncovered "$axc" "$work" "$repo_root/stdlib" 2>/dev/null | LC_ALL=C sort > "$have"
grep -v '^#' "$baseline_dir/UNCOVERED" | grep -v '^[[:space:]]*$' | LC_ALL=C sort > "$want"
if diff -q "$have" "$want" > /dev/null; then
  n="$(grep -c . "$have" || true)"
  if [[ "$n" -eq 0 ]]; then
    ok "every public name reaches the symbol stream"
  else
    ok "$n public names are outside the stream, exactly as compat/UNCOVERED records"
  fi
else
  bad "the set of names outside the symbol stream has moved"
  diff "$want" "$have" | sed 's/^/     /' | head -10
  echo "     '<' left the list, '>' joined it. A name joining it is a REGRESSION:"
  echo "     it is public API that no gate can see. Update compat/UNCOVERED only"
  echo "     when a name LEAVES."
fi

echo "== the negative probes =="

probe() {                       # name  expect-classification  file  old  new
  local name="$1" expect="$2" file="$3" old="$4" new="$5"
  local abl="$work/abl"
  rm -rf "$abl"; cp -r "$repo_root/stdlib" "$abl"
  checks=$((checks + 1))
  if ! python3 - "$abl/$file" "$old" "$new" <<'PY'
import sys
path, old, new = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path, encoding="utf-8") as fh:
    s = fh.read()
if old not in s:
    sys.exit(f"probe text absent from {path}: {old!r}")
with open(path, "w", encoding="utf-8") as fh:
    fh.write(s.replace(old, new, 1))
PY
  then
    bad "$name: could not plant the defect - the probe has rotted against the source"
    return
  fi
  local out; out="$(python3 "$helper" compare "$axc" "$work" "$baseline" "$abl" 2>&1 || true)"
  if printf '%s\n' "$out" | grep -q '^FATAL'; then
    bad "$name: the probe stopped the tree compiling, so it proves nothing about this gate"
    printf '%s\n' "$out" | sed 's/^/     /' | head -3
  elif printf '%s\n' "$out" | grep -qE "^  $expect\$"; then
    ok "$name -> $expect"
  else
    bad "$name: expected '$expect', got:"
    printf '%s\n' "$out" | sed 's/^/     /' | head -5
  fi
  rm -rf "$abl"
}

probe "a public name leaves the API" "REMOVED F vecPop" Vec.ax \
  '(pub :: vecPop (-> Int Int))' '(:: vecPop (-> Int Int))'

probe "a signature changes" "CHANGED F unwrapOr" Err.ax \
  '(pub :: unwrapOr (-> (Result a e) a a))' '(pub :: unwrapOr (-> (Result a zz) a a))'

# The widening probe has to make the body PERFORM the effect as well as
# declare it, and both halves are the interesting part.
#
# Effects have been checked claims since 0.3.0: a tag over a body that
# does not reach a syscall is `AX3010`, and a body that reaches one
# without the tag is `AX3042`. So an effect row cannot widen by
# accident - which is exactly why this gate can see it, and why the
# substitution below carries the tag and the syscall together.
#
# And the subject has to be a function NOTHING CALLS. Effects are
# inferred transitively, so widening a leaf widens every caller above
# it and the tree stops compiling on the first one that does not
# declare it - which is `AX3042` doing its job, and a probe that proves
# nothing about this gate. `isErr` is one of the eight exports
# `docs/error-model.md` records as reached by no fixture and no caller.
#
# The syscall number is a literal rather than `Sys.ax`'s named
# constant, so the probe needs no import and stays inside `Err.ax`.
probe "an effect row widens" "WIDENED F isErr" Err.ax \
  '(pub :: isErr (-> (Result a e) Bool))

(pub fn (isErr r)
  (match r
    ((Ok x) false)
    ((Err y) true)
  )
)' ';@axiom:effect(io)
(pub :: isErr (-> (Result a e) Bool))

(pub fn (isErr r)
  { (__syscall3 20 0 0 0)
    (match r
      ((Ok x) false)
      ((Err y) true)
    ) }
)'

# The probe that exists because this gate did NOT have it. Its first
# version's contract was the nid, the type and `#effects=`, and an
# adversarial read demonstrated that swapping two fields of
# `(pub struct Error ...)` left all three byte-identical - so the gate
# was green on a layout break, which is the `AX3044` miscompile one
# module along. A `struct` is positional and `cast` reinterprets a
# block, so field ORDER is contract. `#fields=` and `#methods=` are
# carried now, and this is what proves it.
probe "a struct's fields are reordered" "CHANGED S Error" Err.ax \
  '(pub struct Error
  (code : Int)
  (message : String)
  (context : String))' '(pub struct Error
  (code : Int)
  (context : String)
  (message : String))'

# The one probe that must stay GREEN. A gate that reddens on every
# difference is not a compatibility gate, it is a freeze - and it would
# make adding a function to the standard library a breaking change.
checks=$((checks + 1))
abl="$work/abl"; rm -rf "$abl"; cp -r "$repo_root/stdlib" "$abl"
printf '\n(pub :: compatProbeAdded Int)\n\n(pub fn (compatProbeAdded) 7)\n' >> "$abl/Vec.ax"
if out="$(python3 "$helper" compare "$axc" "$work" "$baseline" "$abl" 2>&1)"; then
  if printf '%s\n' "$out" | grep -q '^  ADDED F compatProbeAdded$'; then
    ok "a new public name is ADDED and not breaking"
  else
    bad "adding a public name did not report ADDED"; printf '%s\n' "$out" | sed 's/^/     /' | head -4
  fi
else
  bad "adding a public name was treated as breaking - this gate is a freeze, not a contract"
  printf '%s\n' "$out" | sed 's/^/     /' | head -4
fi
rm -rf "$abl"

# And the mode the other three cannot show: a tree that does not compile
# must answer FATAL, never a compatibility verdict. Without this, every
# probe above could be satisfied by a syntax error.
# THE PROBE FOR THE ACCEPTING PATH, and its control.
#
# Five probes require this gate to REFUSE something and one requires it
# to stay green on an addition; not one of them ever reached
# `compat/BREAKING`. That is how a call to an undefined function sat in
# the permit reporting every declared break as undeclared, with the gate
# passing 22 checks - bash resolves a function at call time, the call
# answered 127, and `if` read that as false.
#
# The first version of this probe did not catch that either: it called
# `declared_newer` directly, so it tested the FUNCTION while the defect
# was at the CALL SITE, and it stayed green when the bug was
# reinstated. It goes through `undeclared_in` now - the same function
# the real check above calls - and it asserts BOTH directions off one
# planted break, so the permit cannot be a rubber stamp either.
checks=$((checks + 1))
abl="$work/abl"; rm -rf "$abl"; cp -r "$repo_root/stdlib" "$abl"
python3 - "$abl/Err.ax" <<'EOP'
import sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
old = "(pub :: unwrapOr (-> (Result a e) a a))"
assert old in s, "probe text absent"
open(p, "w", encoding="utf-8").write(s.replace(old, old.replace("pub ", "", 1), 1))
EOP
pdiff="$work/probe.diff"
python3 "$helper" compare "$axc" "$work" "$baseline" "$abl" > "$pdiff" 2>&1 || true
if ! grep -q '^  REMOVED F unwrapOr$' "$pdiff"; then
  bad "the permit probe did not produce the removal it needs"
  sed 's/^/     /' "$pdiff" | head -4
else
  decl="$work/BREAKING.declared"
  cat "$baseline_dir/BREAKING" > "$decl"
  printf '%s  F  unwrapOr  probe: the accepting path\n' "$version" >> "$decl"
  n_yes="$(undeclared_in "$pdiff" "$decl" 2>/dev/null)"
  n_no="$(undeclared_in "$pdiff" "$baseline_dir/BREAKING" 2>/dev/null)"
  if [[ "$n_yes" -eq 0 && "$n_no" -eq 1 ]]; then
    ok "a break declared for $version is accepted, and the same break undeclared is not"
  else
    bad "the permit does not read compat/BREAKING correctly"
    echo "     declared: expected 0 undeclared, got $n_yes"
    echo "     undeclared: expected 1 undeclared, got $n_no"
  fi
fi
rm -rf "$abl"

# A name the PREVIOUS release marked deprecated may be removed without
# a line in `compat/BREAKING` - that is what the notice buys, and this
# is the probe that it is bought rather than assumed.
#
# Both arms come off ONE planted removal and differ only in which
# baseline they are compared against, so the deprecation notice is the
# single variable. Without the control arm the check would pass for a
# gate that simply stopped reporting removals.
checks=$((checks + 1))
abl="$work/abl"; rm -rf "$abl"; cp -r "$repo_root/stdlib" "$abl"
python3 - "$abl/Err.ax" <<'EOP'
import sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
old = "(pub :: unwrapOr (-> (Result a e) a a))"
assert old in s, "probe text absent"
open(p, "w", encoding="utf-8").write(s.replace(old, old.replace("pub ", "", 1), 1))
EOP
depbase="$work/baseline.deprecated"
sed 's|^\(F unwrapOr .*\)$|\1 #deprecated=use%20a%20match|' "$baseline" > "$depbase"
if ! grep -q '^F unwrapOr .*#deprecated=' "$depbase"; then
  bad "the deprecation probe could not mark the baseline row"
else
  out_dep="$(python3 "$helper" compare "$axc" "$work" "$depbase" "$abl" 2>&1 || true)"
  out_pln="$(python3 "$helper" compare "$axc" "$work" "$baseline" "$abl" 2>&1 || true)"
  if printf '%s\n' "$out_dep" | grep -q '^  RETIRED F unwrapOr$' \
     && printf '%s\n' "$out_dep" | grep -q '0 breaking' \
     && printf '%s\n' "$out_pln" | grep -q '^  REMOVED F unwrapOr$'; then
    ok "a deprecated name is RETIRED, and the same name undeprecated is REMOVED"
  else
    bad "the deprecation notice does not change the verdict"
    echo "     with the notice:"; printf '%s\n' "$out_dep" | sed 's/^/       /' | head -3
    echo "     without it:";      printf '%s\n' "$out_pln" | sed 's/^/       /' | head -3
  fi
fi
rm -rf "$abl"

echo "== a tree that does not compile is not a compatibility verdict =="
checks=$((checks + 1))
rm -rf "$abl"; cp -r "$repo_root/stdlib" "$abl"
printf '\n(pub :: broken (-> \n' >> "$abl/Vec.ax"
out="$(python3 "$helper" compare "$axc" "$work" "$baseline" "$abl" 2>&1 || true)"
if printf '%s\n' "$out" | grep -q '^FATAL'; then
  ok "an uncompilable stdlib answers FATAL, not REMOVED"
else
  bad "an uncompilable stdlib produced a compatibility verdict:"
  printf '%s\n' "$out" | sed 's/^/     /' | head -4
fi
rm -rf "$abl"

echo
if [[ $failed -eq 0 ]]; then
  echo "check-compat: $checks checks passed"
else
  echo "check-compat: $failed of $checks checks FAILED"
  exit 1
fi
