#!/usr/bin/env bash
# The seed lineage is rooted outside Axiom, and here is the replay that
# says so - every link a checkpoint does not certify on every run, every
# link under `--full`.
#
# WHAT `check-seed-provenance.sh` LEAVES OPEN. That gate regenerates the
# six seeds from their own commit's sources and requires byte identity,
# so a tampered seed must be a tamper someone can find by reading `.ax`
# files. But the compiler doing the regenerating is built FROM the seed
# under test, so a seed that reproduces a backdoor in its own output
# reproduces it there too - Ken Thompson's *Reflections on Trusting
# Trust*, and its own header says so. What answers that is a compiler
# that is NOT descended from any Axiom seed, and this repository has
# one: the Rust implementation it deleted on 2026-08-08 (`430a138`),
# whose last commit `bb730db` is still in this history and still
# builds with cargo. Measured 2026-08-29: it compiles the `self_host/`
# tree of the FIRST seed commit `60445dc` into a stage1 whose emission
# of that tree is byte-identical to the committed first seed - Wheeler's
# diverse double-compile, at the root of the lineage. From that root
# every later seed reproduces from the one before it, and
# `bootstrap/CHAIN` records how.
#
# WHAT THIS PROVES. Every row of `bootstrap/CHAIN` names a committed
# seed, the seed it reproduces from, and the method; replaying a row
# builds the previous seed with `llc` and `cc`, has it compile the
# next seed's tree, and requires the result - or its own re-emission -
# to equal the next seed byte for byte. A chain whose every row
# replays, whose first row is the Rust anchor and whose last row is the
# seed in the tree, is a lineage in which no seed was ever emitted by a
# compiler that is not itself in the lineage. The three committed seeds
# that WERE emitted by such compilers (`1c682ef`, `24bdf29`, `79c8ebc`
# - each generated by a build of an uncommitted tree, before
# `reseed.sh` learned not to) are declared as orphans, bypassed by
# name, and the bypass is what gets replayed: a walk through the
# commits around them with two recorded bridges, and a link that skips
# the third.
#
# THE TRUST BASE, stated as `bootstrap/README.md` states it: `git`,
# `llc`, `cc` (and `opt`, optional), `cargo` and `rustc` and the crates
# `bb730db`'s `Cargo.lock` pins, and the 28,082 lines of Rust at
# `bb730db`. No Axiom binary is called before the comparison - the gate
# reads its own body to assert that - and `AXIOM_STDLIB` is set to the
# extracted tree's `stdlib` for every emission, never to this
# checkout's, for the reason `check-seed-provenance.sh` records at its
# regeneration step.
#
# THE HOST TARGET ONLY. Every link builds a compiler and runs it, which
# needs the host's seed; a seed for another target is text this host
# cannot execute. Emission is a pure function of source and target
# (`check-reproducible.sh`, `check-cross-targets.sh`, and the six-target
# regeneration in `check-seed-provenance.sh`), so a link that replays
# for one target replays for all six, and the row's stage is the same
# on every host.
#
# THE CHECKPOINT, and the one thing it must not become. Replaying from
# the anchor costs time linear in the number of reseeds this project has
# EVER done, and most of that time re-derives a prefix whose answer
# cannot change: a seed committed in July either replayed or did not,
# and nothing since alters that. So `bootstrap/CHAIN.checkpoint` records
# the prefix that a `--full` run derived, and the rows AFTER it are what
# a default run replays.
#
# A naive "trust rows up to N" would be a machine for laundering a bad
# seed - anyone who can edit the file skips whatever they like - so the
# checkpoint carries the DIGEST of exactly the rows it covers, and this
# gate recomputes that digest from `bootstrap/CHAIN` as it stands, on
# every run, before it skips anything. A covered row that moved by one
# byte digests differently and the checkpoint is void: the gate replays
# every row from the anchor and goes red until the prefix is blessed
# again. Editing an old row cannot shrink the work; it can only enlarge
# it. Blessing is `AXIOM_BLESS=1 ... --full` and nothing else - never a
# side effect of a passing run - and it never covers the newest row.
# The section headed `== bootstrap/CHAIN.checkpoint ==` states what the
# file does and does not prove; it is a record, not a signature.
#
# COST, measured on darwin-aarch64 (Homebrew LLVM 23.1.0, cargo 1.97.1)
# on 2026-08-31, over a 14-row table:
#   `--full`, fourteen rows from the anchor          10m40s
#   default, checkpoint certifying rows 1..13           38s
#     of which recomputing the digest                  0.7s
#     and the same run before there were checkpoints    36s
# The default run therefore costs two or three seconds more than the run
# that checked nothing about the prefix, and answers a question that one
# did not ask. It is cheap enough for the per-push job, which is where
# it runs.
#
# WHERE THE FORTY MINUTES ACTUALLY IS, because it decides whether
# parallelism would help: of the 590 s of replay in a `--full` run, 408
# is ONE row - the sixty-three-commit walk at row 8, each step compiled
# by the compiler the step before built, which is sequential by
# construction. Rows are independent given their starting seed, so a
# matrix across them is possible, but its critical path is that row: the
# best a fourteen-way matrix buys is 590 -> 408 s of replay, about 1.3x,
# for fourteen checkouts of a 30 MB history. The checkpoint removes that
# row from the per-push path entirely, which is why it is the answer
# here and a matrix is not.
# `--full` is the nightly job; the per-push job runs the default when
# `bootstrap/` moved. `AXIOM_LINEAGE_FULL=1` is `--full` for a caller
# that cannot pass an argument.
#
# NEGATIVE PROBES, each a real run against the artifacts just built:
# one byte flipped in a copy of the seed fails the comparison; the
# newest row re-pointed at a different predecessor fails the replay;
# and under `--full` with cargo, one byte changed in the Rust anchor's
# codegen (`sgt` -> `sge`, so `>` compiles as `>=`) stops it
# reproducing the first seed, while one byte changed in the `.ax` tree
# it compiles moves the emission by exactly two lines.

set -uo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/gate.sh"
# `--no-stdlib`: this gate never compiles this checkout's sources, and
# an exported `AXIOM_STDLIB` naming them is exactly the wrong tree for
# every emission below. `gate_init` may bootstrap `.axiom-bin/axiom`
# when none is there; that binary is never invoked here.
gate_init --no-stdlib

full=0
case "${1:-}" in
  --full) full=1 ;;
  "") ;;
  *) echo "usage: $0 [--full]   (or AXIOM_LINEAGE_FULL=1 $0)" >&2; exit 2 ;;
esac
# The same switch for a caller that cannot pass an argument - a shared
# CI `run:` line, a cron wrapper - spelled the way every option in this
# repository's gates is spelled: an `AXIOM_`-prefixed variable set to
# `1`, read once, and reported where it takes effect. `AXIOM_BLESS` is
# the precedent and the second variable here follows it exactly.
[[ "${AXIOM_LINEAGE_FULL:-0}" == 1 ]] && { full=1; echo "AXIOM_LINEAGE_FULL=1: replaying every row"; }
bless="${AXIOM_BLESS:-0}"

failed=0; checks=0; skipped=0
# `probe_mode` re-points the two reporters at a scratch counter, so the
# table validation can be run over a deliberately broken copy of CHAIN
# and asked whether it went red, without the run itself going red.
probe_mode=0; probe_failed=0; probe_first=""
fail() {
  if (( probe_mode )); then probe_failed=$((probe_failed + 1)); [[ -z "$probe_first" ]] && probe_first="$*"; return; fi
  echo "FAIL: $*"; failed=$((failed + 1))
}
ok()   { (( probe_mode )) && return; echo "ok   $*"; checks=$((checks + 1)); }
skip() { echo "skip: $*"; skipped=$((skipped + 1)); }

# The anchor. `430a138` deleted the Rust compiler; its parent is the
# last commit that holds the sources, and the gate builds THAT, so a
# reviewer reads 28,082 lines of Rust at one named commit.
anchor="bb730db691c55b63464e822958acbdb9514f9d1d"
chain="bootstrap/CHAIN"
checkpoint="bootstrap/CHAIN.checkpoint"
lineage_dir="bootstrap/lineage"

command -v git >/dev/null || { echo "FAIL: git is not on PATH"; exit 1; }
command -v llc >/dev/null || { echo "FAIL: llc is not on PATH"; exit 1; }
command -v cc  >/dev/null || { echo "FAIL: cc is not on PATH"; exit 1; }
have_opt=0; command -v opt >/dev/null && have_opt=1
(( have_opt )) || echo "warn: opt is not on PATH - every compiler built here runs about three times slower"

# The stack. Two of the compilers on the walk need more than the 8 MB
# macOS default to compile their successor (measured on the 2026-08-15
# commits), so every emission runs at the hard limit - 64 MB here,
# unlimited on most Linux hosts.
ulimit -s hard 2>/dev/null || true

# ---------------------------------------------------------------------
# The gate's own body must not reach for an Axiom binary. The property
# "no seed-descended compiler before the comparison" is one a refactor
# can silently break, so it is asserted on the text below this line
# rather than remembered.
# ---------------------------------------------------------------------
self_marker='# === the compared path begins here ==='
if sed -n "/^${self_marker}\$/,\$p" "${BASH_SOURCE[0]}" | grep -nE '\$axiom($|[^_a-zA-Z0-9])|\.axiom-bin|AXIOM_AXC|gate_build_axc' ; then
  echo "FAIL: the compared path names an Axiom binary; see the lines above"
  exit 1
fi
ok "nothing below the marker invokes an Axiom binary"

# === the compared path begins here ===

case "$(uname -s)" in
  Darwin)  os=darwin ;;
  Linux)   os=linux ;;
  FreeBSD) os=freebsd ;;
  *) echo "FAIL: no seed for $(uname -s); the seeds cover darwin, linux and freebsd"; exit 1 ;;
esac
case "$(uname -m)" in
  arm64|aarch64) arch=aarch64 ;;
  x86_64|amd64)  arch=x86_64 ;;
  *) echo "FAIL: unsupported architecture $(uname -m)"; exit 1 ;;
esac
target="$os-$arch"

echo "== tools =="
echo "     $(llc --version | grep -m1 -i 'version')"
echo "     $(cc --version 2>/dev/null | head -1)"
(( have_opt )) && echo "     opt: $(command -v opt)"
have_cargo=0
if command -v cargo >/dev/null 2>&1 && command -v rustc >/dev/null 2>&1; then
  have_cargo=1
  echo "     $(cargo --version) / $(rustc --version)"
fi

# ---------------------------------------------------------------------
# Plumbing. Every compiler runs from a directory holding `in.ax` beside
# links to the two module trees, which is the shape `reseed.sh` emits
# in, and the input's NAME reaches the output, so it is `in.ax` here as
# well. `AXIOM_STDLIB` names the extracted tree's stdlib, never this
# checkout's.
# ---------------------------------------------------------------------
resolve() {  # <short-or-full> -> full hash, or empty
  git -C "$repo_root" rev-parse --verify --quiet "$1^{commit}" 2>/dev/null || true
}
has_seed() {  # <commit> -> 0 when the host's seed exists there
  git -C "$repo_root" cat-file -e "$1:bootstrap/axiom-$target.ll" 2>/dev/null
}
seed_at() {  # <commit> <out.ll>
  git -C "$repo_root" show "$1:bootstrap/axiom-$target.ll" > "$2" 2>/dev/null
}
extract() {  # <commit> <dir> [paths...] - the tree's self_host and stdlib
  local sha="$1" dest="$2"; shift 2
  mkdir -p "$dest"
  ( cd "$repo_root" && git archive "$sha" "$@" ) | tar -x -C "$dest"
}
workdir() {  # <treedir> <wdir>
  mkdir -p "$2"
  ln -sfn "$1/stdlib"    "$2/stdlib"
  ln -sfn "$1/self_host" "$2/self_host"
  cp "$1/self_host/main.ax" "$2/in.ax"
}
optimised() {
  if (( have_opt )) && opt -O1 "$1" -S -o "$2" 2>/dev/null; then printf '%s' "$2"; else printf '%s' "$1"; fi
}
# The `-O0`-free llc line `bootstrap-from-seed.sh` uses, for its reason:
# at -O0 there is no tail-call elimination and a compiler compiling its
# own source overflows its stack.
build_compiler() {  # <in.ll> <out-binary>; the reason on failure is in <out>.err
  local ir="$1" out="$2"
  llc -filetype=obj -relocation-model=pic "$(optimised "$ir" "$out.opt.ll")" -o "$out.o" 2>"$out.err" \
    && cc "$out.o" -o "$out" $link_entry 2>>"$out.err"
  local rc=$?
  rm -f "$out.opt.ll" "$out.o"
  return $rc
}
build_reason() { sed 's/\x1b\[[0-9;]*m//g' "$1.err" | grep -m1 -E 'error(\[|:)' | cut -c1-120; }
# A truncated emission is not a mismatch, it is a broken run, and it
# would compare as "differs" where the honest answer is "nothing was
# produced" - `check-seed-provenance.sh`'s floors, kept before every cmp.
emit() {  # <compiler> <wdir> <out.ll>; sets emit_reason on failure
  local comp="$1" w="$2" out="$3" rc
  ( cd "$w" && AXIOM_STDLIB="$w/stdlib" "$comp" in.ax "$target" > "$out" 2> "$out.err" ); rc=$?
  if ! grep -q '^target triple' "$out" || (( $(wc -l < "$out") <= 10000 )); then
    emit_reason="rc=$rc, $(wc -l < "$out" | tr -d ' ') lines"
    # `error[` and `error:` are the compiler's own; a bare `error`
    # would match a name such as `lspError` in a warning's text.
    local first; first="$(sed 's/\x1b\[[0-9;]*m//g' "$out.err" | grep -m1 -E 'error(\[|:)|[Ss]egmentation|[Aa]bort|fault' | cut -c1-120)"
    [[ -n "$first" ]] && emit_reason="$emit_reason: $first"
    (( rc == 139 || rc == 138 )) && emit_reason="$emit_reason: the compiler crashed (SIGSEGV)"
    return 1
  fi
  return 0
}
lines_differing() { diff "$1" "$2" | grep -c '^[<>]' || true; }

# ladder <compiler> <wdir> <seed.ll> <n> <label>
#   The compiler emits the tree: if that equals the seed, `matched`
#   is stage<n>. Otherwise the emission is built and re-emits once:
#   equality there is stage<n+1>. Anything else is a failure whose
#   reason is in `ladder_reason`. Two stages, because a link that needs
#   a third is a link whose generator was not the previous seed.
matched=""; ladder_reason=""; emit_reason=""
ladder() {
  local comp="$1" w="$2" seed="$3" n="$4" label="$5"
  local s1="$w/$label.s$n.ll" s2="$w/$label.s$((n+1)).ll"
  if ! emit "$comp" "$w" "$s1"; then ladder_reason="stage$n was not produced ($emit_reason)"; return 1; fi
  if cmp -s "$s1" "$seed"; then matched="stage$n"; final_ir="$s1"; return 0; fi
  if ! build_compiler "$s1" "$w/$label.stage$n"; then
    ladder_reason="stage$n differs from the seed by $(lines_differing "$s1" "$seed") lines and does not build ($(build_reason "$w/$label.stage$n"))"; return 1
  fi
  if ! emit "$w/$label.stage$n" "$w" "$s2"; then ladder_reason="stage$((n+1)) was not produced ($emit_reason)"; return 1; fi
  if cmp -s "$s2" "$seed"; then matched="stage$((n+1))"; final_ir="$s2"; stage_note=" (stage$n off by $(lines_differing "$s1" "$seed") lines)"; return 0; fi
  ladder_reason="MISMATCH: stage$((n+1)) differs from the seed by $(lines_differing "$s2" "$seed") lines (stage$n by $(lines_differing "$s1" "$seed"))"
  return 1
}

# The seed built into a compiler: <commit> <dir> -> <dir>/seed
seed_compiler() {
  local c="$1" d="$2"
  mkdir -p "$d"
  seed_at "$c" "$d/seed.ll" || { ladder_reason="no $target seed at ${c:0:7}"; return 1; }
  build_compiler "$d/seed.ll" "$d/seed" || { ladder_reason="the ${c:0:7} seed does not build ($(build_reason "$d/seed"))"; return 1; }
}

# ---------------------------------------------------------------------
# The methods. Each takes the previous seed commit and the next, sets
# `matched` and returns 0, or sets `ladder_reason` and returns 1.
# ---------------------------------------------------------------------
final_ir=""; stage_note=""

# seed: the previous seed compiles the next tree.
replay_seed() {  # <prev> <next> <dir>
  local prev="$1" next="$2" d="$3"
  seed_compiler "$prev" "$d" || return 1
  extract "$next" "$d/tree" self_host stdlib; workdir "$d/tree" "$d/w"
  seed_at "$next" "$d/want.ll"
  ladder "$d/seed" "$d/w" "$d/want.ll" 1 link
}

# mixed-tree: the previous seed cannot compile the next tree (that is
# asserted, so a bridge nobody needs is refused), but it can compile
# `self_host@next` over `stdlib@prev` into an intermediate that can.
# The intermediate's emission is stage2 - the intermediate itself
# being the stage1 the seed could not produce.
replay_mixed() {  # <prev> <next> <dir>
  local prev="$1" next="$2" d="$3"
  seed_compiler "$prev" "$d" || return 1
  extract "$next" "$d/tree" self_host stdlib; workdir "$d/tree" "$d/w"
  seed_at "$next" "$d/want.ll"
  if ladder "$d/seed" "$d/w" "$d/want.ll" 1 plain; then
    ladder_reason="the plain link reproduces at $matched - the mixed-tree bridge is not needed and the row must say \`seed\`"; return 1
  fi
  echo "     the plain link fails, as the bridge requires: $ladder_reason"
  extract "$prev" "$d/mixed" stdlib; extract "$next" "$d/mixed" self_host; workdir "$d/mixed" "$d/mw"
  emit "$d/seed" "$d/mw" "$d/i1.ll" || { ladder_reason="the seed cannot compile the mixed tree ($emit_reason)"; return 1; }
  build_compiler "$d/i1.ll" "$d/i1" || { ladder_reason="the intermediate does not build ($(build_reason "$d/i1"))"; return 1; }
  ladder "$d/i1" "$d/w" "$d/want.ll" 2 link
}

# skip: the previous seed reaches the next directly, over an orphan
# between them - and the orphan is shown to be one: the same seed
# compiles the orphan's tree to a fixpoint that is NOT the orphan.
replay_skip() {  # <prev> <next> <skipped> <dir>
  local prev="$1" next="$2" orphan="$3" d="$4"
  seed_compiler "$prev" "$d" || return 1
  extract "$next" "$d/tree" self_host stdlib; workdir "$d/tree" "$d/w"
  seed_at "$next" "$d/want.ll"
  ladder "$d/seed" "$d/w" "$d/want.ll" 1 link || return 1
  local got="$matched" note="$stage_note"
  extract "$orphan" "$d/otree" self_host stdlib; workdir "$d/otree" "$d/ow"
  seed_at "$orphan" "$d/orphan.ll"
  if ladder "$d/seed" "$d/ow" "$d/orphan.ll" 1 orphan; then
    ladder_reason="the ${orphan:0:7} seed REPRODUCES from ${prev:0:7} at $matched - it is not an orphan and needs a row"; return 1
  fi
  # Not the seed; but is it a fixpoint at all? Re-emit once more and
  # compare stage2 with stage3 - an orphan is a tree whose honest
  # emission is stable and simply is not what was committed.
  build_compiler "$d/ow/orphan.s2.ll" "$d/ow/orphan.stage2" || { ladder_reason="the orphan's stage2 does not build"; return 1; }
  emit "$d/ow/orphan.stage2" "$d/ow" "$d/ow/orphan.s3.ll" || { ladder_reason="the orphan's stage3 was not produced ($emit_reason)"; return 1; }
  if ! cmp -s "$d/ow/orphan.s2.ll" "$d/ow/orphan.s3.ll"; then ladder_reason="the ${orphan:0:7} tree reaches no fixpoint from ${prev:0:7}"; return 1; fi
  echo "     ${orphan:0:7} is an orphan: its tree's fixpoint from ${prev:0:7} differs from the committed seed by $(lines_differing "$d/ow/orphan.s3.ll" "$d/orphan.ll") lines"
  matched="$got"; stage_note="$note"
}

# walk: every commit between two seeds that touched `self_host/` or
# `stdlib/`, each compiled by the compiler built from the one before.
# The list is checked in (`list=`) and must equal git's, so a walk
# cannot quietly skip a commit. A step may carry a bridge:
#   <commit> mixed-tree             as above, over the PREVIOUS COMMIT's stdlib
#   <commit> patch <file> <sha256>  the previous compiler compiles a
#                                   copy of the tree with <file> applied,
#                                   and that intermediate compiles the
#                                   unpatched tree
# and at a bridged step the plain step is run first and must fail. At
# a step whose commit carries a seed, the new compiler re-emits its own
# tree and the result is compared with that seed: equal, or the
# orphan's measured distance.
walk_seed_commits=""
replay_walk() {  # <prev> <next> <listfile> <dir>
  local prev="$1" next="$2" list="$3" d="$4"
  seed_compiler "$prev" "$d" || return 1
  local want="$d/want.ll"; seed_at "$next" "$want"
  local cur="$d/seed" pc="$prev" i=0 c how arg sha t0 ts nd new s1
  t0=$SECONDS
  while read -r c how arg sha; do
    [[ -z "$c" || "$c" == \#* ]] && continue
    i=$((i + 1)); nd="$d/$i-$c"; ts=$SECONDS
    extract "$c" "$nd/tree" self_host stdlib; workdir "$nd/tree" "$nd/w"
    case "${how:-plain}" in
      plain)
        if ! emit "$cur" "$nd/w" "$nd/w/s1.ll"; then ladder_reason="step $i (${c}): the compiler from step $((i-1)) cannot compile it ($emit_reason)"; return 1; fi
        if ! build_compiler "$nd/w/s1.ll" "$nd/w/s1"; then ladder_reason="step $i (${c}): its stage1 does not build ($(build_reason "$nd/w/s1"))"; return 1; fi
        new="$nd/w/s1" ;;
      mixed-tree|patch)
        # The bridge must be needed: the plain step's compiler must not
        # be able to compile this tree.
        local plain_reason=""
        if ! emit "$cur" "$nd/w" "$nd/w/plain.s1.ll"; then plain_reason="the previous compiler cannot compile it ($emit_reason)"
        elif ! build_compiler "$nd/w/plain.s1.ll" "$nd/w/plain.s1"; then plain_reason="the IR it emits does not build ($(build_reason "$nd/w/plain.s1"))"
        elif ! emit "$nd/w/plain.s1" "$nd/w" "$nd/w/plain.s2.ll"; then plain_reason="the compiler it builds cannot compile it ($emit_reason)"
        else ladder_reason="step $i (${c}): the plain step succeeds - the \`$how\` annotation is stale"; return 1; fi
        echo "     step $i (${c}): $how bridge; the plain step fails as it must: $plain_reason"
        if [[ "$how" == mixed-tree ]]; then
          extract "$pc" "$nd/mixed" stdlib; extract "$c" "$nd/mixed" self_host; workdir "$nd/mixed" "$nd/mw"
          emit "$cur" "$nd/mw" "$nd/w/i1.ll" || { ladder_reason="step $i (${c}): the mixed tree does not compile ($emit_reason)"; return 1; }
        else
          local pf="$repo_root/$lineage_dir/$arg"
          [[ -f "$pf" ]] || { ladder_reason="step $i (${c}): patch $arg is not in $lineage_dir"; return 1; }
          [[ "$(gate_sha "$pf")" == "$sha" ]] || { ladder_reason="step $i (${c}): $arg hashes to $(gate_sha "$pf" | cut -c1-12), the list says ${sha:0:12}"; return 1; }
          extract "$c" "$nd/patched" self_host stdlib
          ( cd "$nd/patched" && patch -p1 < "$pf" ) > "$nd/patch.log" 2>&1 || { ladder_reason="step $i (${c}): $arg does not apply"; return 1; }
          workdir "$nd/patched" "$nd/pw"
          emit "$cur" "$nd/pw" "$nd/w/i1.ll" || { ladder_reason="step $i (${c}): the patched tree does not compile ($emit_reason)"; return 1; }
        fi
        build_compiler "$nd/w/i1.ll" "$nd/w/i1" || { ladder_reason="step $i (${c}): the intermediate does not build ($(build_reason "$nd/w/i1"))"; return 1; }
        emit "$nd/w/i1" "$nd/w" "$nd/w/s2.ll" || { ladder_reason="step $i (${c}): the intermediate cannot compile the full tree ($emit_reason)"; return 1; }
        build_compiler "$nd/w/s2.ll" "$nd/w/s2" || { ladder_reason="step $i (${c}): stage2 does not build"; return 1; }
        new="$nd/w/s2" ;;
      *) ladder_reason="step $i (${c}): unknown annotation \`$how\`"; return 1 ;;
    esac
    local note=""
    if [[ " $walk_seed_commits " == *" $c "* ]]; then
      seed_at "$c" "$nd/seed.ll"
      emit "$new" "$nd/w" "$nd/w/re.ll" || { ladder_reason="step $i (${c}): the new compiler cannot re-emit its own tree ($emit_reason)"; return 1; }
      if cmp -s "$nd/w/re.ll" "$nd/seed.ll"; then note=" - re-emits its own seed exactly"
      else note=" - an orphan: re-emission differs from its committed seed by $(lines_differing "$nd/w/re.ll" "$nd/seed.ll") lines"; fi
    fi
    echo "     step $i (${c}): ok ($((SECONDS - ts))s)$note"
    [[ "$cur" != "$d/seed" ]] && rm -f "$cur"
    rm -f "$nd/w/"*.ll "$nd/w/plain.s1" "$nd/w/i1"; rm -rf "$nd/mixed" "$nd/patched" "$nd/tree"
    cur="$new"; pc="$c"
  done < "$list"
  (( i > 0 )) || { ladder_reason="the walk list is empty"; return 1; }
  # The last step's tree is the next seed's tree. Its predecessor's
  # emission of it was stage1 of the final link; the final compiler's
  # own re-emission is stage2.
  extract "$next" "$d/ftree" self_host stdlib; workdir "$d/ftree" "$d/fw"
  emit "$cur" "$d/fw" "$d/fw/final.ll" || { ladder_reason="the final compiler cannot re-emit the ${next:0:7} tree ($emit_reason)"; return 1; }
  if cmp -s "$d/fw/final.ll" "$want"; then matched="stage2"; final_ir="$d/fw/final.ll"; stage_note=" ($i steps, $((SECONDS - t0))s)"; return 0; fi
  ladder_reason="the walk ends $(lines_differing "$d/fw/final.ll" "$want") lines from the ${next:0:7} seed"
  return 1
}

# rust-anchor: cargo builds the Rust compiler at `bb730db`; it compiles
# the first seed's tree into stage1 with its own driver; stage1's
# emission must be the first seed. Stage1's own IR is the RUST codegen's
# and is required to differ from the seed - a stage1 that already
# equalled it would mean the two codegens are one.
rust_bin=""
replay_anchor() {  # <next> <dir>
  local next="$1" d="$2" t0=$SECONDS
  mkdir -p "$d/src"
  ( cd "$repo_root" && git archive "$anchor" ) | tar -x -C "$d/src"
  echo "     $(find "$d/src" -name '*.rs' | wc -l | tr -d ' ') Rust files at ${anchor:0:7}; Cargo.lock sha256 $(gate_sha "$d/src/Cargo.lock" | cut -c1-12)"
  export CARGO_TARGET_DIR="$d/target"
  if ! ( cd "$d/src" && cargo build --release --offline -p axiom-cli ) > "$d/cargo.log" 2>&1; then
    if ! ( cd "$d/src" && cargo build --release -p axiom-cli ) > "$d/cargo.log" 2>&1; then
      ladder_reason="cargo could not build the Rust compiler at ${anchor:0:7}: $(grep -m1 -E '^error' "$d/cargo.log" | cut -c1-120)"; return 1
    fi
  fi
  rust_bin="$d/target/release/axiom"
  [[ -x "$rust_bin" ]] || { ladder_reason="cargo built nothing at $rust_bin"; return 1; }
  echo "     the Rust compiler built in $((SECONDS - t0))s ($(wc -c < "$rust_bin" | tr -d ' ') bytes)"
  extract "$next" "$d/tree" self_host stdlib; workdir "$d/tree" "$d/w"
  seed_at "$next" "$d/want.ll"
  anchor_stage1 "$d/tree" "$d/w" || return 1
  ladder "$d/w/stage1" "$d/w" "$d/want.ll" 2 link || return 1
  if cmp -s "$d/w/stage1.ll" "$d/want.ll"; then ladder_reason="the Rust codegen's own IR equals the seed - the anchor is not a second implementation"; return 1; fi
  echo "     the Rust codegen's own IR for stage1 is $(wc -l < "$d/w/stage1.ll" | tr -d ' ') lines against the seed's $(wc -l < "$d/want.ll" | tr -d ' '), as two codegens must differ"
}
anchor_stage1() {  # <tree> <wdir>: the Rust compiler builds stage1 from the tree, with its own llc/cc driver
  local tree="$1" w="$2"
  rm -f "$w/stage1" "$w/stage1.ll"
  ( cd "$w" && AXIOM_STDLIB="$tree/stdlib" "$rust_bin" build --input self_host/main.ax --output stage1 --emit-llvm ) > "$w/rust-build.log" 2>&1 \
    || { ladder_reason="the Rust compiler cannot build stage1: $(grep -m1 -iE 'error' "$w/rust-build.log" | cut -c1-120)"; return 1; }
  [[ -x "$w/stage1" && -s "$w/stage1.ll" ]] || { ladder_reason="the Rust compiler produced no stage1"; return 1; }
}

# ---------------------------------------------------------------------
echo
echo "== $chain: the table is well formed, complete, and ends at the seed in the tree =="
# ---------------------------------------------------------------------
current="$(git -C "$repo_root" log -1 --format=%H -- 'bootstrap/*.ll' 2>/dev/null || true)"
[[ -n "$current" ]] || { echo "FAIL: no commit in history touches bootstrap/*.ll - a shallow clone cannot answer this; the job needs fetch-depth: 0"; exit 1; }
history_commits="$(git -C "$repo_root" log --reverse --format=%H -- 'bootstrap/*.ll')"

# Parallel arrays, because the macOS runner's bash 3.2 has no
# associative ones. `row_seed` holds full hashes; `row_seed_short` what
# the table wrote.
row_seed=(); row_seed_short=(); row_from=(); row_method=(); row_matched=(); row_secs=(); row_detail=(); row_line=()
orphans=(); orphans_short=()
nrows=0

# validate_chain <file>: parses the table into the arrays above and
# reports every structural fault. A function, so the negative probe at
# the end can run it over a broken copy.
validate_chain() {
local chain="$1" lineno=0 line seed_word from_word method want_stage secs seed_full from_full detail kv
local chained covered i h o s sf l listed gits c how arg sha pos prev_pos in_rows in_orphans found
row_seed=(); row_seed_short=(); row_from=(); row_method=(); row_matched=(); row_secs=(); row_detail=(); row_line=()
orphans=(); orphans_short=(); nrows=0
[[ -f "$chain" ]] || { fail "$chain is missing"; return; }

while IFS= read -r line || [[ -n "$line" ]]; do
  lineno=$((lineno + 1))
  [[ -z "${line// }" || "$line" == \#* ]] && continue
  set -- $line
  if [[ "$1" == orphan ]]; then
    seed_full="$(resolve "$2")"
    [[ -n "$seed_full" ]] || { fail "$chain:$lineno: orphan $2 is not a commit"; continue; }
    orphans+=("$seed_full"); orphans_short+=("$2"); continue
  fi
  (( $# >= 5 )) || { fail "$chain:$lineno: a row needs seed, from, method, matched, seconds: \`$line\`"; continue; }
  seed_word="$1"; from_word="$2"; method="$3"; want_stage="$4"; secs="$5"; shift 5
  # `next` names the seed the tree holds whose commit did not exist when
  # `reseed.sh` wrote the row - the same reason `STAMP` records a hash
  # and not a commit. It resolves to the commit that last wrote the
  # six `.ll` files, and only the last row may say it.
  if [[ "$seed_word" == next ]]; then seed_full="$current"; else seed_full="$(resolve "$seed_word")"; fi
  [[ -n "$seed_full" ]] || { fail "$chain:$lineno: seed $seed_word is not a commit"; continue; }
  from_full="$(resolve "$from_word")"
  [[ -n "$from_full" ]] || { fail "$chain:$lineno: reproduced-from $from_word is not a commit"; continue; }
  case "$method" in rust-anchor|seed|mixed-tree|skip|walk|bridge-needed) ;; *) fail "$chain:$lineno: unknown method \`$method\`"; continue ;; esac
  case "$want_stage" in stage1|stage2|-) ;; *) fail "$chain:$lineno: matched must be stage1, stage2 or -, not \`$want_stage\`"; continue ;; esac
  [[ "$secs" =~ ^[0-9]+$ ]] || { fail "$chain:$lineno: seconds must be a number, not \`$secs\`"; continue; }
  detail=""
  for kv in "$@"; do
    case "$kv" in
      skips=*|list=*|generator=*) detail="$detail $kv" ;;
      *) fail "$chain:$lineno: unknown field \`$kv\` (skips=, list=, generator=)"; continue 2 ;;
    esac
  done
  row_seed+=("$seed_full"); row_seed_short+=("$seed_word"); row_from+=("$from_full"); row_method+=("$method")
  row_matched+=("$want_stage"); row_secs+=("$secs"); row_detail+=("$detail"); row_line+=("$lineno")
  nrows=$((nrows + 1))
done < "$chain"
(( nrows > 0 )) || { fail "$chain has no rows"; return; }
ok "$nrows rows and ${#orphans[@]} orphans parsed"

# The first row is the anchor and nothing else is; every other row
# reproduces from the row before it - which is what makes the table a
# chain and not a list of claims.
if [[ "${row_method[0]}" == rust-anchor && "${row_from[0]}" == "$anchor" ]]; then
  ok "row 1 is the Rust anchor at ${anchor:0:7}"
else
  fail "row 1 must be \`<first seed> ${anchor:0:7} rust-anchor ...\`; it is \`${row_seed_short[0]} ${row_from[0]:0:7} ${row_method[0]}\`"
fi
chained=1
for ((i = 1; i < nrows; i++)); do
  [[ "${row_method[i]}" != rust-anchor ]] || { fail "$chain:${row_line[i]}: only the first row may be the anchor"; chained=0; }
  if [[ "${row_from[i]}" != "${row_seed[i-1]}" ]]; then
    fail "$chain:${row_line[i]}: ${row_seed_short[i]} reproduces from ${row_from[i]:0:7}, but the row before it is ${row_seed_short[i-1]}"
    chained=0
  fi
done
(( chained )) && ok "every row reproduces from the row before it"

# Every commit that ever wrote the seed is either a row or a declared
# orphan, in history order, and the last row is the seed in the tree.
covered=1
while IFS= read -r h; do
  in_rows=0; for ((i = 0; i < nrows; i++)); do [[ "${row_seed[i]}" == "$h" ]] && in_rows=1; done
  in_orphans=0; for o in "${orphans[@]:-}"; do [[ "$o" == "$h" ]] && in_orphans=1; done
  if (( in_rows + in_orphans == 0 )); then fail "${h:0:7} wrote the seed and $chain has neither a row nor an orphan line for it"; covered=0; fi
  (( in_rows + in_orphans == 2 )) && { fail "${h:0:7} is both a row and an orphan"; covered=0; }
done <<< "$history_commits"
for ((i = 0; i < nrows; i++)); do
  grep -q "^${row_seed[i]}\$" <<< "$history_commits" || { fail "$chain:${row_line[i]}: ${row_seed_short[i]} never wrote bootstrap/*.ll"; covered=0; }
done
for o in "${orphans[@]:-}"; do
  [[ -z "$o" ]] && continue
  grep -q "^$o\$" <<< "$history_commits" || { fail "orphan ${o:0:7} never wrote bootstrap/*.ll"; covered=0; }
done
# Order: the rows must appear in history order.
prev_pos=-1
for ((i = 0; i < nrows; i++)); do
  pos="$(grep -n "^${row_seed[i]}\$" <<< "$history_commits" | cut -d: -f1)"
  [[ -n "$pos" ]] || continue
  (( pos > prev_pos )) || { fail "$chain:${row_line[i]}: ${row_seed_short[i]} is out of history order"; covered=0; }
  prev_pos=$pos
done
(( covered )) && ok "the $(grep -c . <<< "$history_commits") commits that wrote the seed are $nrows rows and ${#orphans[@]} orphans, in history order"

if [[ "${row_seed[nrows-1]}" == "$current" ]]; then
  ok "the last row is ${current:0:7}, the commit that wrote the seed in the tree"
else
  fail "the seed in the tree was written by ${current:0:7}, and the last row of $chain is ${row_seed_short[nrows-1]}"
  echo "      A reseed landed without its row. \`reseed.sh\` appends one; if the seed was"
  echo "      generated another way, replay the link by hand and write what reproduced it."
fi
# A skip row names an orphan that lies between its two ends; a walk
# row names a list that exists and equals git's list of the commits
# between its two ends that touched the sources.
for ((i = 0; i < nrows; i++)); do
  case "${row_method[i]}" in
    skip)
      s="$(detail_of "${row_detail[i]}" skips)"; sf="$(resolve "$s")"
      [[ -n "$s" ]] || { fail "$chain:${row_line[i]}: a skip row needs skips=<orphan>"; continue; }
      found=0; for o in "${orphans[@]:-}"; do [[ "$o" == "$sf" ]] && found=1; done
      (( found )) || { fail "$chain:${row_line[i]}: skips=$s is not a declared orphan"; continue; }
      git -C "$repo_root" merge-base --is-ancestor "${row_from[i]}" "$sf" && git -C "$repo_root" merge-base --is-ancestor "$sf" "${row_seed[i]}" \
        || { fail "$chain:${row_line[i]}: $s is not between ${row_from[i]:0:7} and ${row_seed_short[i]}"; continue; }
      ok "row ${row_seed_short[i]} skips $s, which lies between its ends" ;;
    walk)
      l="$(detail_of "${row_detail[i]}" list)"
      [[ -n "$l" && -f "$repo_root/bootstrap/$l" ]] || { fail "$chain:${row_line[i]}: a walk row needs list=<file under bootstrap/>"; continue; }
      listed="$(grep -vE '^[[:space:]]*(#|$)' "$repo_root/bootstrap/$l" | awk '{print $1}')"
      gits="$(git -C "$repo_root" log --reverse --format=%h "${row_from[i]}..${row_seed[i]}" -- self_host stdlib)"
      if [[ "$listed" == "$gits" ]]; then
        ok "row ${row_seed_short[i]} walks the $(grep -c . <<< "$listed") commits between ${row_from[i]:0:7} and ${row_seed_short[i]} that touched the sources - the list is git's"
      else
        fail "$chain:${row_line[i]}: bootstrap/$l is not the list of source commits between ${row_from[i]:0:7} and ${row_seed_short[i]}"
        diff <(printf '%s\n' "$gits") <(printf '%s\n' "$listed") | head -6 | sed 's/^/       /'
      fi
      while read -r c how arg sha; do
        [[ -z "$c" || "$c" == \#* || -z "${how:-}" ]] && continue
        case "$how" in
          mixed-tree) ;;
          patch) [[ -n "${arg:-}" && -n "${sha:-}" ]] || fail "bootstrap/$l: \`$c patch\` needs a file and its sha256"
                 [[ -f "$repo_root/$lineage_dir/$arg" ]] || fail "bootstrap/$l: $lineage_dir/$arg does not exist"
                 [[ "$(gate_sha "$repo_root/$lineage_dir/$arg" 2>/dev/null)" == "${sha:-}" ]] || fail "bootstrap/$l: $arg does not hash to ${sha:0:12}" ;;
          *) fail "bootstrap/$l: unknown step annotation \`$how\` on $c" ;;
        esac
      done < "$repo_root/bootstrap/$l" ;;
    bridge-needed)
      fail "$chain:${row_line[i]}: the ${row_seed_short[i]} seed was generated by a compiler that is not the ${row_from[i]:0:7} seed's descendant (${row_detail[i]# })"
      echo "      That link is not replayable as written. Certify it: try \`mixed-tree\` (the previous"
      echo "      seed over self_host@new + stdlib@previous), or a \`walk\` over the commits between,"
      echo "      and replace this row with the method that reproduces the seed." ;;
  esac
done
}
detail_of() {  # <detail> <key> -> value
  local kv; for kv in $1; do [[ "$kv" == "$2="* ]] && { printf '%s' "${kv#*=}"; return; }; done
}
validate_chain "$chain"
(( nrows > 0 )) || { echo "check-seed-lineage: $chain has no rows to replay"; exit 1; }

# ---------------------------------------------------------------------
echo
echo "== $checkpoint: the prefix it certifies, re-derived from $chain =="
# ---------------------------------------------------------------------
# WHY THERE IS A CHECKPOINT. `--full` re-derives the whole chain from
# the Rust anchor, and its cost is linear in the number of reseeds this
# project has EVER done - a prefix whose answer cannot change, paid for
# again every night, forever. The default run answered that by replaying
# the NEWEST row and saying nothing at all about the rows before it:
# cheap, and silent about thirteen of the fourteen links.
#
# `bootstrap/CHAIN.checkpoint` is the record that default run was
# missing. It names a PREFIX of the table and the digest of exactly that
# prefix, and the digest is RECOMPUTED here, from the table as it stands
# right now, on every single run. A row inside the certified prefix that
# moved by one byte - a `matched` corrected, an orphan's prose reworded,
# a short hash that now resolves to a different commit, a walk list
# edited, a seed blob that is no longer the blob replayed - moves the
# digest; and a digest that does not match certifies nothing. The
# checkpoint is then VOID: the gate replays every row anyway and goes
# red until the prefix is blessed again. Editing an old row cannot
# shrink the work. It can only enlarge it.
#
# WHAT THE CHECKPOINT IS NOT, stated here so nobody reads more into the
# file than it says. It is not a signature. Whoever can edit a row can
# also recompute a digest and rewrite this file, and no arithmetic in
# this gate can stop them. What it costs them is that the edit and the
# re-blessing become ONE REVIEWABLE DIFF that says, in the tree, "this
# change re-certified the lineage" - instead of a one-character change
# to a table nothing re-derives. The property is tamper-EVIDENT, to a
# reader and to the nightly `--full` that re-derives every row from
# `bb730db` inside a day. That is the standard `bootstrap/STAMP` is
# already held to.
#
# THE NEWEST ROW IS NEVER CERTIFIED, and the replay range below is
# clamped so at least one link is replayed on every run. Blessing stops
# before any row written `next` - the row whose meaning moves as history
# does - so the link a push actually ADDS is replayed on that push,
# checkpoint or no checkpoint.

# seed_blobs <commit> -> the git object ids of every seed that commit
# carries, sorted. The row names a commit and the replay compares the
# HOST's seed at it; binding all of them makes the digest one statement
# about the same bytes on every host, rather than a host-shaped one that
# a second host would have to re-derive.
seed_blobs() {
  git -C "$repo_root" ls-tree "$1" bootstrap/ 2>/dev/null \
    | grep -E 'axiom-[^ /]*\.ll$' | awk '{print $3}' | LC_ALL=C sort | tr '\n' ' '
}

# checkpoint_material <chainfile> <k> -> on stdout, the canonical text
# the digest is taken over; non-zero and a reason on stderr when the
# first <k> rows cannot BE a certified prefix.
#
# Every line of it is something a replay of those rows consumed:
#   - the row and orphan LINES verbatim, so any edit at all moves it;
#   - each row's words RESOLVED to full hashes, so a table whose
#     `2549cfa` begins naming a different commit is a different table
#     even though its own bytes did not change;
#   - the git object id of every seed those commits carry, which is what
#     the replay compared against;
#   - the sha256 of every walk list and every patch file a covered row
#     names - working-tree files that no commit hash binds;
#   - the anchor, and the row count, so a prefix cannot be re-read as a
#     shorter or a longer one.
#
# What it deliberately does NOT cover: this script. Binding the
# checkpoint to the gate's own bytes would void it on every comment
# edit to a 900-line file, and a forty-minute re-blessing that fires on
# a typo is a re-blessing nobody reads - the ritual this gate exists to
# refuse. The gate's own body is checked by its own probes, which run
# on every invocation including this one.
checkpoint_material() {
  local cf="$1" k="$2" line n=0 fseed ffrom l c how parg psha kv
  printf 'axiom-chain-checkpoint-v1\n'
  printf 'anchor %s\n' "$anchor"
  printf 'rows %s\n' "$k"
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "${line// }" || "$line" == \#* ]] && continue
    set -- $line
    if [[ "$1" == orphan ]]; then
      (( n >= k )) && continue
      printf 'orphan-line %s\n' "$line"
      printf 'orphan-commit %s\n' "$(resolve "${2:-}")"
      continue
    fi
    (( n >= k )) && break
    n=$((n + 1))
    if [[ "$1" == next ]]; then
      echo "checkpoint: row $n is written \`next\`, which names no commit until one exists - a prefix cannot cover it" >&2
      return 1
    fi
    fseed="$(resolve "$1")"; ffrom="$(resolve "${2:-}")"
    [[ -n "$fseed" && -n "$ffrom" ]] || { echo "checkpoint: row $n names a commit that does not resolve" >&2; return 1; }
    printf 'row %s %s\n' "$n" "$line"
    printf 'row-seed %s %s %s\n' "$n" "$fseed" "$(seed_blobs "$fseed")"
    printf 'row-from %s %s\n' "$n" "$ffrom"
    for kv in "$@"; do
      case "$kv" in
        list=*)
          l="${kv#list=}"
          [[ -f "$repo_root/bootstrap/$l" ]] || { echo "checkpoint: row $n names bootstrap/$l, which is not in the tree" >&2; return 1; }
          printf 'row-list %s bootstrap/%s %s\n' "$n" "$l" "$(gate_sha "$repo_root/bootstrap/$l")"
          while read -r c how parg psha; do
            [[ -z "$c" || "$c" == \#* || "${how:-}" != patch ]] && continue
            [[ -f "$repo_root/$lineage_dir/${parg:-}" ]] || { echo "checkpoint: row $n's list names $lineage_dir/${parg:-}, which is not in the tree" >&2; return 1; }
            printf 'row-patch %s %s %s\n' "$n" "$parg" "$(gate_sha "$repo_root/$lineage_dir/$parg")"
          done < "$repo_root/bootstrap/$l" ;;
      esac
    done
  done < "$cf"
  (( n == k )) || { echo "checkpoint: $cf holds $n rows, and a prefix of $k needs $k" >&2; return 1; }
}

checkpoint_digest() {  # <chainfile> <k> -> sha256 of the material
  local m; m="$(checkpoint_material "$1" "$2")" || return 1
  printf '%s\n' "$m" | gate_sha
}

# checkpoint_read <file>: the five fields, or `ck_bad` and non-zero.
ck_rows=0; ck_digest=""; ck_through=""; ck_blessed=""; ck_host=""; ck_bad=""
checkpoint_read() {
  local f="$1"
  ck_rows=""; ck_digest=""; ck_through=""; ck_blessed=""; ck_host=""; ck_bad=""
  ck_rows="$(sed -n 's/^Rows covered:[[:space:]]*//p'   "$f" | head -1 | tr -d '[:space:]')"
  ck_digest="$(sed -n 's/^Prefix digest:[[:space:]]*//p' "$f" | head -1 | tr -d '[:space:]')"
  ck_through="$(sed -n 's/^Through seed:[[:space:]]*//p' "$f" | head -1 | tr -d '[:space:]')"
  ck_blessed="$(sed -n 's/^Blessed:[[:space:]]*//p'      "$f" | head -1)"
  ck_host="$(sed -n 's/^Replayed on:[[:space:]]*//p'     "$f" | head -1)"
  # A field that is missing, empty or the wrong shape is a REFUSAL and
  # never a "no checkpoint here": a file nobody can parse is exactly the
  # file an attacker would leave behind, and treating it as absence
  # would hand it the silent fast path it was after.
  [[ "$ck_rows" =~ ^[0-9]+$ ]] || { ck_bad="\`Rows covered:\` is \`${ck_rows:-<missing>}\`, which is not a number"; return 1; }
  (( ck_rows >= 1 ))           || { ck_bad="it covers $ck_rows rows, which certifies nothing"; return 1; }
  [[ "$ck_digest" =~ ^[0-9a-f]{64}$ ]] || { ck_bad="\`Prefix digest:\` is \`${ck_digest:-<missing>}\`, which is not a sha256"; return 1; }
  [[ -n "$ck_through" ]]       || { ck_bad="\`Through seed:\` is missing"; return 1; }
  return 0
}

# checkpoint_check <ckfile> <chainfile>: the whole decision, as a pure
# function over two files, so the probes at the end can ask it about
# files that are MEANT to be refused. Sets `ck_state` to absent, valid
# or void, `ck_why` and `ck_covers`; prints nothing and counts nothing.
ck_state=absent; ck_why=""; ck_covers=0; ck_got=""
checkpoint_check() {
  local f="$1" cf="$2" got
  ck_state=absent; ck_why=""; ck_covers=0; ck_got=""
  [[ -f "$f" ]] || { ck_why="$f is not in the tree"; return; }
  ck_state=void
  checkpoint_read "$f" || { ck_why="it cannot be read: $ck_bad"; return; }
  (( ck_rows <= nrows )) || { ck_why="it certifies $ck_rows rows and the table now holds $nrows - rows were deleted"; return; }
  [[ "${row_seed_short[ck_rows-1]}" == "$ck_through" ]] \
    || { ck_why="it says its last covered row is \`$ck_through\`; row $ck_rows of the table is \`${row_seed_short[ck_rows-1]}\`"; return; }
  got="$(checkpoint_digest "$cf" "$ck_rows" 2>/dev/null)" \
    || { ck_why="the first $ck_rows rows of $cf cannot be digested"; return; }
  ck_got="$got"
  [[ "$got" == "$ck_digest" ]] \
    || { ck_why="the first $ck_rows rows now digest to ${got:0:16} and it certifies ${ck_digest:0:16}"; return; }
  ck_state=valid; ck_covers=$ck_rows
}

checkpoint_check "$checkpoint" "$chain"
checkpoint_state="$ck_state"; checkpoint_covers=$ck_covers
case "$checkpoint_state" in
  valid)
    ok "$checkpoint certifies rows 1..$ck_covers (through ${ck_through}), and those rows digest to ${ck_got:0:16} here and now"
    echo "     blessed ${ck_blessed:-<unrecorded>}"
    if [[ -n "$ck_host" && "$ck_host" != "$target"* ]]; then
      echo "     replayed on $ck_host, not this host's $target: the covered rows' $target"
      echo "     seeds are bound by object id above but were not run here. The nightly"
      echo "     \`--full\` replays them on the runner's own target."
    fi ;;
  absent)
    skip "no $checkpoint: rows 1..$((nrows - 1)) are not replayed on this run, and nothing in the tree records that they ever were"
    echo "      Bless one:  AXIOM_BLESS=1 $0 --full" ;;
  void)
    fail "$checkpoint is VOID and certifies nothing: $ck_why"
    echo "      The prefix it names has moved, so it is not a statement about this"
    echo "      table. Replaying EVERY row instead - a checkpoint cannot shrink the"
    echo "      work by being edited - and staying red until the prefix is blessed"
    echo "      again:  AXIOM_BLESS=1 $0 --full"
    full=1 ;;
esac

# ---------------------------------------------------------------------
echo
echo "== STAMP names the tree of ${current:0:7}, and the seed in the tree is that commit's =="
# ---------------------------------------------------------------------
# Exactly `check-seed-provenance.sh`'s check: the tree compiled below
# is the EXTRACTED tree at the seed commit, and STAMP must describe it,
# or the replay would compare the right bytes against the wrong claim.
want_stamp="$(sed -n 's/^Source stamp: *//p' bootstrap/STAMP | tr -d '[:space:]')"
extract "$current" "$work/current" self_host stdlib
got_stamp="$(gate_seed_source_stamp "$work/current")"
if [[ "$got_stamp" == "$want_stamp" ]]; then ok "bootstrap/STAMP hashes ${current:0:7}'s sources (${got_stamp:0:12})"; else fail "bootstrap/STAMP (${want_stamp:0:12}) does not describe ${current:0:7}'s sources (${got_stamp:0:12})"; fi
if seed_at "$current" "$work/current-seed.ll" && cmp -s "$work/current-seed.ll" "bootstrap/axiom-$target.ll"; then
  ok "bootstrap/axiom-$target.ll is byte-identical to ${current:0:7}'s"
else
  fail "bootstrap/axiom-$target.ll is not what ${current:0:7} committed - the tree's seed moved without a commit"
fi

# ---------------------------------------------------------------------
# The replays.
# ---------------------------------------------------------------------
# WHERE THE REPLAY STARTS. `--full` starts at the anchor. A valid
# checkpoint starts after the prefix it certifies. Anything else starts
# at the newest row - which is what this gate did before there were
# checkpoints, and is the floor it never goes below. The range is
# CLAMPED so at least one link is replayed on every run whatever a
# checkpoint says, and that is not politeness: the negative probes below
# compare against an emission this run produced, and a run that replays
# nothing has nothing to probe with.
if (( full )); then
  first=0
elif [[ "$checkpoint_state" == valid ]]; then
  first=$checkpoint_covers
  (( first > nrows - 1 )) && first=$((nrows - 1))
else
  first=$((nrows - 1))
fi
replayed=0; last_final_ir=""; last_want=""; last_dir=""
# Which rows THIS process replayed. A blessing is over rows derived
# here, so every row a checkpoint let it skip stays `0`.
row_replayed=(); for ((i = 0; i < nrows; i++)); do row_replayed[i]=0; done
if (( first > 0 )); then
  echo
  if [[ "$checkpoint_state" == valid ]]; then
    echo "     rows 1..$first are not replayed here: $checkpoint certifies them, and the"
    echo "     digest of exactly those rows was recomputed from $chain above."
  else
    echo "     rows 1..$first are not replayed here and nothing certifies them; this is the"
    echo "     newest-link-only run. \`--full\` (the nightly) replays them all."
  fi
fi
for ((i = first; i < nrows; i++)); do
  seed="${row_seed[i]}"; from="${row_from[i]}"; method="${row_method[i]}"
  echo
  echo "== row $((i + 1))/$nrows: ${row_seed_short[i]} from ${from:0:7} by $method, recorded ${row_matched[i]} in ${row_secs[i]}s =="
  d="$work/row$((i + 1))"; mkdir -p "$d"
  matched=""; ladder_reason=""; stage_note=""; final_ir=""
  if [[ "$method" != rust-anchor ]] && ! has_seed "$from"; then skip "no $target seed at ${from:0:7}; this host cannot build that compiler"; continue; fi
  if ! has_seed "$seed"; then skip "no $target seed at ${seed:0:7}; nothing for this host to compare"; continue; fi
  t0=$SECONDS
  case "$method" in
    rust-anchor)
      if (( ! have_cargo )); then
        skip "cargo is not on PATH; the anchor row builds the Rust compiler at ${anchor:0:7} and needs it"
        echo "      (the chain from the first seed onward is still replayed; the root is not)"
        continue
      fi
      replay_anchor "$seed" "$d"; rc=$? ;;
    seed)       replay_seed "$from" "$seed" "$d"; rc=$? ;;
    mixed-tree) replay_mixed "$from" "$seed" "$d"; rc=$? ;;
    skip)       replay_skip "$from" "$seed" "$(resolve "$(detail_of "${row_detail[i]}" skips)")" "$d"; rc=$? ;;
    walk)       walk_seed_commits="$(git -C "$repo_root" log --format=%h -- 'bootstrap/*.ll' | tr '\n' ' ')"
                replay_walk "$from" "$seed" "$repo_root/bootstrap/$(detail_of "${row_detail[i]}" list)" "$d"; rc=$? ;;
    bridge-needed) continue ;;
  esac
  secs=$((SECONDS - t0))
  if (( rc != 0 )); then
    fail "${row_seed_short[i]} does not reproduce from ${from:0:7} by $method: $ladder_reason (${secs}s)"
    continue
  fi
  if [[ "$matched" == "${row_matched[i]}" ]]; then
    ok "${row_seed_short[i]} reproduces from ${from:0:7} at $matched$stage_note, ${secs}s"
    row_replayed[i]=1
  else
    fail "${row_seed_short[i]} reproduces from ${from:0:7}, but at $matched where the row says ${row_matched[i]} - correct the row"
  fi
  replayed=$((replayed + 1)); last_final_ir="$final_ir"; last_want="$d/want.ll"; last_dir="$d"
  # Keep the last row's artifacts for the probes; drop the rest.
  (( i < nrows - 1 )) && [[ "$method" != rust-anchor ]] && rm -rf "$d"
done

# ---------------------------------------------------------------------
echo
echo "== negative probes =="
# ---------------------------------------------------------------------
if [[ -n "$last_final_ir" && -f "$last_final_ir" ]]; then
  # (a) One byte flipped in a copy of the seed must fail the very
  # comparison that just passed. The copy is asserted to differ from
  # the original first, so a `cp` that failed cannot pass the probe.
  flipped="$work/flipped.ll"; cp "$last_want" "$flipped"
  at=$(( $(wc -c < "$flipped") / 2 ))
  printf 'X' | dd of="$flipped" bs=1 seek="$at" conv=notrunc 2>/dev/null
  if cmp -s "$flipped" "$last_want"; then
    fail "the probe's flip at byte $at did not change the copy"
  elif cmp -s "$last_final_ir" "$flipped"; then
    fail "a seed with one byte flipped still compares equal to the replay - the comparison is not byte-level"
  else
    ok "one byte flipped at offset $at in a copy of the seed is refused ($(cmp "$last_final_ir" "$flipped" 2>&1 | sed 's/.*differ: //'))"
  fi
else
  fail "no replay produced an emission, so the flipped-byte probe has nothing to run against"
fi

# (b) A row re-pointed at a different predecessor must go red, and it
# does so twice over. The TABLE refuses it: every row reproduces from
# the row before it, so the newest row naming the seed two rows back
# breaks the chain, and the validation is run over exactly that copy.
# The REPLAY refuses a predecessor that cannot reproduce the seed: the
# newest tree compiled by the FIRST committed seed, which is the
# predecessor furthest from it.
#
# What the replay does NOT refuse, measured while writing this and
# worth knowing: a NEARBY seed that can compile the tree reproduces it
# at stage2 too, because stage2 is the tree's own fixpoint and any
# working compiler reaches it. That is the same fact as
# `check-seed-provenance.sh`'s, and it is why stage1 is the stronger
# row - the previous seed's DIRECT emission - and why the table's
# structure, not the replay alone, is what names a predecessor.
i=$((nrows - 1)); seed="${row_seed[i]}"; method="${row_method[i]}"
if (( nrows >= 3 )); then
  wrong="${row_seed[i-2]}"; edited="$work/CHAIN.edited"
  awk -v ln="${row_line[i]}" -v w="${wrong:0:7}" 'NR == ln { $2 = w } { print }' "$chain" > "$edited"
  if cmp -s "$edited" "$chain"; then
    fail "the probe's edit to the newest row's predecessor was not applied"
  else
    probe_mode=1; probe_failed=0; probe_first=""
    validate_chain "$edited"
    probe_mode=0
    if (( probe_failed > 0 )); then
      ok "$chain with ${row_seed_short[i]} re-pointed at ${wrong:0:7} is refused: $probe_first"
    else
      fail "$chain with ${row_seed_short[i]} re-pointed at ${wrong:0:7} passed validation"
    fi
    validate_chain "$chain" > /dev/null   # the arrays, restored
  fi
else
  skip "the re-pointed-row probe needs three rows"
fi
first_seed_commit="${row_seed[0]}"
if [[ "$method" == seed || "$method" == skip || "$method" == mixed-tree ]] && has_seed "$first_seed_commit" && has_seed "$seed" && [[ "$first_seed_commit" != "${row_from[i]}" ]]; then
  d="$work/wrong-from"; mkdir -p "$d"
  matched=""; ladder_reason=""; t0=$SECONDS
  replay_seed "$first_seed_commit" "$seed" "$d"; rc=$?
  if (( rc == 0 )); then
    fail "${row_seed_short[i]} reproduces from the FIRST seed ${first_seed_commit:0:7} at $matched - the newest tree compiles under the oldest compiler, so the replay alone cannot name a predecessor; look before trusting the row's \`from\`"
  else
    ok "${row_seed_short[i]} does not reproduce from the first seed ${first_seed_commit:0:7}: $ladder_reason ($((SECONDS - t0))s)"
  fi
  rm -rf "$d"
else
  skip "the wrong-predecessor replay needs a seed, skip or mixed-tree newest row and a first seed this host can build"
fi

# (c), (d) The anchor's probes, under --full with cargo, on the Rust
# compiler just built.
if (( full && have_cargo )) && [[ -n "$rust_bin" && -x "$rust_bin" ]]; then
  ad="$work/row1"; first_seed="${row_seed[0]}"
  # (d) One byte of the `.ax` tree the anchor compiles must move the
  # emission - otherwise the anchor is satisfied by an emitter that
  # ignores its input. `stdlib/Json.ax` asks whether a byte is `e`
  # (101); ask about `f` (102) in a copy. The anchor line is asserted
  # present before the edit: the first attempt at this probe perturbed
  # a file that did not exist at that commit and "passed".
  pd="$work/anchor-ax-probe"; extract "$first_seed" "$pd/tree" self_host stdlib
  victim="$pd/tree/stdlib/Json.ax"
  if [[ "$(grep -c '(== (strByte src p) 101)' "$victim" 2>/dev/null)" != 1 ]]; then
    fail "the .ax probe's anchor \`(== (strByte src p) 101)\` is not exactly once in stdlib/Json.ax at ${first_seed:0:7} - re-derive it"
  else
    sed -i.bak 's/(== (strByte src p) 101)/(== (strByte src p) 102)/' "$victim"; rm -f "$victim.bak"
    workdir "$pd/tree" "$pd/w"
    if ! anchor_stage1 "$pd/tree" "$pd/w"; then fail "the .ax probe's tree does not build through the Rust compiler: $ladder_reason"
    elif ! emit "$pd/w/stage1" "$pd/w" "$pd/w/out.ll"; then fail "the .ax probe emitted nothing to compare ($emit_reason)"
    elif cmp -s "$pd/w/out.ll" "$ad/want.ll"; then fail "one byte of stdlib/Json.ax changed and the anchor's emission did not move"
    else ok "one byte of the first seed's stdlib/Json.ax moves the anchor's emission by $(lines_differing "$pd/w/out.ll" "$ad/want.ll") lines"; fi
  fi
  # (c) One byte of the Rust anchor's codegen must stop the
  # reproduction: `icmp sgt` becomes `icmp sge`, so every `>` the
  # compiler is built with compiles as `>=`. The rebuilt stage1 is a
  # different program, and whatever it does - a different emission, a
  # crash, or a loop that never ends - is not the seed. The emission is
  # bounded by a watchdog because that last outcome is a real one.
  src="$ad/src/axiom-codegen/src/lib.rs"
  if [[ "$(grep -c 'icmp sgt i64' "$src" 2>/dev/null)" != 1 ]]; then
    fail "the Rust probe's anchor \`icmp sgt i64\` is not exactly once in axiom-codegen/src/lib.rs at ${anchor:0:7} - re-derive it"
  else
    sed -i.bak 's/icmp sgt i64/icmp sge i64/' "$src"; rm -f "$src.bak"
    grep -q 'icmp sge i64' "$src" || fail "the Rust probe's edit was not applied"
    if ! ( cd "$ad/src" && CARGO_TARGET_DIR="$ad/target" cargo build --release --offline -p axiom-cli ) > "$ad/cargo-probe.log" 2>&1 \
       && ! ( cd "$ad/src" && CARGO_TARGET_DIR="$ad/target" cargo build --release -p axiom-cli ) > "$ad/cargo-probe.log" 2>&1; then
      fail "the patched Rust compiler does not build: $(grep -m1 -E '^error' "$ad/cargo-probe.log" | cut -c1-120)"
    else
      rd="$work/anchor-rs-probe"; extract "$first_seed" "$rd/tree" self_host stdlib; workdir "$rd/tree" "$rd/w"
      outcome=""
      if ! anchor_stage1 "$rd/tree" "$rd/w"; then outcome="the patched anchor cannot build stage1 ($ladder_reason)"
      else
        # The watchdog: 600 s, then the emission is killed and counted
        # as not produced.
        ( cd "$rd/w" && AXIOM_STDLIB="$rd/tree/stdlib" ./stage1 in.ax "$target" > "$rd/w/out.ll" 2> "$rd/w/out.err" ) &
        wpid=$!; waited=0
        while kill -0 "$wpid" 2>/dev/null && (( waited < 600 )); do sleep 1; waited=$((waited + 1)); done
        if kill -0 "$wpid" 2>/dev/null; then kill "$wpid" 2>/dev/null; wait "$wpid" 2>/dev/null; outcome="its stage1 ran for ${waited}s without finishing and was killed"
        else
          wait "$wpid"; wrc=$?
          if ! grep -q '^target triple' "$rd/w/out.ll" || (( $(wc -l < "$rd/w/out.ll") <= 10000 )); then outcome="its stage1 produced no emission (rc=$wrc, $(wc -l < "$rd/w/out.ll" | tr -d ' ') lines)"
          elif cmp -s "$rd/w/out.ll" "$ad/want.ll"; then outcome=""
          else outcome="its stage1's emission differs from the seed by $(lines_differing "$rd/w/out.ll" "$ad/want.ll") lines"; fi
        fi
      fi
      if [[ -z "$outcome" ]]; then fail "the Rust anchor with \`sgt\` compiled as \`sge\` STILL reproduces the first seed - the anchor's behaviour does not reach the compared bytes"
      else ok "one byte changed in the Rust anchor's codegen stops the reproduction: $outcome"; fi
    fi
  fi
elif (( full )); then
  skip "the anchor's two probes need cargo"
fi

# (e) The checkpoint's own ablations, over a SYNTHETIC checkpoint built
# here from the table as it stands. Synthetic rather than the tree's, so
# they run on a checkout that carries no checkpoint at all and on one
# whose checkpoint is void - the two states in which a mechanism's
# self-test is most worth having - and so they exercise exactly the
# `checkpoint_read`/`checkpoint_digest`/`checkpoint_check` path the fast
# path above rests on rather than a copy of it.
#
# Each is a real refusal by that path, not an assertion about it: a
# probe here that "passes" by not being reached is the defect this
# repository names most often.
if (( nrows >= 3 )); then
  pk=$((nrows - 1))
  if ! pdig="$(checkpoint_digest "$chain" "$pk" 2>/dev/null)"; then
    fail "the first $pk rows of $chain cannot be digested, so the checkpoint probes have nothing to run against"
  else
    pck="$work/CHAIN.checkpoint.probe"
    write_probe_ck() {  # <file> <rows> <through> <digest>
      printf 'Rows covered:          %s\nThrough seed:          %s\nPrefix digest:         %s\nBlessed:               probe\nReplayed on:           %s\n' \
        "$2" "$3" "$4" "$target" > "$1"
    }
    write_probe_ck "$pck" "$pk" "${row_seed_short[pk-1]}" "$pdig"

    # (e1) The mechanism is not vacuous in the passing direction: a
    # checkpoint over this table, against this table, is VALID. Without
    # this arm every refusal below is satisfied by a verifier that
    # refuses everything.
    checkpoint_check "$pck" "$chain"
    if [[ "$ck_state" == valid && "$ck_covers" == "$pk" ]]; then
      ok "a checkpoint over rows 1..$pk of $chain verifies against $chain (digest ${pdig:0:16})"
    else
      fail "a checkpoint this gate just wrote over rows 1..$pk does not verify: $ck_why"
    fi

    # (e2) THE ONE THAT MATTERS. An edit to a row INSIDE the certified
    # prefix must VOID it - not be skipped, not be trusted. Row 2's
    # `matched` is changed to the other stage in a copy: a row that
    # parses, chains, covers and orders exactly as before, and lies
    # about which emission equalled the seed. The copy is asserted to
    # differ from the original first, so an `awk` that changed nothing
    # cannot pass this.
    ed="$work/CHAIN.old-row-edited"
    awk -v ln="${row_line[1]}" 'NR == ln { if ($4 == "stage1") $4 = "stage2"; else $4 = "stage1" } { print }' "$chain" > "$ed"
    if cmp -s "$ed" "$chain"; then
      fail "the probe's edit to row 2's \`matched\` was not applied"
    else
      checkpoint_check "$pck" "$ed"
      if [[ "$ck_state" == void ]]; then
        ok "row 2's \`matched\` changed inside the certified prefix VOIDS the checkpoint: $ck_why"
      else
        fail "row 2 edited inside the certified prefix and the checkpoint still reads \`$ck_state\` - an old row can be edited without enlarging the work"
      fi
    fi

    # (e3) A checkpoint whose digest was tampered with - one hex digit -
    # is refused. It parses; it certifies a prefix that does not exist.
    bad="$work/CHAIN.checkpoint.badhash"
    # One hex digit, changed in bash rather than through `sed`: BSD sed
    # has no `t` without a label and the first draft of this line failed
    # SILENTLY there, leaving an EMPTY digest - so the probe still went
    # green, refusing the file for having no digest at all rather than
    # for having a wrong one. A probe that passes for the wrong reason
    # is the defect this section exists to catch.
    # The FIRST digit, not the last: every refusal here prints the two
    # digests truncated to sixteen characters, and a change in the
    # sixty-fourth would print a refusal whose two sides read identical.
    tampered="$( [[ "${pdig:0:1}" == a ]] && printf b || printf a )${pdig:1}"
    if [[ "$tampered" == "$pdig" ]]; then
      fail "the probe's one-digit change to the digest was not applied"
    else
      write_probe_ck "$bad" "$pk" "${row_seed_short[pk-1]}" "$tampered"
      checkpoint_check "$bad" "$chain"
      if [[ "$ck_state" == void ]]; then
        ok "a checkpoint with one digit of its digest changed is refused: $ck_why"
      else
        fail "a checkpoint with a tampered digest reads \`$ck_state\`"
      fi
    fi

    # (e4) A TRUNCATED checkpoint is refused and NOT read as absence.
    # The distinction is the whole safety of the fast path: "absent"
    # takes the old default and says so, "void" replays everything and
    # goes red, and a file nobody can parse must be the second.
    trunc="$work/CHAIN.checkpoint.truncated"
    grep -v '^Prefix digest:' "$pck" > "$trunc"
    checkpoint_check "$trunc" "$chain"
    if [[ "$ck_state" == void ]]; then
      ok "a checkpoint with its digest line deleted is refused rather than read as absence: $ck_why"
    else
      fail "a checkpoint with no digest line reads \`$ck_state\`, not \`void\`"
    fi

    # (e5) A checkpoint that claims MORE rows than the table holds -
    # the shape a deleted row leaves behind - is refused.
    over="$work/CHAIN.checkpoint.overreach"
    write_probe_ck "$over" "$((nrows + 1))" "${row_seed_short[pk-1]}" "$pdig"
    checkpoint_check "$over" "$chain"
    if [[ "$ck_state" == void ]]; then
      ok "a checkpoint claiming $((nrows + 1)) rows over a table of $nrows is refused: $ck_why"
    else
      fail "a checkpoint claiming more rows than the table holds reads \`$ck_state\`"
    fi
  fi
else
  skip "the checkpoint probes need three rows"
fi

# ---------------------------------------------------------------------
# Blessing. A gate that writes its own trust anchor when it passes
# proves nothing, so this never happens as a side effect of a green run:
# it happens when it is ASKED, with `AXIOM_BLESS=1` - the spelling every
# blessable gate in this repository already uses - and only over rows
# THIS process replayed, in this order, from the anchor.
# ---------------------------------------------------------------------
if [[ "$bless" == 1 ]]; then
  echo
  echo "== AXIOM_BLESS=1: advancing $checkpoint =="
  if (( ! full )); then
    fail "AXIOM_BLESS=1 without --full: this run replayed $replayed of $nrows rows, and a prefix it did not derive is a prefix it cannot certify"
    echo "      Use:  AXIOM_BLESS=1 $0 --full"
  elif (( failed > 0 )); then
    fail "$failed check(s) failed above; nothing is blessed"
  else
    # The prefix is the LONGEST run of rows, from row 1, that this
    # process replayed and that names a committed seed. It stops at the
    # first row that was skipped - the anchor without cargo, a row whose
    # seed this host has no target for - because a checkpoint that
    # begins after the anchor certifies a chain with no root, which is
    # the one thing this gate exists to refuse. It stops before `next`
    # for the reason the section above gives.
    bk=0
    while (( bk < nrows )) && (( ${row_replayed[bk]} )) && [[ "${row_seed_short[bk]}" != next ]]; do bk=$((bk + 1)); done
    if (( bk == 0 )); then
      fail "no prefix to bless: row 1 (${row_seed_short[0]} from ${anchor:0:7} by ${row_method[0]}) was not replayed on this run"
      (( have_cargo )) || echo "      The anchor row needs cargo, and cargo is not on PATH."
    else
      bdig="$(checkpoint_digest "$chain" "$bk")"
      if [[ -z "$bdig" ]]; then
        fail "the first $bk rows of $chain cannot be digested; nothing is written"
      else
        {
          printf 'Rows covered:          %s\n' "$bk"
          printf 'Through seed:          %s\n' "${row_seed_short[bk-1]}"
          printf 'Prefix digest:         %s\n' "$bdig"
          printf 'Blessed:               %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          printf 'Replayed on:           %s (%s)\n' "$target" "$(llc --version 2>/dev/null | grep -m1 -i version | sed 's/^ *//')"
          printf 'Blessed by:            AXIOM_BLESS=1 scripts/check-seed-lineage.sh --full\n'
          printf 'Recomputed by:         scripts/check-seed-lineage.sh, on every run\n'
          printf '\n'
          cat <<'CKDOC'
`Prefix digest` is sha256 over the canonical text `checkpoint_material`
in scripts/check-seed-lineage.sh builds from the first `Rows covered`
rows of bootstrap/CHAIN: those row and orphan lines verbatim, every
short hash in them resolved to a full commit, the git object id of
every seed those commits carry, the sha256 of every walk list and patch
file they name, and the Rust anchor. The gate recomputes it on EVERY
run and replays the rows after it; when the recomputation disagrees
this file certifies nothing, the gate replays every row from the anchor
instead, and it stays red until the prefix is blessed again.

This is a record, not a signature. Whoever can edit a row of
bootstrap/CHAIN can recompute this digest too - what the file buys is
that they must do it in the same diff, where a reviewer sees a change
that re-certified the lineage rather than a one-character edit to a
table nothing re-derives. The nightly `--full` job re-derives every row
from the Rust anchor bb730db regardless of what this file says.

It never covers the newest row: blessing stops before any row written
`next`, so the link a push adds is replayed on that push.

Advance it with:   AXIOM_BLESS=1 scripts/check-seed-lineage.sh --full
CKDOC
        } > "$checkpoint"
        ok "blessed rows 1..$bk of $chain (through ${row_seed_short[bk-1]}), digest ${bdig:0:16}, written to $checkpoint"
        echo "     Commit it with the CHAIN it certifies; a later run recomputes the digest and"
        echo "     replays rows $((bk + 1))..$nrows."
      fi
    fi
  fi
fi

echo
if (( failed > 0 )); then
  echo "check-seed-lineage: $failed check(s) failed ($checks ok, $skipped skipped)"
  exit 1
fi
if (( full )); then
  echo "check-seed-lineage: $checks checks; the lineage replays from the Rust anchor to ${current:0:7} ($replayed of $nrows rows replayed$( (( skipped )) && echo ", $skipped skipped with the reason above"))"
elif [[ "$checkpoint_state" == valid ]]; then
  echo "check-seed-lineage: $checks checks; rows 1..$checkpoint_covers of $chain are the prefix $checkpoint certifies - re-derived here, not taken on faith - and rows $((first + 1))..$nrows were replayed, ending at the seed in the tree (${current:0:7})$( (( skipped )) && echo " ($skipped skipped with the reason above)")"
else
  echo "check-seed-lineage: $checks checks; the seed in the tree (${current:0:7}) reproduces from its predecessor, and $chain is a chain$( (( skipped )) && echo " ($skipped skipped with the reason above)")"
fi
